### ISSUE TITLE
Include app name in <title> tag of webpage

### ISSUE THREAD

**Issue by andyszy** [dust-tt/dust#102]
Current behavior: Currently when I have several Dust apps open in browser tabs, it's difficult to tell which is which, because they are all titled "Dust - andyszy". This also makes Chrome's omnibox less useful for quickly navigating back to a specific Dust app. 

Expected behavior: the <title> tag of the page should include the name of the Dust app I'm currently working on.

**Comment by spolu** [comment]
Duh! You got it :+1: Will get to it today.
