### ISSUE TITLE
(not run) ability to set icon on static data source (chat)

### ISSUE THREAD

**Issue by Yutcam** [dust-tt/dust#1206]
Pennylane builder [would like to personalize the icon](https://dust4ai.slack.com/archives/C05A4RWJQKC/p1691595439890789) of the Custom data sources to make those more identifiable by the end user. Today, they have a Custom Data Source for the Help Center and are thinking about adding a CDS for accounting. Ideally, they would like to help the end user differentiate the one from the other more easily.

**Comment by spolu** [comment]
We're not yet tracking "product updates" in Github. I think the go-to place for now for that is the Notion roadmap?

**Comment by spolu** [comment]
(as your title says it, def not a "run" issue/request)
