### ISSUE TITLE
Document timestamp set to last updated time not created time

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1219]
Initial asK: slack thread data should be the date of the message instead of the start of the thread.

We can't really do that but maybe we can use the last message time not the first one (cc @lasryaric)
I think the same can be done for Notion, GDrive and Github

We can probably run a migration for Notion, Slack (not sure?).

@fontanierh what about Github? 
@lasryaric what about GDrive (do we have the last updated time? If not let's fix that before we run the full resync)

**Comment by lasryaric** [comment]
If I understand correctly your request, it's already the case for Gdrive:
https://github.com/dust-tt/dust/blob/main/connectors/src/connectors/google_drive/temporal/activities.ts#L397

For Slack, we are using the first message, so we need to change that.
I will change it before re-running the full syncs.

**Comment by spolu** [comment]
@lasryaric we don't have full syncs planned for Slack do we?

**Comment by lasryaric** [comment]
@spolu no, we can write a migration, or we can re-full sync once the cached embeddings is live.

**Comment by fontanierh** [comment]
@spolu  
For notion it was already implemented last month (https://github.com/dust-tt/dust/pull/1021)
For GitHub, here's a PR that implements it: https://github.com/dust-tt/dust/pull/1222

**Comment by fontanierh** [comment]
Update: only Slack is missing, assigning @lasryaric ✨

**Comment by fontanierh** [comment]
It's fully implemented now, closing
