### ISSUE TITLE
Clean-up public API routes for the Assistant

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1329]
The conversation creation is blocked on my PR: https://github.com/dust-tt/dust/pull/1324 which is blocked on @PopDaph's PR: https://github.com/dust-tt/dust/pull/1303 but as soon as the queue gets processed we can fully clean-up the public API routes

**Comment by spolu** [comment]
https://github.com/dust-tt/dust/pull/1324 is ready for review to unblock this one

**Comment by lasryaric** [comment]
PR in review: 
https://github.com/dust-tt/dust/pull/1383
