### ISSUE TITLE
RetrievalAction component

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1343]
The component that covers everything related to retrieval. #1342 depends on this

**Comment by philipperolet** [comment]
Multiple UX topics, and how I plan to handle them
1. States of the component => computing parameters | retrieving docs | succeeded | failed => passed as a prop to the component
2. Color codes for chips are not explaining what the chips are => tooltip to do that
3. Chip label may be too long (e.g. long query) => tooltip too (tooltip format = [what] : [full content] e.g. "Semantic search query : lorem ipsum dolor sit"
4. Always display timeframe chip (null => "All time") and query chip (null => No query)

Seems the best tradeoff between shipping fast / having a minimal quality bar. Feedback welcome :)

**Comment by philipperolet** [comment]
Reminder of what the component should be. For this first iteration, the buttons (view / edit etc) won't be implemented


![Image](https://github.com/dust-tt/dust/assets/5437393/86c4eb90-7e11-4b5b-aa53-f84553dfd946)

**Comment by gabhubert** [comment]
for @Duncid

**Comment by philipperolet** [comment]
The [reference figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=148-2696&mode=design&t=mRPjM4RsYyWyzHOH-0)

This component is about the first 3 states (everything before "Answer")
