### ISSUE TITLE
Embedding and Vector Search support for Datasets

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#137]
We plan to add vector search and embedding support to Dust datasets.

We propose to add these capabilities as first-class citizen of Dust datasets vs incorporating that through an external integration to services such as Pinecone or Weaviate. The rationale is to optimize for ease-of-use and completeness as part of designing a Dust app.

## Rationale

If we were to solely rely on an external vector search integration such as a "Vector Search" block that would tap into provides such as Pinecone or other, the user experience would end-up greatly degraded as users would have to construct such semantically searchable datasets entirely outside of Dust.

Instead we propose to add this as a first-class feature to the existing Dataset abstraction enabling users to manage their datasets through the UI or by API while relying on Dust to automatically embed selected fields.

Our hypothesis is that most Dust users won't have the complexity of managing such external databases, in particular, this would be impossible just by using Dust. While this would not be an issue for elaborated users, this is a total blocker for more casual users.

The down-side is that our initial implementation probably won't scale as well as existing hosted solutions, but we believe we can mitigate that in the future internally as/if the need for very large datasets arise.

## Interface

Add an `embedding` property to datasets configurable from the UI or by API. The `embedding` property is an object defining the auto-embedding of the dataset by Dust, with the following properties:

- `field`: the field of the dataset to use for embedding
- `provider_id`: the provider of the embedding model
- `model_id` the id of the embedding model to use
- `status`: the status of the auto-embedding process, `initial`, `refresh`, `ready`

Add a reserved field to each element of the dataset:
- `_embedding`: which will hold the resulting vector

### API support for datasets

Datasets are versioned so we currently don't have granular insert/update of fields, the dataset being sent in its entirety each time. We probably need to revisit that, with version being updated at each insert/update.

- Creation
- Insert / Delete / Update

Question: do we need to explicit the schema of a dataset. Currently based on parsing the entire dataset.

### Auto-embedding

- Add embedding controls on datasets
- Build background jobs for initial embeddings and refresh on-demand: probably a queue system that gets filled as embedding requirements are created by operations on datasets

The actual management of embeddings could be externalized to a Pinecone or Weaviate but we'll probably start with an internal implementation that scans the entire dataset when a vector search is required. This will probably evolve in the future but right now there are size constraints on the datasets that make it a realistic first step.

### Documentation and UI

Obvious

**Comment by spolu** [comment]
More design notes here: https://docs.google.com/document/d/1NRlQSbcl-f--1JuozP84JTlLSH_5i2QZAKuyxbXabg4/edit#

**Comment by happysalada** [comment]
Thank you for the repo!
in the same vein, here is a list of integrations that are being built by other products
https://langchain.readthedocs.io/en/latest/modules/document_loaders/how_to_guides.html
https://llamahub.ai/

Just to give you more information, I came here looking to make a QA bot, similar to https://github.com/hwchase17/langchainjs/blob/main/langchain/src/chains/chat_vector_db_chain.ts

**Comment by spolu** [comment]
@happysalada thanks! once we have DataSources built up we'll add managed ingestion pipelines to make it super easy to construct them and keep them updated.

What data sources would you be interested in ooc?

**Comment by happysalada** [comment]
I'm interested in the pdf source, to try to refine a bot for book summaries.
Interested in the youtube-transcript source to verify if there can be proper summarization capacity for transcript or making a QA bot from several transcripts.
Depending on how you make the datasources, a google doc integration could be interesting. Google doc would enable non devs to edit potentially source data by themselves. I know google doc integration can be troublesome, so personally I'll try to show the dust ui first to see if everything couldn't be worked out from editing a dust block.
Last I'm a little interested in the audio transcript file, but since this needs a bit of compute power, I'm thinking it's going to need to come from somewhere else. (This might be a block that needs to be run on a server that you just access with a curl block from dust).

**Comment by happysalada** [comment]
I just thought, that it would be nice to get access to embeddings in a block. currently the llms are only for text completion.
If embeddings were available it would be easier to create a map reduce loop and send a dataset to a third party vector database.
(right now, the easiest work around looks like to just use a curl block for those).

**Comment by spolu** [comment]
Yes that's definitely the plan of course :+1:

**Comment by happysalada** [comment]
I have a question regarding this.
Most likely as a developper we will have a raw dataset (of question and answers for example). We will then need to enrich this with embeddings for example. At the moment, I have to process this on my own. If there was a block to save a result to create a new dataset that would be amazing. That way, I can upload the raw data, create a processing pipeline with dust.cc and save the processed data (including the embeddings) to use for my main pipeline. There might be a way to do this, I just haven't found it. (I'll be processing my data with a script for now, so no rush on this).

**Comment by spolu** [comment]
Yes. Data sources will live outside of apps and will be callable from any of your apps.

We will take care of embedding the data. And we will even take care eventually of the ingestion pipeline for you.

**Comment by happysalada** [comment]
Is there a way to disable caching on a block ? Ive run into trouble a couple of time, trying to rerun a pipeline where something changed, but the results werent picked up

**Comment by spolu** [comment]
> Is there a way to disable caching on a block ? Ive run into trouble a couple of time, trying to rerun a pipeline where something changed, but the results werent picked up

Yes by API (config) or in the UI the small database icon

**Comment by happysalada** [comment]
So that's what the database icon does! Thanks a lot!
(maybe just a hover over to explain what this does would be nice. I even tried to inspect the html to see if there was an sr-only directive. Of course now that you mention it it makes perfect sense).

**Comment by happysalada** [comment]
I have one more question if you don't mind.
What do you think about blocks that would take input sources and convert them to text. So for example "youtube video transcript", or "read pdf" (from a link or from a file upload).
Do you feel those should be part of dust, or do they belong somewhere else that will do the preprocessing so that dust will focus on the text ?
I need to extract text from some big pdfs (and many) and wondering if I should start coding something outside.

**Comment by spolu** [comment]
To be clear this is unrelated to "DataSources" right? Just for regular use as part of a Dust app?

We're contemplating adding transcription blocks and possibly PDF conversion blocks. They would have to be able to pull data by URL of course. But the timeline for these is unclear unfortunately. That's for Dust apps. 

We'll likely add PDF support when uploading documents to a DataSource as well.

**Comment by happysalada** [comment]
that's exactly what I'm looking for, thanks!

Last comment, the ability to use your own vector database would be really nice. I understand it would be for advanced users only, but you could have a block where you can select the provider (no need to support them all of course), this could potentially be a shortcut to providing something. (completely understand if you prefer to launch something more polished).

Thanks again for the quick answers!

**Comment by spolu** [comment]
Closing as we now support DataSources: https://docs.dust.tt/data-sources-overview
