### ISSUE TITLE
ECONNREFUSED in local run web app

### ISSUE THREAD

**Issue by oneilsh** [dust-tt/dust#138]
I am working on getting the web application running on my local machine, and I kept running into this error:

```
error - TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:12789:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handler (webpack-internal:///(api)/./pages/api/apps/[user]/index.js:79:23)
    at async Object.apiResolver (/Users/oneils/Downloads/dust/front/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (/Users/oneils/Downloads/dust/front/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/Users/oneils/Downloads/dust/front/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/Users/oneils/Downloads/dust/front/node_modules/next/dist/server/router.js:253:36)
    at async DevServer.run (/Users/oneils/Downloads/dust/front/node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (/Users/oneils/Downloads/dust/front/node_modules/next/dist/server/dev/next-dev-server.js:743:20)
    at async DevServer.handleRequest (/Users/oneils/Downloads/dust/front/node_modules/next/dist/server/base-server.js:322:20) {
  cause: Error: connect ECONNREFUSED ::1:3001
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3001
  },
  page: '/api/apps/[user]'
}
```

In `.env.local` I have `URL` set to `http://localhost:3000` and `DUST_API` set to `http://localhost:3001` as recommended. Following [this](https://stackoverflow.com/questions/72390154/econnrefused-when-making-a-request-to-localhost-using-fetch-in-node-js) stackoverflow answer I added

```
import dns from 'node:dns';
dns.setDefaultResultOrder('ipv4first');
```

to `pages/api/apps/[user]/index.js` and the error has gone away :) 

Not sure if this is something specific to my setup, but thought I'd report it.

(PS - thank you for creating this amazing tool!)

**Comment by oneilsh** [comment]
Update: I later got the same error via a call the next library, after some more it looks like it's caused by an `::1      localhost` entry in my `/etc/hosts` (I'm on a mac), after removing it things are working better. 

However, when this error did trigger (via a cURL block), it set the run into a "running" state blocking any interaction. I got this on the publicly hosted dust.tt as well - I have a run of this app: https://dust.tt/oneilsh/a/553e1e8525 that's sitting in "Running" and I can't stop or start any more runs for it.

**Comment by spolu** [comment]
> Update: I later got the same error via a call the next library, after some more it looks like it's caused by an `::1 localhost` entry in my `/etc/hosts` (I'm on a mac), after removing it things are working better.

Thanks for the report and the proposed work-around.
 
> However, when this error did trigger (via a cURL block), it set the run into a "running" state blocking any interaction. I got this on the publicly hosted dust.tt as well - I have a run of this app: https://dust.tt/oneilsh/a/553e1e8525 that's sitting in "Running" and I can't stop or start any more runs for it.

It looks like even the block before never got to execute. I will investigate what happened here and will unblock your app right away.

**Comment by spolu** [comment]
Found the error here, investigating:
```
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', src/http/request.rs:108:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[!] Run error: Block execution spawn error: task 17566 panicked
```

**Comment by spolu** [comment]
Huh that is quite unexpected...

**Comment by spolu** [comment]
Ah no, I understand. Due to the replacement of `{{ QUERYURLS.completion.text }}` in the cURL request URL, the URL is invalid and the builder errors. I will add a case to properly catch that.

**Comment by spolu** [comment]
Fixed with this commit

**Comment by spolu** [comment]
Also fixed state of https://dust.tt/oneilsh/a/553e1e8525 :+1:

**Comment by wooters** [comment]
@spolu I just ran into the ECONNREFUSED issue that @oneilsh reported. His fix (modifying `pages/api/apps/[user]/index.js`) worked for me.

Not sure if someone was planning to submit a PR for this, but if not, I’d be happy to.

**Comment by spolu** [comment]
Yes that would be great!

**Comment by onurgu** [comment]
I was also hit by this, I fixed manually.

**Comment by spolu** [comment]
Thanks @gmpetrov for the super clean fix
