### ISSUE TITLE
Handle which profile pic appears when viewing a shared conversation

### ISSUE THREAD

**Issue by gabhubert** [dust-tt/dust#1437]
Pennylane has spotted the bug and reacted thinking it could have been an impersonation, which isn't something we want.

Discussed that in v2 we accept users to see avatars of other ws users, so it seems we could have that behaviour. 

My take: if we are confident v2 is with Pennylane within 7 business days, do nothing, else fix

**Comment by PopDaph** [comment]
PR here: https://github.com/dust-tt/dust/pull/1447
