### ISSUE TITLE
Install problem at step: “Start Front on SQLite"

### ISSUE THREAD

**Issue by wooters** [dust-tt/dust#145]
Hi everyone 👋, thank you for creating this awesome project! I’m excited to get started. 

I’ve run into a problem during local install. I searched through the issues and didn’t see anything similar. I’m hoping someone may be able to guide me.

When I get to step 4 of [Start Front on SQLite](https://github.com/dust-tt/dust#start-front-on-sqlite), I run into this:

```
$ FRONT_DATABASE_URI=sqlite:front_store.sqlite ./init/init.sh
/Users/charleswooters/projects/dust/front/node_modules/sequelize/lib/sequelize.js:136
      throw new Error("Dialect needs to be explicitly supplied as of v4.0.0");
            ^

Error: Dialect needs to be explicitly supplied as of v4.0.0
    at new Sequelize (/Users/charleswooters/projects/dust/front/node_modules/sequelize/lib/sequelize.js:136:13)
    at file:///Users/charleswooters/projects/dust/front/lib/models.js:159:23
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

Node.js v19.6.0
```
It looks like it may be an issue with versions of *something*, but I’m not sure how to resolve this. 

Any suggestions would be most welcome! Thanks!

**Comment by wooters** [comment]
Looking at the errors a bit more closely, I think maybe I need to set the `XP1_DATABASE_URI` in addition to `FRONT_DATABASE_URI` before calling ./init/init.sh

I’ll give that a try

**Comment by wooters** [comment]
Okay, I think that might have worked. I did this:
```
XP1_DATABASE_URI=sqlite:xp1_store.sqlite FRONT_DATABASE_URI=sqlite:front_store.sqlite ./init/init.sh
```
and it seemed to run. I’m not sure if I used the correct value for `XP1_DATABASE_URI`. Does that look okay?

**Comment by wooters** [comment]
Looks like I needed to do one more thing. I had to add `XP1_DATABASE_URI=sqlite:xp1_store.sqlite` to the `front/.env.local` file.

Once I did that, everything seems to be running fine. 🎉 

Thanks again for this awesome project!

**Comment by onurgu** [comment]
I had the same problem even if I followed the current README. I had to modify these lines

```
const { FRONT_DATABASE_URI } = process.env;
const sequelize = new Sequelize(FRONT_DATABASE_URI);
```

to make it work.

**Comment by spolu** [comment]
Closing since README has been updated :+1:
