### ISSUE TITLE
Input bar seems to be slow or CPU bounding

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#1482]
When typing in the input bar for sending a new message, I can feel some slowness and the text I typed takes a second or two to show up sometimes.

**Comment by spolu** [comment]
So is this only when the dev tools are opened?

**Comment by lasryaric** [comment]
I think we can close this issue.
The UI was especially slow because I had > 6 agent message in a "created" state, triggering 6 events stream, taking all the available http slots to the origin.

I have not seen any slowness since we fixed that.
