### ISSUE TITLE
Investigate slack bot manifest

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1529]

**Comment by lasryaric** [comment]
Looking at the "dynamic manifest" discussed earlier today [here on Slack](https://dust4ai.slack.com/archives/C050SM8NSPK/p1695026326188869?thread_ts=1695024753.817279&cid=C050SM8NSPK).

The problem I see for now is that there is a Slack screen saying "Choose your workspace to develop your app".



![Image](https://github.com/dust-tt/dust/assets/358965/a3c4c9be-c059-4a27-a08d-d43993a53f70)

Is that a red flag for you @Duncid @gabhubert ?

**Comment by gabhubert** [comment]
making sure I understand. The ux for an admin would be that they need to
pick their workspace? That seems ~peaceful if the upside is that they can
get a @soupinou running on their Slack in a few seconds right? What's the
threat/risk in your view?

**Comment by Duncid** [comment]
I'd love to see the video @lasryaric as I don't fully understand from the screenshot

**Comment by gabhubert** [comment]
++

**Comment by lasryaric** [comment]
Per IRL discussion, we decided to not move forward with the app manifest option because this is a developer workflow, and it's not fitting our needs as we initially thought.

We'll explore interactive messages which seems to be properly supported by the API.
