### ISSUE TITLE
Mentions in inputbar: allow mentions to work after typos

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#1532]
Currently, on typo on the agent's name, a state in which no more agents match will occur most of the time which will exit autocomplete mode. If pressing del to correct, mention mode is lost and we have to completely delete the mention and start again with @ (without typo) to make the mention be accounted for

**Comment by spolu** [comment]
Yep. Slack does this. I think it's a bit advanced advanced but would be nice to have

**Comment by philipperolet** [comment]
Assigning @flvndvd since his inputbar refactor will fix this ! 💪 🔥
