### ISSUE TITLE
When mentioning @Test the configuration Id appears

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1568]
Super weird that it happens just for @Test on Dust workspace?

![Image](https://github.com/dust-tt/dust/assets/15067/45115de7-5966-45ea-99b7-6ff58c2a89d0)

cc @PopDaph

**Comment by PopDaph** [comment]
I made some tests and it looks like it's broken when the sId starts with a number 😬

**Comment by spolu** [comment]
Damn

**Comment by spolu** [comment]
we need {sId=xxx} I guess?

**Comment by spolu** [comment]
checking the exact good syntax for such attrs...

**Comment by PopDaph** [comment]
Got the same conclusion as you! https://github.com/dust-tt/dust/pull/1617
