### ISSUE TITLE
non upgraded workspace have only access to small models

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1577]

**Comment by philipperolet** [comment]
Will add globalAgents: to limits, as list of agentconfigurations sId
Null will mean no limit (just as -1 means no limit for numeric limits)

**Comment by spolu** [comment]
hmmmm it's super granular let's chat tomorrow about a less granular solution. Not sure I have it yet....

**Comment by spolu** [comment]
OK so let's:

- Add a `large_model` flag on the model spec that @fontanierh built yesterday
- Add a `large_model` boolean on plan (migrate existing plan to true) update upgrade logic
- Check for that flag in `getAgentConfiguration`
- Turn the throw in `postNewUserMessage` (and friends) in a skip if getAgentConfguration is not found (return `{ row: null and m: null }` and filter)
- Add a status for `require_upgrade` for global agents and return that so that we can act on it in UI (not show in InputBar (should alreaday be filtered by @PopDaph latest PR), and deactivate the toggle (set to off) in the list of global agents with a DropDown to contact us.
- The goal is for them to become available automatically once they upgrade (which should be the case as per above)

**Comment by spolu** [comment]
This obviously lies on the critical path to switch let's push this out this morning 🔥

**Comment by philipperolet** [comment]
Related discussion: https://dust4ai.slack.com/archives/C050SM8NSPK/p1695368241304159

**Comment by philipperolet** [comment]
How would the dropdown to contact us on the list of global agents look? do we already have one somewhere? @Duncid

**Comment by Duncid** [comment]
I think it needs to be a design task before it's a eng task!

**Comment by spolu** [comment]
We need it to rollout v2 so we'll stick with an alert but let's think about our paywall UX as a fast follow-up task :+1:
