### ISSUE TITLE
Displaying Tabs in message (Markdown) looks better.

### ISSUE THREAD

**Issue by Duncid** [dust-tt/dust#1590]
From:
![Image](https://github.com/dust-tt/dust/assets/4435185/d93f1db8-3c6a-4a13-a2a8-c98f0ce14dcb)

To:

![Image](https://github.com/dust-tt/dust/assets/4435185/c1a13442-15c7-4dc3-bd19-4656d2c0484d)

**Comment by spolu** [comment]
Thanks for filing!
