### ISSUE TITLE
Adding a blinking cursor while streaming text

### ISSUE THREAD

**Issue by Duncid** [dust-tt/dust#1591]
![Image](https://github.com/dust-tt/dust/assets/4435185/e63ba075-02d9-4fab-86d0-25bda86d83a8)

Color Success-400

**Comment by spolu** [comment]
Nice

**Comment by lasryaric** [comment]
PR in review.

**Comment by Duncid** [comment]
Looks awesome :)

**Comment by lasryaric** [comment]
Deploying :)
