### ISSUE TITLE
User can "react" with an emoji on messages

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1620]
![Image](https://github.com/dust-tt/dust/assets/4435185/26402567-f0e0-4ba9-a550-2908961f4cdb)

Clicking on the Button opens a dropdown with all emojis, ideally something similar to slack's (probably a library doing that out there?).

After clicking, emoji is added on the right with a number (of people who clicked it).
Tooltip says the different people who reacted for a given emoji.
Clicking on an emoji in the list is a toggle vote / unvote.
An emoji going down to 0 count disappear.

![Image](https://github.com/dust-tt/dust/assets/4435185/5c10e9bc-e6a8-4686-8032-dc634e6cc449)

**Comment by spolu** [comment]
Assigning to you @PopDaph

**Comment by PopDaph** [comment]
Oops yes thanks! 🙇🏻‍♀️
