### ISSUE TITLE
Participants of the conversation are displayed in the HeaderBar

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1621]

**Comment by spolu** [comment]
Context: https://dust4ai.slack.com/archives/C050A0S2Z7F/p1695152116880219

**Comment by PopDaph** [comment]
Problem with that is that in the participants tables only stores the user if there's a user and from the user we do not have the picture url from the user. 


Proposal: 

1/ Edit the model `ConversationParticipant` to:
-  set the userId optional
-  store `userContextProfilePictureUrl` , `userContextUsername`, `userContextTimezone`, `userContextFullName ` and `userContextEmail`.

2/ Add to the list of participants even tho there's no user id (conversation initiated on Slack).


Then if we want to be super clean, we could

3/ Attach a UserMessage to a participant and remove `userContextProfilePictureUrl` , `userContextUsername`, `userContextTimezone`, `userContextFullName ` and `userContextEmail` from userMessage, to fetch it from the `ConversationParticipant` table.

WDYT @spolu ?

**Comment by PopDaph** [comment]
Discussed IRL: we want to keep simple so for now we will loop on all agent & user messages to grab the names and pictures and we won't use the participant model for that

**Comment by PopDaph** [comment]
Shipped!
