### ISSUE TITLE
Users can edit their messages

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#1639]
1st step is to allow editing without supporting agent mentions when editing (but user mentions can be ok)
2nd step is to allow new agent mentions
3rd step is to handle existing mentions: re-run on edit? or provide a re-run button on agent messages whose user message was edited?

**Comment by spolu** [comment]
Worked on here: https://github.com/dust-tt/dust/pull/4945

Almost ready to ship

**Comment by spolu** [comment]
Clsoing as this was attempted discussed and decided a no go

**Comment by Duncid** [comment]
@spolu would be cool to have rational of decision for traceability!

**Comment by spolu** [comment]
See the PR linked :+1: https://github.com/dust-tt/dust/pull/4945
