### ISSUE TITLE
Figure out and implement scrolling while streaming

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1648]
See what ChatGPT does

I thiiink you want to scroll if you're at the bottom, otherwise not scroll on streaming

**Comment by lasryaric** [comment]
Taking this

**Comment by spolu** [comment]
Please focus on the two others if we want to switch today 👍

**Comment by spolu** [comment]
Slack bot to v2 is way higher prio this one could be post switch almost :)

**Comment by lasryaric** [comment]
That goes without saying :)

**Comment by lasryaric** [comment]
(I should have clarified it though. I will un-assign it to allow someone
else to move on this one if I am still on the Slack bot).

**Comment by spolu** [comment]
Let's give it a try
