### ISSUE TITLE
Figure out FAQ question

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1659]

**Comment by Yutcam** [comment]
Suggestions: 
- What can I use the Assistant for? 
- How do I access the Assistant? 
- Why use gpt4 or claude? 

ping @Duncid

**Comment by Duncid** [comment]
IMO, it should be very easy to change and change often.

- @Yutcam how comfortable are you with github?
- @PopDaph can we have a notion page pointing directly to the files and sections where we can edit them in the code?

Suggestions:
- Admin
  - What can I use the Assistant for?
  - What are custom Assistants?
  - What customized Assistants should I create?
  - How can I make assistant smarter with my own data?
  - What's the level of security and privacy dust offers?
- Builder
  - What can I use the Assistant for?
  - What are custom Assistants?
  - What customized Assistants should I create?
  - How can I make assistant smarter with my own data?
  - What's the level of security and privacy dust offers?
- User
  - What can I use the Assistant for?
  - What are the limitations of Assistants?
  - Who creates custom Assistants?
  - How do Assistant work exactly?

**Comment by Yutcam** [comment]
@Duncid never used it, but I can learn. cc @PopDaph

**Comment by PopDaph** [comment]
> IMO, it should be very easy to change and change often.
> @PopDaph can we have a notion page pointing directly to the files and sections where we can edit them in the code?

Not MVP, but yes at some point we can make it easier for you to configure FAQ questions! 


### Let's align for the MVP: 


So top question = 
```
How can I interact with an assistant?
```

Then bottom questions, can we pick 3 that are relevant for a user? 🙏 
If we are unsure about what example would make sense with @\helper, we can give 3 examples with other assistants depending on which are activated. We would brand our global assistants. WDYT?

**Comment by PopDaph** [comment]
OK so top question = 
> How can I interact with an assistant?

Bottom questions = 
> What can I use an Assistant for?
> What are the limitations of Assistants?
> Who creates Assistants?
> How do Assistants work exactly?


I removed custom from the 3rd bottom questions because users have no notion of Dust Assistants / Custom Assistants as they don't have access to the builder page. 

I'm opening a PR

**Comment by Yutcam** [comment]
@spolu if it looks good to @Duncid it is yes. We can keep iterating on it.

**Comment by spolu** [comment]
@PopDaph can we do different questions per role as proposed by @Duncid ?

**Comment by PopDaph** [comment]
> @PopDaph can we do different questions per role as proposed by @Duncid ?

Yes, on it! Will come up with a proposal on a PR, based on what was said here.

**Comment by spolu** [comment]
\o/

**Comment by PopDaph** [comment]
https://github.com/dust-tt/dust/pull/1688
