### ISSUE TITLE
Contribution on the core package

### ISSUE THREAD

**Issue by gmpetrov** [dust-tt/dust#166]
Can you recommend a good first issue related to the core package for a Rust beginner?
I wanted to play with Rust for a while now, it might be a good occasion 😃

**Comment by spolu** [comment]
I would suggest:
- https://github.com/dust-tt/dust/issues/114
- Relatedly, you could also play with adding a command line command to delete a DataSource.
- https://github.com/dust-tt/dust/issues/144

#144 is a bit more heavy but quite straightforwrad nonetheless. Happy to take the front-end part of it if you decide to go with it.

**Comment by gmpetrov** [comment]
Thx going to look at #144

**Comment by spolu** [comment]
Awesome. Don't hesitate to ping me here or on Discord.
