### ISSUE TITLE
Run Migration on all workspaces

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1660]
@lasryaric can we tweak the migration so that ti does not take conversations that are less than 1h old

That way we can run it once and then re-run it post switch without missing messages from "live conversations"

**Comment by lasryaric** [comment]
Sounds good. Taking that.

**Comment by spolu** [comment]
ETA?

**Comment by lasryaric** [comment]
30 minutes.

**Comment by lasryaric** [comment]
Migrations as not been done on workspaces yet but the command is available and can be run at anytime.
