### ISSUE TITLE
Move the slack bot to v2

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1661]
We want to move the slack bot to v2 API and links

We can likely do so before the switch (slack conversations will be redirected for a small window of time to the new assistant which is fine)

Needs to render bot mentions
Citations can stay as is (and add something to say they are available by clicking on the link)

cc @gabhubert

**Comment by lasryaric** [comment]
Happy to take that too.

**Comment by spolu** [comment]
@lasryaric 👍 make it per workspace see #1670 

What's your ETA?

**Comment by lasryaric** [comment]
I don't know yet for this one. I will report back here asap.

**Comment by lasryaric** [comment]
It's going to be a bit longer. targeting  3pm now.

**Comment by lasryaric** [comment]
Code is written, testing it now.

**Comment by lasryaric** [comment]
Forgot that I will have to wait for the agent message for the streaming (I was listening on the id returned by postUserMessage, which is the userMessage id). 
Now working on getting the agent message id to keep testing.
