### ISSUE TITLE
front: typescript?

### ISSUE THREAD

**Issue by gmpetrov** [dust-tt/dust#168]
W'd you be interested in migrating the front codebase to typescript? 

It will improve the developer experience and bring a bit more robustness to the codebase.
TS is retro-compatible with JS so the migration could happen gradually.

**Comment by spolu** [comment]
Yes definitely interested in that move, I would start with `lib` and move my way up. Something we'll surely be working on soon.

**Comment by spolu** [comment]
Now fully type-scripted :+1:
