### ISSUE TITLE
Adding search to Assistant Picker

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1721]
![Image](https://github.com/dust-tt/dust/assets/4435185/2b92c7bb-404a-4d25-91d2-5d3748e2a68e)

**Comment by spolu** [comment]
This task focus on Search #1622 focuses on edit/manage

**Comment by spolu** [comment]
@Duncid concerning this do we go with a scroller if there are many assistants?

**Comment by Duncid** [comment]
@spolu yes the idea is that it can scroll
