### ISSUE TITLE
Kill chat v0 in front

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1754]

**Comment by philipperolet** [comment]
Should we support old links to conversations? => yes, via redirects
Other links => no

**Comment by philipperolet** [comment]
Not sure what you mean here; redirects work on my side; let's talk quickly IRL so I can understand

**Comment by philipperolet** [comment]
Other point: getUserMetadata / setUserMetadata in user.ts lib => do we plan to reuse them soon ? (currently not used anymore after deletion of v0)

**Comment by spolu** [comment]
As per IRL we do have sId preserved so we can redirect \o/
