### ISSUE TITLE
DataSource Upsert/Delete Block

### ISSUE THREAD

**Issue by realglyph123** [dust-tt/dust#177]
On the recent documentation, I see that you can delete and create documents using the API, however I'd like to see this in action with DataSources

- Create & Delete DataSource Block

**Comment by spolu** [comment]
Just to be super clear. You'd like to have the ability to upsert / delete a document from a Dust app?

**Comment by realglyph123** [comment]
Yes.

**Comment by spolu** [comment]
Closing for now, as Data Source are really though of as "source of data" that should be managed outside of the execution loop of an app.
