### ISSUE TITLE
Handle multiple-user conversation assistant responses

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#1794]
When multiple users can call assistants
- either the assistant should mention the user it's answering, or quote their message
- or the assistant response should be inserted exactly below the triggering user message, even if it was created later in conversation (because either another user spoke at the same time, or the assistant was newly mentionned when a user edited their message)

**Comment by spolu** [comment]
The only case is if we edit the user message after another user message has been posted

That seems like not a real problem right now is it?

**Comment by spolu** [comment]
This is likely not a problem now. Closing in favor of other tasks. Feel free to reopen if needed
