### ISSUE TITLE
Agent toggling for Conversation

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1816]
- @agent auto toggles agent for whole conversation
- all toggled agents respond to every message
- with toggled agents if there is a specific @agent only this one answers
- toggles are visible in the dropdown menu of assistants (and upcoming top assistant list dropdown)

Visuals available in Figma

**Comment by fontanierh** [comment]
Agent toggling => sticky mentions. See conversation [here](https://dust4ai.slack.com/archives/C050A0S2Z7F/p1695827185710359)
