### ISSUE TITLE
Add support for `ContentFragment` in conversation

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1841]
ContentFragments are pieces of content injected in the conversation context.

They will be used to:
- inject a document in context
- inject an opened tab the day we have refactor the extension
- inject the context of a slack thread when working with the slack bot

This will likely be a new action on the conversation, something like `postNewContentFragment`

**Comment by fontanierh** [comment]
ContentFragments will be stored as messages (a new 3d type of message)
