### ISSUE TITLE
postgres BIGINT is returned as string in sequelize

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1855]
This means we lie in our RetrievalDocumentType when they come from the DB

**Comment by spolu** [comment]
Maybe we can just use INT or otherwise figure out something with this: https://github.com/sequelize/sequelize/pull/5796/files https://github.com/sequelize/sequelize/issues/2383#issuecomment-58006083

**Comment by fontanierh** [comment]
I suppose you are talking about [this](https://github.com/dust-tt/dust/blob/f660d8f3411f931988bcdfe0d171953a187962ed/front/lib/models/assistant/actions/retrieval.ts#L355-L358) ? If so, I think this should be an actual Datetime column, no ? It's easy to get it back into a number when we need to.

**Comment by spolu** [comment]
Yes that’s also a solution 👍
