### ISSUE TITLE
"Suggestions of follow-up" behaviour for assistant message

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#1861]
Related to [Exhaustive mode for DS Retrieval](https://www.notion.so/dust-tt/DesignDoc-Exhaustive-mode-for-datasource-retrieval-202d685b1ccb4e84ac6df5c40fa90dc0)
- Add a Follow-up component at the end of an agent message
- Takes a list of follow-ups and displays them cf figma in design doc
- followup creation logic can depend on the whole message (action, generation). Basically, make a list of follow-up behaviours associated with tests on whether they apply to a message. Each follow-up behaviour takes an agent message and returns either a follow up or null. The list of followups to display is map(listOfBehaviours applied to agentMessage).filter(not null)

**Comment by spolu** [comment]
Isn't this task a bit prematured. We haven't even yet decided exactly how that follow-up would happen?

Am I missing something? Seems like It depends on many other open questions that haven't been properly speced yet right?

**Comment by spolu** [comment]
Just want to avoid resources being put in places before we have the buy-in of everyone on a given approach.

**Comment by philipperolet** [comment]
This is mostly a general component / UX task, mostly independent on the specific use we would have for it for exhaustive retrieval

But no prob to hold 👍

**Comment by philipperolet** [comment]
I can take a few fixes / AgentMessage and Assitant builder UI tasks in the meantime

**Comment by philipperolet** [comment]
Moving that out of pending backlog. This feature was initially required in the early design of exhaustive retrieval action.
Following a discussion with @Duncid and @spolu , it will in fine not be needed (a "continue" button will be used instead)
There is then no more reason to prioritize this for now

**Comment by spolu** [comment]
Closing as stale
