### ISSUE TITLE
Remove participants from ConversationType

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#1883]
The list of participants is currently computed server side in lib/api but really it can be computed from the conversation so it should not exist on the ConversationType as it does not bring any new capability, it's just a convenience for our product to have it here.

Let's either move its computation fully client-side or create separate endpoints to compute them and have access to them. Both are fine.

**Comment by PopDaph** [comment]
@spolu was about to start this task but I have a second thought. 

There is no additional query to fetch the list of participant, we just take advantage of a loop on messages in `getConversation` to fill the list of participants, and return them: https://github.com/dust-tt/dust/blob/main/front/lib/api/assistant/conversation.ts#L404

So I think we shouldn't change the way it's done. OK for you?

**Comment by spolu** [comment]
Well the only tension is for the public API this field really is not needed. What is the rationale for keeping it server-side versus moving the logic client-side? The rationale I see for doing it is simplifying the object we return from `GET /.../conversations/[cId]`

**Comment by PopDaph** [comment]
https://github.com/dust-tt/dust/pull/1935 🙇🏻‍♀️
