### ISSUE TITLE
Better discoverability for Assistants

### ISSUE THREAD

**Issue by Duncid** [dust-tt/dust#1893]
# Scope

Discovering assistants of a workspace and their purpose is easier.

# Solution
## New screens
We create a gallery view showing assistants + description and a detailview showing instructions and datasources:
![Image](https://github.com/dust-tt/dust/assets/4435185/2c59755b-4127-4501-bf8a-be71cfb2c07c)

### On "new conversation" contextual help:

![Image](https://github.com/dust-tt/dust/assets/4435185/a8073084-4e4b-4816-ba27-b2c232b207a1)

See all assistant now opens the gallery.
Clicking on "..." opens the detail view of each assistant.

### In the assistant picker

Access to gallery:
![Image](https://github.com/dust-tt/dust/assets/4435185/5186a20c-2b39-4b40-afed-50549cf9cb4d)

Access to detail view on roll over via a "more" IconButton:

![Image](https://github.com/dust-tt/dust/assets/4435185/30fda1e0-8c73-4b32-9aae-f8f0c2f40686)

**Comment by Duncid** [comment]
FYI @gabhubert @spolu

**Comment by spolu** [comment]
Looks super reasonable. Where would the galery live and how would it relate to the existing builder page for a builder?

**Comment by Duncid** [comment]
> Where would the gallery live and how would it relate to the existing builder page for a builder?

It lives as described here (multiple access points).
It does not necessarily need to relate to existing builder page, but we could add manage and create buttons for builders.

**Comment by spolu** [comment]
ack :+1:

**Comment by spolu** [comment]
@lasryaric this is the on :)

**Comment by lasryaric** [comment]
Thanks @spolu. Assigned it to myself. I will start working on it either this afternoon or on Monday.

**Comment by spolu** [comment]
Was covered as part of ahuna
