### ISSUE TITLE
Install error on Step 4 of Start Front on SQLite

### ISSUE THREAD

**Issue by iradeyal2** [dust-tt/dust#1906]
Very excited to try out Dust after reviewing the awesome examples! I'm trying to install locally and getting an error on this step:

Run `XP1_DATABASE_URI=sqlite:xp1_store.sqlite FRONT_DATABASE_URI=sqlite:front_store.sqlite ./admin/init_db.sh`

Here's the error. Is this an array issue? Any suggestions would be appreciated!

name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: near "[]": syntax error] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'CREATE TABLE IF NOT EXISTS `agent_data_source_configurations` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `tagsIn` VARCHAR(255)[], `tagsNotIn` VARCHAR(255)[], `parentsIn` VARCHAR(255)[], `parentsNotIn` VARCHAR(255)[], `retrievalConfigurationId` INTEGER NOT NULL REFERENCES `agent_retrieval_configurations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `dataSourceId` INTEGER NOT NULL REFERENCES `data_sources` (`id`) ON DELETE CASCADE ON UPDATE CASCADE);'
  },
  original: [Error: SQLITE_ERROR: near "[]": syntax error] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'CREATE TABLE IF NOT EXISTS `agent_data_source_configurations` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `tagsIn` VARCHAR(255)[], `tagsNotIn` VARCHAR(255)[], `parentsIn` VARCHAR(255)[], `parentsNotIn` VARCHAR(255)[], `retrievalConfigurationId` INTEGER NOT NULL REFERENCES `agent_retrieval_configurations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `dataSourceId` INTEGER NOT NULL REFERENCES `data_sources` (`id`) ON DELETE CASCADE ON UPDATE CASCADE);'
  },
  sql: 'CREATE TABLE IF NOT EXISTS `agent_data_source_configurations` (`id` INTEGER PRIMARY KEY AUTOINCREMENT, `createdAt` DATETIME NOT NULL, `updatedAt` DATETIME NOT NULL, `tagsIn` VARCHAR(255)[], `tagsNotIn` VARCHAR(255)[], `parentsIn` VARCHAR(255)[], `parentsNotIn` VARCHAR(255)[], `retrievalConfigurationId` INTEGER NOT NULL REFERENCES `agent_retrieval_configurations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE, `dataSourceId` INTEGER NOT NULL REFERENCES `data_sources` (`id`) ON DELETE CASCADE ON UPDATE CASCADE);',
  parameters: {}
}

**Comment by spolu** [comment]
Hi @iradeyal2,

We don't support local installations anymore at this stage. Feel free to use our product directly at dust.tt.
