### ISSUE TITLE
Check that custom assistants using semantic search can be timeframed via instructions

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#1931]
- Create a custom assistant with a timeframe in the instructions
- Experiment on a few queries / varying the instructions

**Comment by philipperolet** [comment]
Results: https://www.notion.so/dust-tt/DesignDoc-Exhaustive-mode-for-datasource-retrieval-202d685b1ccb4e84ac6df5c40fa90dc0?pvs=4#d02554a5b9c540528671ccb6c59d4277

**Comment by spolu** [comment]
Can this be closed?
