### ISSUE TITLE
Render Markdown looses spaces indentation on user messages

### ISSUE THREAD

**Issue by PopDaph** [dust-tt/dust#1955]

**Comment by PopDaph** [comment]
https://dust4ai.slack.com/archives/C050A0S2Z7F/p1696434210053929

**Comment by PopDaph** [comment]
Discussed IRL with @spolu and we decided we would do nothing. 
Markdown specification treats leading spaces as insignificant & we decided to render user messages as markdown.

**Comment by spolu** [comment]
Vanilla explanation for future complainers available here: https://dust4ai.slack.com/archives/C05RR1QDGP3/p1696502360483569?thread_ts=1696437172.724099&cid=C05RR1QDGP3
