### ISSUE TITLE
[Slack-V2]  Add support for creating a Content Fragment when creating a conversation

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#1958]
Today there is an API endpoint to attach a content fragment on an existing conversation, but that means the content fragment won't be picked up by the agent message if a user message is set when creating the conversation.
For that reason, we need the following sequence of event to happen when calling `POST /api/v1/w/[wId]/assistant/conversations/index.ts`:
- (i) Create a conversation
- (ii) Create a content fragment linked to the newly created conversation 
- (iii) Create the user message

(ii) needs to be implemented.

**Comment by spolu** [comment]
We’ll also need to correlate slack threads and dust conversations in DB such that a follow up will insert the right intermediary fragment if applicable and continue the convo

can come as a follow up of course

**Comment by lasryaric** [comment]
It’s already correlated in the table slack_messages in connectors. I don’t
know if everything needed for the delta fragment is there though. I will
check that 👍

**Comment by spolu** [comment]
Yes we’ll likely need the last triggering message id?

**Comment by spolu** [comment]
(sorry this conversation was on the wrong issue I think)

Taking this one in any case

**Comment by spolu** [comment]
I realize now there might not be another issue to cover the creation of the content fragment by the slack bot?

**Comment by spolu** [comment]
Ah no there is #1960
