### ISSUE TITLE
[Slack-V2] Create a GET agent configurations API endpoint

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#1959]
The Slack bot will need to know the list of agent configurations available when receiving a request to be able to associate a mention on slack (eg: `@dust ~gpt-4 ....`) to an actual agent configuration.

The plan is pretty simple here: Add a v1/ API endpoint exactly like the existing `GET /api/w/0ec9852c2f/assistant/agent_configurations` endpoint.

The POST version is not needed.

**Comment by fontanierh** [comment]
https://github.com/dust-tt/dust/pull/1973
