### ISSUE TITLE
[Slack-V2] Make the bot answer with an agent picker if we could not route the message

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#1962]
If a message sent to the Slack bot could not be routed (ie: no linked channel, no ~mention), the slack bot should answer with a interactive select menu ([see example here](https://dust4ai.slack.com/archives/D050AFZJVEH/p1696338307895349)) to allow the end user to pick an agent and then post a user message with a mention to the select agent(s).

You can see the Slack interactive message documentation here:
https://api.slack.com/messaging/interactivity

**Comment by spolu** [comment]
Closing as stale

**Comment by lasryaric** [comment]
For the record we decided to not implement this for two reasons:
- Not important enough
- Users would get confused with a dropdown and potentially 100+ assistants in the list.
