### ISSUE TITLE
[Slack-V2] Implement the UI for associating an assistant to a Slack channel

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#1965]
Per [section #1 of the Slack design doc](https://www.notion.so/dust-tt/Design-Doc-Slack-bot-for-assistants-a23803db9aa346e9911846c08bca5c91?pvs=4#6be00ba3058f432d97f4c71df3a360e4), we need a UI element to link an assistant to a Slack channel (see details in the design doc).

The API endpoint to list the Slack channels already exists (`/connectors/:connector_id/permissions`) and there is a task to create the endpoint needed for the association between the Slack channel and the assistant #1963

**Comment by fontanierh** [comment]
pending some mystery solving [here](https://dust4ai.slack.com/archives/C050A0S2Z7F/p1696519086114809)
