### ISSUE TITLE
Figure out why we have error on datadog without message and stack trace

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#2010]
[Here](https://app.datadoghq.eu/apm/traces?query=%40_top_level%3A1%20env%3Aprod%20status%3Aerror&cols=core_service%2Ccore_resource_name%2Clog_duration%2Clog_http.method%2Clog_http.status_code&graphType=flamegraph&historicalData=false&messageDisplay=inline&query_translation_version=v0&shouldShowLegend=true&sort=time&spanID=8309397830528483110&spanType=service-entry&spanViewType=errors&timeHint=1696842886281&trace=27443220274382383432744322027438238343&traceID=2744322027438238343&start=1696842302800&end=1696843202800&paused=false) is an example of such error.

**Comment by spolu** [comment]
Moving back to known bugs

**Comment by spolu** [comment]
These errors are associated with `"Error uploading document to Dust."` eg: https://app.datadoghq.eu/logs?query=%22Error%20uploading%20document%20to%20Dust.%22%20&cols=host%2Cservice&event=AgAAAYtmt9mLKsP6OQAAAAAAAAAYAAAAAEFZdG10LVFJQUFBMV9oVURsWmxPTmdBRAAAACQAAAAAMDE4YjY2YjctZTllNC00MzIxLTliMGItMTJjYTdkZjgxZGEw&index=%2A&messageDisplay=inline&refresh_mode=sliding&stream_sort=desc&viz=stream&from_ts=1693379555658&to_ts=1693383155658&live=true

Which has error data. Bu these errors are AxiosErrors which are maybe not well supported by datadog?

No obvious action item here. Closing
