### ISSUE TITLE
Allow fuzzy search in the Assistants dropdown (of the InputBar)

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2019]
This is for the search component of the assistants dropdown. The goal is not to change the mention system.

**Comment by spolu** [comment]
Actually goal is to do the same for mention auto-complete in the input bar

**Comment by fontanierh** [comment]
Should we also do like slack ?
Slack treats some characters (eg, `.`, `_` `-`) as "word separators". The autocomplete surfaces items for which the query is a prefix of any "word". The "Sales_coach" example would be covered by this.
