### ISSUE TITLE
Citations UI: Chevrons to scroll by click on left and right

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#2027]
Add chevrons to the citations ui below, that make it scroll 

![Image](https://github.com/dust-tt/dust/assets/5437393/6584ec2e-6847-4a45-b9dd-384778ca6977)

just like e.g. 

![Image](https://github.com/dust-tt/dust/assets/5437393/673c52f2-8f3c-4d76-869f-e7a249eb7f97)

**Comment by spolu** [comment]
Not relevant anymore
