### ISSUE TITLE
In assistant, long lines of code in code blocks break the UI

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#2028]

**Comment by fontanierh** [comment]
here for example: https://dust.tt/w/0ec9852c2f/assistant/d6896998d2

**Comment by fontanierh** [comment]
![Image](https://github.com/dust-tt/dust/assets/14199823/1b909bfa-949d-4aa7-b65d-e572517b1590)

**Comment by spolu** [comment]
Ah we used to overflow on the right, the left overflow is new I believe...

**Comment by spolu** [comment]
@PopDaph we used to have a scroller for long code no?

**Comment by fontanierh** [comment]
Either side of the overflow sound not ideal no ? We should only overflow within the code block

**Comment by PopDaph** [comment]
> @PopDaph we used to have a scroller for long code no?

I think so yes 😕

**Comment by fontanierh** [comment]
taking
