### ISSUE TITLE
Add ability to update the organization-id

### ISSUE THREAD

**Issue by sam-cohan** [dust-tt/dust#216]
Right now, there is not good way to add the organization-id to outgoing requests (for OpenAI) as the code is commented out in three places in the openai.rs file. Need a mechanism to send the organization-id. I think the ideal situation would be to provide a default through an env-var (similar to the key), and then override-able from config hash of llm or chat block.

**Comment by spolu** [comment]
Thanks. Will attempt to address this tomorrow :+1:

**Comment by spolu** [comment]
Sorry for the delay. Will look into it ASAP :+1:

**Comment by fontanierh** [comment]
@sam-cohan You can now pass `openai_organization_id` in the model config when using the API

**Comment by spolu** [comment]
@sam-cohan had to revert the PR associated with this issue due to a small bug when streaming from OpenAI.

We will let you know once fixed and re-merged into `main` :+1:

**Comment by sam-cohan** [comment]
ok thank you!

**Comment by spolu** [comment]
Now fixed and deployed again :+1:

**Comment by sam-cohan** [comment]
Thanks!
