### ISSUE TITLE
[Doom] Make the dust assistant configurable

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2196]
Source: https://github.com/dust-tt/decisions/issues/105

Today, each data source has a setting defining if the datasource is to be included in `@dust` assistant.

Remove that setting and replace it with a "Manage" button on the `@dust` assistant.

<img width="964" alt="image" src="https://github.com/dust-tt/decisions/assets/4435185/eac5b6b9-3697-4b25-b097-dea92bf67ea8">

**Comment by spolu** [comment]
Some outstanding questions:

- there is no activate/deactivate?
- what if there is no data source? what does it mean to see it here? Is it activated ? is it not? 

cc @Duncid

**Comment by Duncid** [comment]
Here are my thoughts:
- @dust comes pre-activated
- It's by default on "all data sources"
- One can open and edit
- One cannot remove

Later on, we probably will have a capacity to deactivate it without removing it.

**Comment by spolu** [comment]
@Duncid so we add non connected data sources by default even if you previously edited it? There's a small weirdness here no?

**Comment by Duncid** [comment]
(FYI @gabhubert )

## @spolu 

> @Duncid so we add non connected data sources by default even if you previously edited it? There's a small weirdness here no?

> @Duncid so we add non connected data sources by default even if you previously edited it? There's a small weirdness here no?

IMO what we're missing is a setting of Search Data source" that would be "All available data source".

That would be the default setting for `@dust`.

If a user changes that setting, then the new settings apply.

## @fontanierh 

> What happens when the workspace has no data source ? Do we not show @dust  ? Do we show it, but it’s grayed-out and you cannot enable it ?

The above apply. It's set to "all data sources" but there are no data sources.

> Do we really want to move dust to “custom” assistants ? I understand that it’s now configurable, but it’s still not really a custom assistant ?

It's a good question.

1. If we take a "sandbox" approach, `@dust` is nothing more than a help created to avoid the original void.
It obey all the rules of custom assistants, can be removed, handle can change,…
Ultimately, members may use it or remove it entirely.

2. If we take a more driven approach, `@dust` is a specific assistant with specific  capabilities and users have limited choice on what they can do with it (can't change icon or name, can remove, can disable…).

IMO, the first option is the most interesting one, but the second one is easier to implement now.
I would start with 2.

**Comment by spolu** [comment]
>> What happens when the workspace has no data source ? Do we not show @dust ? Do we show it, but it’s grayed-out and you cannot enable it ?
>
> The above apply. It's set to "all data sources" but there are no data sources.

That's kind of broken in the interim where there are not data sources? Do we prefer deactivating Dust or having it reply an error (which would something generic when the all data source setting is set but there are none)

**Comment by spolu** [comment]
> 1. If we take a "sandbox" approach, @dust is nothing more than a help created to avoid the original void.
It obey all the rules of custom assistants, can be removed, handle can change,…
> 2. Ultimately, members may use it or remove it entirely.
>
> If we take a more driven approach, @dust is a specific assistant with specific capabilities and users have limited choice on what they can do with it (can't change icon or name, can remove, can disable…).
>
> IMO, the first option is the most interesting one, but the second one is easier to implement now.
I would start with 2.

I'm not attached to @dust being a special assistant at all... but it's an interesting question for sure.

**Comment by gabhubert** [comment]
> That's kind of broken in the interim where there are not data sources? Do we prefer deactivating Dust or having it reply an error (which would something generic when the all data source setting is set but there are none)

I think throw an error?

**Comment by spolu** [comment]
Counter proposal that to me feel like the path of least resistance:

- We keep the current DB schema and logic
- Dust is still presented in the top-level list
- Dust has a special config page (and therefore a special config button vs a toggle)
- The config page has the toggle + the list of all data sources with a toggle + some text to guide the user and explain them what's its purpose

How would you feel about that @Duncid @fontanierh 

I think it minimizes the "change" yet solve the initial problem or removing that settings screen on data sources. It's still easy to use.

By default connected data sources are added, static are not

If no datasource the assistant is deactivated and there's CTA to create a data source

**Comment by spolu** [comment]
Rationale:
- minimize change
- opportunity to explain value of it
- solves initial problem
- new entry point to CTA to create a data source
- Do not introduce a new concept "all data sources" which is easy to set but is likely leading to bad results for custom assistants in general

**Comment by Duncid** [comment]
> That's kind of broken in the interim where there are not data sources? Do we prefer deactivating Dust or having it reply an error (which would something generic when the all data source setting is set but there are none)

I don't think it's broken. When we ask to select a data source and there are no data source available it's broken.
But if we have a "god mode" setting tapping all data sources, I don't think anyone will be shocked that no data is recovered if no data has been added.

**Comment by Duncid** [comment]
I can work with @spolu 's proposal.
I tend to be attracted by the sandbox approach mostly because of esthetics (it's pure).

**Comment by spolu** [comment]
Can you define the "sandbox approach" :grimacing: not sure I put a concept on these words yet :)

**Comment by Duncid** [comment]
## Sandbox Design Approach
Concept: The Sandbox approach provides users with a set of tools or elements that allow them to create, explore, and interact in an open environment. There's no fixed path or specific goal, giving users freedom to experiment.

**Key Features:**

Open-ended gameplay or interaction.
User-driven outcomes.
Emphasis on exploration and creativity.
Less structured experience.

**Examples**: Legos, Capla, many video games, like "Minecraft" or "The Sims", use the sandbox approach where players can build and interact with the world as they see fit.

## Rollercoaster Design Approach
Concept: The Rollercoaster approach is a guided experience where users are taken on a predefined path with set outcomes. It's more linear and controlled, ensuring users experience content or interactions in a specific order.

**Key Features:**

Linear and structured experience.
Designer-driven outcomes.
Emphasis on delivering a specific story or experience.
Predictable and consistent for all users.

**Examples**: Many narrative-driven video games or interactive story apps provide a rollercoaster experience, guiding users through a story with specific events and outcomes.

In the context of product design these approaches can be used to determine how users interact with a product. A Sandbox approach might be more suitable for products that prioritize user creativity and personalization, while a Rollercoaster approach might be chosen for products that aim to provide a specific, consistent experience.

**Comment by Duncid** [comment]
When you buy a Lego, it can come already assembled or with a plan to assemble a certain piece.
But any lego can be broken down, modified, re-used for other purpose.

The rule is to never create a piece that is specific (or as little as possible).

**Comment by spolu** [comment]
Yep makes sense and aligned. I just a bit skeptical of the piece "include all data sources" I worry it's a foot gun for us

**Comment by Duncid** [comment]
> Yep makes sense and aligned. I am just a bit skeptical of the piece "include all data sources" I worry it's a foot gun for us

The choice can be framed as "Do we still want to push a general assistant approach (dust as we knew it 3 months back) or did we stop believing in it".

Consequence would be allowing god mode or denying god mode.
If we deny god mode, then is `@dust` is just our branded `@gpt` by default. We let people edit it however they like.

We can have an experience that guide people to assemble their first lego (dissociated from `@dust`).

**Comment by spolu** [comment]
I think leading people to build their @dust and not have one by default is directionally where we want to be for sure. But this will take concerted effort that is beyond the scope of removing the settings page on data sources :)

**Comment by spolu** [comment]
So all in all we're super aligned on the end state and we just take an intermediary step towards there pending the framing and implementation of a more advanced onboarding experience + template in assistant builder etc...

**Comment by spolu** [comment]
@fontanierh all good for you? What’s your take?

**Comment by fontanierh** [comment]
Aligned with your proposal, that's a good first step.

**Comment by fontanierh** [comment]
I'm working on making the page work, do you already have a rough idea of design @Duncid  ?

**Comment by fontanierh** [comment]
Functionally, I guess this is more or less what we want ? Obviously shouldn't look like this at all though

![Image](https://github.com/dust-tt/dust/assets/14199823/cd490bd8-6da4-4f8c-875b-bce42671924a)

**Comment by gabhubert** [comment]
- I think these are indeed the main functional affordances.
- in the future, I think we'll want to make the dust assistant able to ingest more company context (with impact on the preprompt). 
- let me know when to chime in on copy.

**Comment by fontanierh** [comment]
> let me know when to chime in on copy.

Whenever you are available, I'm ready for it @gabhubert  😄

**Comment by gabhubert** [comment]
HEADER
- change to: Manage Dust Assistant

TITLE
- icon should be Dust, not robot
- title: Dust Assistant
- tagline: Configure the @dust assistant for this workspace.

SECTION 1
- Add title above enabled: Availability
- Add tagline: Select whether or not @dust is available as a standalone assistant for this workspace.
- when enabled is NOT selected, we should have help text appear to specify behaviour on Slack 

SECTION 2
- Title: Data Sources
- tagline: Configure which connections and data sources will be searched by the Dust Assistant.

**Comment by fontanierh** [comment]
Thank you !

I am missing the CTA to add a new datasource if there are none yet. I'm still not clear what the behaviour is when `@dust` is enabled but there are no datasources ?

@gabhubert 

> when enabled is NOT selected, we should have help text appear to specify behaviour on Slack

lmk if you have ideas regarding this. I can think of 3 possibilities:
1/ The default answer on slack (i.e if no channel-based routing is set for the channel) is something along the lines of "There is no agent configured to reply in this channel"
2/ we pick the next best assistant as default (gpt4 ?). If also disabled, the next best etc... If every assistant is disabled, then we fallback to "There is no agent configured to reply in this channel"
3/ we continue to reply with `@dust` by default even if disabled

I think 1/ is bad UX (if you ping an app on slack, the goal is never to receive an error message, so there is 0% chance to give the user what they want if we just reply with an error).
I think 3/ is bad as well (if I disable an assistant, I expect my employees/teammates to not be able to interact with it).

I think 2/ is not perfect, but the best option. Ideally we allow configuring the global slack default assistant somewhere.

<img width="1080" alt="Screenshot 2023-10-23 at 14 23 31" src="https://github.com/dust-tt/dust/assets/14199823/86283b9c-9f8c-4a09-96d5-ce16cd139c8d">

**Comment by gabhubert** [comment]
> I am missing the CTA to add a new datasource if there are none yet. I'm still not clear what the behaviour is when @dust is enabled but there are no datasources ?

- Should we redirect to the Connections page with a CtA "Add connections" (I know, this isn't perfect, because we could need a world where they want @dust to work with a static data source)?
- If no data sources or connections exist, imo we should force-disable @dust since it's not able to perform retrievals, i.e. perform it's "core" job

On the Slack UX: I think 2/ is our best direction. We could hardcode after the reply that the reply was given by @assistant because @dust is disabled?

**Comment by fontanierh** [comment]
> Should we redirect to the Connections page with a CtA "Add connections" (I know, this isn't perfect, because we could need a world where they want @dust to work with a static data source)?

sounds good 👍 

> If no data sources or connections exist, imo we should force-disable @dust since it's not able to perform retrievals, i.e. perform it's "core" job

I agree, the experience cannot be good if there is a retrieval step but nothing to retrieve from


> On the Slack UX: I think 2/ is our best direction. We could hardcode after the reply that the reply was given by @Assistant because @dust is disabled?

For customers that don't want to use datasources / RAG at all, it means we'll be adding this text at the end of every response. Are we sure we want this ?

Also, do you have an idea regarding what we want to display on the page (when `@dust` is disabled) to explain the slack bot behaviour ?

**Comment by gabhubert** [comment]
> For customers that don't want to use datasources / RAG at all, it means we'll be adding this text at the end of every response. Are we sure we want this ?

Fair enough, we could just add a callout on the assistant list in Dust (or mvp-do-nothing)

> Also, do you have an idea regarding what we want to display on the page (when @dust is disabled) to explain the slack bot behaviour ?

Maybe just some text in the Availability section  `If @dust is invoked on Slack @$assistant will reply.`

**Comment by fontanierh** [comment]
<img width="1629" alt="Screenshot 2023-10-24 at 15 05 50" src="https://github.com/dust-tt/dust/assets/14199823/1d41760d-6328-40fd-94f3-7d3abfba66d0">


thanks @gabhubert. This is what I came up with wrt the "add connections" CTA. Any idea for the copy ?

**Comment by gabhubert** [comment]
This workspace doesn't currently have any data sources.
- Add connections or data sources to enable @dust
- CtA: + Add connections

**Comment by fontanierh** [comment]
For the slackbot callouts:

![Image](https://github.com/dust-tt/dust/assets/14199823/075f26e1-f197-4db6-9f17-709ec8ea91a9)

![Image](https://github.com/dust-tt/dust/assets/14199823/53198c1e-d57e-4f48-9f5d-dc90b64f5432)

**Comment by Duncid** [comment]
Looking good, would just make sure the tag is not stretched on all the
width (I guess an align left or a flex shrink somewhere)

**Comment by fontanierh** [comment]
The page [I implemented](https://github.com/dust-tt/dust/pull/2228) has several issues:
- we never explain what the Dust assistant is
- we never explain that it needs data sources to work (and why)
- we talk about the slack bot if the assistant is disabled, but it's really not clear for the user. We assume that they know the Dust assistant is default on slack, but most users probably don't know
- Both the Dust assistant and the slackbot are called "dust". Both of them are invoked using "@dust" somewhere. thats very confusing.

**Comment by fontanierh** [comment]
It's hard to find a solution that fixes all of these problem without removing "something".

**Comment by gabhubert** [comment]
per IRL: going to investigate if you could hide a Slack app from your workspace (this could help the case for 2 apps, one for data connection one for Slackbot, which is one possible way forward)

**Comment by fontanierh** [comment]
From my investigation, I don't think its possible. 
@lasryaric as local Slack API expert, do you know if there is a way to do this ?

**Comment by lasryaric** [comment]
@gabhubert @fontanierh I am not sure what you mean by "hide a Slack app from your workspace".
You would like to Dust app to be installed on a Slack workspace but be hidden?

I looked at the API and did not find any way to do that. It also makes sense to me: I would not trust Slack much if they were hiding apps away from my view.

**Comment by fontanierh** [comment]
The idea was to have 2 slack apps:
- the "bot" app, that would be visible / pingable on Slack, and that would answer users
- the "sync" app, that would be "hidden" / unpingable and that would only be used to synchronize data.
I haven't found a way to do this either

**Comment by fontanierh** [comment]
As per IRL, the solution we are going with:
- we remove the slack-bot-related "warning chips"
- we make GPT-4 respond on slack when Dust assistant is disabled
- we remove ability to disable the GPT-4 assistant (like helper)

**Comment by lasryaric** [comment]
Thanks for clarifying @fontanierh and sounds good to me for the plan.
