### ISSUE TITLE
[Doom] Search in data sources files

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2197]
From: https://github.com/dust-tt/decisions/issues/105

Replace semantic search in data sources by fuzzy search on files

<img width="643" alt="image" src="https://github.com/dust-tt/decisions/assets/4435185/0f88e166-f60c-4886-afd3-7cb6c3dd2e5a">

**Comment by fontanierh** [comment]
Starting to think about this a bit -- do we want fuzzy search on file titles only ? Or also the actual content ?

**Comment by spolu** [comment]
file names only

**Comment by spolu** [comment]
I think we can focus on managed data sources for now since this screen displays more than just the "documents" (google drive directories, slack channels not threads).

**Comment by spolu** [comment]
I think the effort / value trade-off is a bit off here.

Proposal: closing this task for now cc @Duncid @gabhubert 

Will do so unless I hear otherwise by noon

**Comment by gabhubert** [comment]
I think that's fine given focus especially if it's tougher than planned.

**Comment by spolu** [comment]
Not necessarily more than planned. It's just a fair amount of work (1-2 days) and I'm not sure this is our top priority.

**Comment by Duncid** [comment]
Low confidence here but I think it might actually be quite important.

**Comment by Duncid** [comment]
Being unable to retrieve a file by name is very reassuring for an admin, it will most definetly help finding a problem of sync, it also has very practical application to point a prompt to a specific file

**Comment by Duncid** [comment]
IMO could be used to enhance retrieval as well (combine semantic and more basic search by name).

**Comment by fontanierh** [comment]
> IMO could be used to enhance retrieval as well (combine semantic and more basic search by name).

That's kind of different topic, but agreed that some kind of hybrid search would be useful.

**Comment by spolu** [comment]
Yes search to support the product will be super useful I agree. But that's not within the scope of that issue.

And we need to evaluate the value it provides independently.

The admin can search the hierarchy to find their file. It's obviously harder but it's also less error-prone. If the search is not fuzzy enough the admin might be led to thinnk that something is not synced while it is...

**Comment by spolu** [comment]
Will close for now. To be re-visited at a later stage. Other climbs are higher priority.
