### ISSUE TITLE
[Doom] Aggregated Slack channels management

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2198]
From: https://github.com/dust-tt/decisions/issues/105

Move from making the bot join and then filtering in edit permission to a world where we can make the bot join from Dust by selecting the channels we want aggregated out of all the public channels of the workspace.

- After activation, allow admins to select any channel from the channel list.
- Selected channels will be vectorised, no need for further actions.
- `@dust` can be called from any channel it was invited to.

Selecting a channel will make the bot join that channel and will add the channel to the list of channels we aggregate. Deselecting the channel has no action on the bot, and aggregation of that channel is stopped

**Comment by spolu** [comment]
Yes exactly. This will only allow the bot to respond in that channel :+1:

**Comment by lasryaric** [comment]
We'll need to ask our current Slack users to re-authorize for this to work.

**Comment by spolu** [comment]
Yep

**Comment by lasryaric** [comment]
The connect Slack flow had many issues, so I am fixing them all until we get a good flow from A-Z.
I will send a video at the end.

**Comment by lasryaric** [comment]
Shipped!
