### ISSUE TITLE
[Doom] Better debugging of data sources

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2199]
Initla proposal from: https://github.com/dust-tt/decisions/issues/105 was:

<img width="1502" alt="image" src="https://github.com/dust-tt/decisions/assets/4435185/e31b9eef-6acc-4dae-8e11-e57c7c0903e9">

- If a file is in error, the status displays it. If a file is in error under on a sub-node, we display in the status in orange.
- We give access to source URL and dust interpretation of it (in a side modal)

--

There is no concept of error of a file but we can surely give the last update on some platforms. We definitely want to enable access to the source URL + view of the content of the file as seen by dust

**Comment by spolu** [comment]
We won't be able to have errors on sub-file for sure

**Comment by fontanierh** [comment]
I don't understand the "error" thing. Yes we can give the last update, but there are to my knowledge 0 cases where we can display an error ?
Do we want to display the last upsert time for the doc ? likely not in orange/red thoughm right ?
