### ISSUE TITLE
[Doom] Management of Connected Data sources

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2200]
From: https://github.com/dust-tt/decisions/issues/105

See [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=2389%3A13138&mode=design&t=jNPh15R04TKGjgcX-1):

<img width="1414" alt="image" src="https://github.com/dust-tt/decisions/assets/4435185/c1787bd2-17f1-40d1-ade1-57bde1075bbc">

Changes:
- Clearly state that the display is the display of the syncronized data and clarify CTAs

**Comment by gabhubert** [comment]
With connected data sources now "connections", adapt header titles and CtAs:

header sections
- "Manage X" still works
- "Select {folders || channels || etc}" is more adapted
