### ISSUE TITLE
[Doom] Static Data Sources improvements

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2201]
From: https://github.com/dust-tt/decisions/issues/105

### Folder metaphore

<img width="648" alt="image" src="https://github.com/dust-tt/decisions/assets/4435185/df93afee-986f-4ebe-a2fb-b242e8389dea">

Clarify the notion of a bucket of documents.

### Document management

<img width="1805" alt="image" src="https://github.com/dust-tt/decisions/assets/4435185/7d2c248a-3b4d-4c8f-8d76-046c80a89b21">

Proposed changes:
- We create a field for Document title
- We regroup tags and document ID behind a "Developer option" setting button (opens a side modal)

**Comment by gabhubert** [comment]
I see the point @Duncid is making, but I think adding a concept (folder) is a lot no? I also think keeping `data source` allows us to minimise copy changes in the section of custom assistant where data sources are mentioned quite visibly.

**Comment by fontanierh** [comment]
IMO having "folders" kind of implies that you can move a doc from a folder to another
