### ISSUE TITLE
[Structured Data] [Step 0] implement `get_schema_from_connection_string`

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#2206]
To support remote DBs, we need a way to retrieve the schema from a SQL database connection string. 

The interface would look something like this:

`fn get_schema_from_connection_string(conn_str: String, tables: Vec<String>) -> Map<String, TableSchema>;`

where `tables` is a list of table names. The return value should be a map where keys are table names and values are the schema for that table.

###

**Comment by spolu** [comment]
Note: didn't put it in Caloris as scope of Caloris excludes remote databases

**Comment by spolu** [comment]
Closing for now, this will be reframed when the time comes
