### ISSUE TITLE
[Structured Data] [Step 0] implement `query_remote_database`

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#2207]
To support remote DBs, we need a way to execute a SQL query string on a database using a connection string.

The interface would look something like this:

`fn query_remote_database(conn_str: String, query: String) -> Vec<Row>;`

**Comment by fontanierh** [comment]
Should this one also be excluded from Caloris @spolu  ?

**Comment by spolu** [comment]
Yes ideed!

**Comment by spolu** [comment]
title updated moved back to olympus :+1:

**Comment by spolu** [comment]
Closing tfor now this will be reframed when the time comes
