### ISSUE TITLE
[Caloris] [Structured Data] [Step 1] `core` data model

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#2209]
Some of it is dependent on what we end up using for querying non-remote databases.

We’ll need tables for the `databases` ,`tables` and `rows`.

A first draft of it is available here: [`core` data model](https://www.notion.so/dust-tt/Design-Doc-Structured-Sources-727e513cbbf44ad3b9742819d8b3f82f)

**Comment by philipperolet** [comment]
It seems the doc is empty? is that expected or is it the wrong link?

**Comment by fontanierh** [comment]
Indeed @philipperolet -- updated
