### ISSUE TITLE
Is there a good way to collaborate on a dust project when using the front end?

### ISSUE THREAD

**Issue by clayoneil** [dust-tt/dust#230]
When using the front end, all of the code blocks (I believe) are saved in the sqllite database. This prevents us having a central code repo with all of our code blocks. The only way we have been able to collaborate is by copy and pasting the code from code blocks. Is there a solution for this?

**Comment by spolu** [comment]
Hi! We're working on introducing the notion of Workspace for teams to collaborate on apps and datasources together.

ETA 1-2 weeks.

**Comment by spolu** [comment]
We are now ready to roll-out shared team workspaces. Feel free to ping us at team@dust.tt to get into the preview of that feature :+1:

**Comment by spolu** [comment]
(if you're using the hosted version, I can help you set that up of course)
