### ISSUE TITLE
Improve copy on Slack<>Assistant mapping

### ISSUE THREAD

**Issue by gabhubert** [dust-tt/dust#2319]

**Comment by gabhubert** [comment]
Currently: 

## Slack Integration
You can set this assistant as the default assistant on a selection of your Slack workspace channels. @Timmy will answer by default when the @Dust Slack bot is mentioned in these channels.


Edit to: 

## Set as default assistant in a Slack channel
Have @{name} reply by default when @dust is mentioned in the following Slack workspace channels:

**Comment by spolu** [comment]
Superseded by Meru
