### ISSUE TITLE
[Caloris] PRIO Frame Structured Data from Connected Data Source UX

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2326]
What is the product experience to query structured data form connected data source
- Selected epxlicitley? Different mode for assistant? Automatic?

**Comment by spolu** [comment]
@fontanierh I presume Database are at the same level of Documents under Data Source right?

Assuming step 0 is access through a Dust app, what's your current plan for pointing the DatabaseSchema and Database blocks to the right databases? 

We'll have to select a DataSource of course but do we also select the Databases explicitly?

**Comment by fontanierh** [comment]
@spolu  I think at first yes ? You have the database IDs as input to the dust app, just like for data sources.

And the next step would be to have special "documents" pointing to databases inside of data sources so we can "match" them using semantic search. Am I understanding your question correctly ?

**Comment by spolu** [comment]
So the input is DataSource(s) and DatabaseId(s) right? or more like `[]{ dataSource, databaseId}`

**Comment by spolu** [comment]
Nice UI challenge :)

**Comment by fontanierh** [comment]
Input of what? The retrieval action?

**Comment by spolu** [comment]
I meant config to the DatabaseSchema and Database blocks to be precise?

**Comment by fontanierh** [comment]
closing this
