### ISSUE TITLE
[Caloris] Frame taking comments in GDrive and Notion

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2328]

**Comment by fontanierh** [comment]
some of the challenges for Notion will be the rate-limiting (notion has very low rate limit and we already hit it all the time) and general unstability of the API.

**Comment by spolu** [comment]
Indeed. Also do you know if documents pop up in search when they are commented?

(just considering the technical constraints here since I think there are also orthogonal product constraints on whether this is something we want or not)

**Comment by fontanierh** [comment]
No idea. The docs don't mention this, and I would not be surprised if it wasn't the case. 
I'll do a test and report here 👍

**Comment by spolu** [comment]
@gabhubert @Yutcam do people ask for comment?

Closing for now, but happy to reopen if we feel it's a priority

**Comment by Yutcam** [comment]
The only comments users mentioned to me were comments of a Dust convo to flag some relevant or irrelevant content. But there are no records of requests to index Gdrive or Notion comments on my side @spolu

**Comment by gabhubert** [comment]
- agree no rush.
- re-opening to close with a label that might help future us?
