### ISSUE TITLE
[Doom] Better guidance for Admins and Builders

### ISSUE THREAD

**Issue by Duncid** [dust-tt/dust#2372]
Framing:
https://github.com/dust-tt/decisions/issues/102#issuecomment-1792567650

# Making
## Guiding in Assistant Builder

Notes:
- Rename the Action section "Data source and Action"
- Use the new ContentMessage component from Sparkle

![image](https://github.com/dust-tt/decisions/assets/4435185/aa537647-ed2c-4463-aa38-98dc25f284fe)

### 2 cases
Admin & Builders.
Figma available here: https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=860%3A15637&mode=design&t=DjIXRmA3Jrd66WTk-1

<img width="620" alt="image" src="https://github.com/dust-tt/decisions/assets/4435185/9767fb83-6c34-440d-b8c8-98321d9ff69a">

## Guiding in Connections
For Builders:

![image](https://github.com/dust-tt/decisions/assets/4435185/8d9cc7f5-5eb2-476c-9bcd-453a8034ea32)

# Question

@spolu What climb can this be a part of? Where should I add a task for it?

**Comment by spolu** [comment]
ContentMesssage does not allow styling of the message nor newlines. @Duncid will tweak content mesage to accept a children component instead of a message
