### ISSUE TITLE
How to debug a code block or add console.log support

### ISSUE THREAD

**Issue by okomarov** [dust-tt/dust#244]
I am creating a scoring function which compares the LLM's model output, which is a JSON, to an expected object saved in a field of an `input` block:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/3731173/232328506-b606db4e-d6c9-4f1a-a755-a6ee008e892a.png">

The score is off which most likely means the scoring function is failing somehow. If I visually inspect the two objects, `expected` and `obtained` then I can't really see why the score is what it is. Any way to have console.logs would help greatly.

**Comment by spolu** [comment]
We're planning to add support for console.log outputs on the code blocks :+1: 

Probably before end of month :+1:  Will update there.
