### ISSUE TITLE
[Caloris] frame support for pdf files in Gdrive

### ISSUE THREAD

**Issue by gabhubert** [dust-tt/dust#2452]

**Comment by gabhubert** [comment]
We initially had a lot of noise from pdf files, but many users now asking to have it or at least opt in. To be framed.

**Comment by spolu** [comment]
As discussed on slack:

- Should be gated to begin. (I proposed 3 settings in slack but I think it does not make sense)
- Let's create shared infrastructure for configuring connections so that we can rely on the same endpoint for this and enabling the Slack bot.

**Comment by spolu** [comment]
We'll have a setting in poke to activate it. And we can slow roll it. We need more work on qdrant IMHO before enabling Alan again.

**Comment by gabhubert** [comment]
ok so we have some technical constraints: 
- can't infer at ingestion
- need some Qdrant work before opening the floodgates e.g. on Alan

and some product constraints: 
- want to keep it simple
-  want to support the cases where users expect it

## Proposal
### Implementation v1
- we enable it behind a flag at the connection level (GDrive)
- flag is added to Poké for non-eng
- we set to false for all for now
- we update the comment in limitations to: "Google Drive: Dust doesn't take into account files with more than 750Kb of extracted text. By default, Dust doesn't take into account .pdf files. Email us at team@dust.tt to activate this". 

### Testing and v2
- obviously, we want to delight users
- so we'd love to "activate by default" iff "pdf by default increases the value of dust"
- the test plan for that isn't trivial, but we could do the following: 
  - log a Gdrive connection
  - we email to ask if pdf could help
  - we tarck and decide

ok for you @Duncid @spolu @lasryaric ?

**Comment by spolu** [comment]
LGTM

**Comment by Duncid** [comment]
Happy to go any direction here (no strong feeling, I trust the team on the risk of activating PDFs for all).

**Comment by lasryaric** [comment]
Sounds good to me. Thanks.

**Comment by gabhubert** [comment]
Bombs away! ⚡

**Comment by lasryaric** [comment]
💣 🔢 🔄

**Comment by gabhubert** [comment]
@lasryaric what's the status here? Is eng blocked on anything?

**Comment by lasryaric** [comment]
@gabhubert I have listed in my goals to start working on it today.

Following last week incident we decided to work on a "production checks" framework.
More details here:
https://dust4ai.slack.com/archives/C050A0S2Z7F/p1699625143185819

Framing here:
https://github.com/dust-tt/tasks/issues/234

I will update later today 👍

**Comment by lasryaric** [comment]
Started working on Gdrive PDF v1 now. (just sent my PR for production checks).

**Comment by gabhubert** [comment]
## Decision
### Implementation v1
- we enable it behind a flag at the connection level (GDrive)
- flag is added to Poké for non-eng
- we set to false for all for now
- we update the comment in limitations to: "Google Drive: Dust doesn't take into account files with more than 750Kb of extracted text. By default, Dust doesn't take into account .pdf files. Email us at [team@dust.tt](mailto:team@dust.tt) to include .pdf files.".

### Testing and v2
- obviously, we want to delight users
- so we'd love to "activate by default" iff "pdf by default increases the value of dust"
- the test plan for that isn't trivial, but we could do the following:
  - log a Gdrive connection
  - we email to ask if pdf could help
  - we track and decide
