### ISSUE TITLE
[Caloris2] [Chunking v2] Move Notion to chunking v2

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2458]
Frame the change for Notion
Implement
New insertion will benefit
No full resync

**Comment by spolu** [comment]
We likely ant something rather simple here, just create deepening contents on h1/h2 + top-level document title and tags as top-level prefix

**Comment by philipperolet** [comment]
Framing, in the spirit of the above suggestion:
- similarly to github, use structure up to and including h2 + limit prefix size to 128 (probably mutualize the logic between gh & notion in data_sources.ts lib)
- each block in the page becomes a section with no prefix, except h1/h2 blocks that become section with a prefix and no content (blocks below become of course nested in those sections)
- add the following tags: author,  creation date, last edit date, last editor, and page properties that fit the remaining space of a 128 char prefix. Add them as a separate prefix from the title prefix (so the title can be long, and we can still have a few tags). 

AFAIU, for notion, there is a single point of upsert leading to chunking, which is at the end of the `renderAndUpsertPageFromCache` activity. The PR to be opened will change the page rendering logic right above this upsertion to match what's described above.

@spolu @fontanierh good for you?

**Comment by spolu** [comment]
@philipperolet LGTM

**Comment by philipperolet** [comment]
Reopened following various issues in notion and chunking

**Comment by philipperolet** [comment]
Should be done this time
