### ISSUE TITLE
[Caloris2] [Chunking v2] Move GDrive to chunking v2

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2459]
Frame the change for GDrive
Implement
New insertion will benefit
No full resync

**Comment by spolu** [comment]
We likely want something very simple here, probably what already exists but to be checked (simply title and last updated maybe author as top-level prefix)

**Comment by philipperolet** [comment]
After quick overview:
- author / createdAt / etc. => already done by recent refactor using `renderDocTitleAndContent`
- user labels
- file details (e.g. size)
- Path (incl. team drive)

File details => not worth it IMHO
Labels => probably useful when used but never heard of anybody using it
Path => this can actually be useful for semantic search (and true for Notion too); consumes another 192 chars but probably worth it, path structure is often used with strong meaning

Will explore adding path & labels

**Comment by spolu** [comment]
Not completely convinced by path. I suggest we close and move on for now :+1:
