### ISSUE TITLE
[Build trust] Get Slack app verified

### ISSUE THREAD

**Issue by gabhubert** [dust-tt/dust#2475]

**Comment by gabhubert** [comment]
Process: https://api.slack.com/start/distributing/app-review-guide

**Comment by gabhubert** [comment]
2-3 weeks for feedback.

**Comment by philipperolet** [comment]
Hey 👋
Since it's been 6 months without activity, moving out of board 🙇  When you feel it's time to start working on it, feel free to update the issue with the rationale, and move it back in for discussion in Eng runner 👍

@lasryaric is the app verified now? if yes maybe we can actually close?

**Comment by lasryaric** [comment]
It's not verified but the reason we thought we needed it to get verified was actually not correct so we can just close.
