### ISSUE TITLE
Share app with team

### ISSUE THREAD

**Issue by okomarov** [dust-tt/dust#248]
Is there a way to share an app within a team? 

We're iterating on a prompt and its useful to let non-technical people work on the same pipeline which leverages the input tests. 

Is the current workaround ~to signup with username and password and share credentials~, is there one?

**Comment by spolu** [comment]
We're working on a concept of team workspace as we speak. Should be ready in beta by next week.

Feel free to ping team@dust.tt to get updated as soon as it's ready :+1:

**Comment by okomarov** [comment]
Awesome thanks!

All my team members have a google sign in. As a side question, would it be possible to change email to ***@***.*** ***@***.***> which is my work google mail so that I can also have a personal dust account for ***@***.*** No worries if too much trouble, not a priority.

**Comment by spolu** [comment]
(note we're on the public github issue)

Your current workspace user is tied to your github account. You can easily re-create a personal account with a personal Gmail address :+1:
