### ISSUE TITLE
[Doom - Downgrade] Create banner and display it for users with an active but cancelled subscription

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#2482]
Related [design doc](https://www.notion.so/dust-tt/Design-doc-Downgrading-from-paid-plans-to-free-plans-a79e649619f341df90e266e5df4a3115?pvs=4)

Tasks:
(to detect ending a free trial)
- Update stripe webhook handler on event `customer.subscription.updated` if there is a cancellation
    - the stripe object returns a cancelledAt, update Subscription object to set endDate (but keep it to active)
        - This allows  `front` to be aware that a user has cancelled the subscription but is still active (currently not the case)
    - Send an email to admins with a TLDR of what will happen + link to the FAQ
- Update stripe webhook handler on event `customer.subscription.updated` if there is a renewal after cancellation but before the end of billing
    - update Subscription object to reset endDate (but keep it to active)

- Create the banner with @Duncid's help

**Comment by Duncid** [comment]
We could re-use this:
<img width="747" alt="image" src="https://github.com/dust-tt/dust/assets/4435185/f5731edc-7ef7-4499-b478-e6454d689edb">

Simply add a yellow chip saying "Subscription cancelled"

**Comment by philipperolet** [comment]
This could be a good idea. But would the chip be enough since it cannot convey info?
The role the banner was to enable a little bit of text to warn of the dire consequences, e.g.
```
"Your subscription will end on Nov 13. All connections will be deleted and all members will be revoked except for the admin. Find all the relevant info [here](LINK TO DOWNGRADE FAQ)" 
```
Since we also send emails to the admin, we don't absolutely have to do this but it could be better (less fallback if a user forgets something, and/or maybe they realize they shouldn't actually cancel, it's easier to keep the subscription active for now and just remove a few users, etc.

**Comment by philipperolet** [comment]
The banner would BTW be reused in other situations => we had one last week where we rolled a custom banner to inform of the OpenAI incident

**Comment by philipperolet** [comment]
@Duncid apparently the banner is already designed? 🙂
