### ISSUE TITLE
[Doom - Downgrade] Prevent using documents and datasources after downgrade if they are over the free plan limits

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#2484]
Related [design doc](https://www.notion.so/dust-tt/Design-doc-Downgrading-from-paid-plans-to-free-plans-a79e649619f341df90e266e5df4a3115?pvs=4)

Tasks:
- Add logic that if a datasource has more docs than the limits, it’s not usable by api or custom assistants (incl. error message for api and notification for CAs)
- Add logic that if there are more datasources than the limits, static datasources are not usable by api or CAs (incl. err msgs / notification)

**Comment by philipperolet** [comment]
This turns out to require tradeoffs. Below, framing

**Comment by philipperolet** [comment]
## Datasource limits for users who downgraded: the case where the user had more datasources (or documents) than the new downgraded plan allows

Enforcing the limit = err on the retrieval, and alert the user that they have to remove datasources / documents to get it to work again

### Context
A. Currently, this case only affects users who canceled their subscription, and switched back to a free plan
B. in the future, it might affect users who switch from a plan to another where limits change
C. This is **only** about the case where there is a decrease in the user allowed limits. Other cases not discussed here: 
  - Enforcing limits when the user hasn't yet reached them, and tries to add datasources / documents from the app => already handled;
  - The case in which they try to add datasources using the API => PR incoming;

### Solutions
Performing counts on the datasources and documents might be costly. We have 2 options:
- solve only for case A (present) => run the count directly in runRetrieval
  - run the counts only on free plan for rag agents based on static DS => this can then be done live during the RAG action, since it concerns few users who have churned anyways and probably don't evem have messages left in their free plan.

- solve for case B (possible future in which people change their max DS/documents limit)=> then we need to find solutions
  - ability to mark datasources as unavailable, or limits as reached, somewhere easily available by api (but needs to be synced e.g. the user can remove datasources)
  - have dedicated cached queries for counts on datasources / documents
  - other ideas?

### Conclusion
- I favor solution A, I can ship in ~15' if agreed on (so I'm biased, thus checking for agreement), PR is already half there. 
- I think the possible future is not definite, and dealing with those hypothetical future cases is not a priority--as long as we can clearly know if and when we hit them in the future so they don't take us by surprise
- => I will throw a loud exception, with a link to this issue, if the code ends up trying to enforce a datasource limit for a non-free plan.

@spolu r? Or maybe there is a fast solution I missed? 
@aric mentionning you too since you were on the PR

**Comment by philipperolet** [comment]
Following IRL discussion with @spolu & @lasryaric, current situtation does not warrant our time to handle: solution AA => we let the user run messages on agents that have static datasources. Very edge-casy anyways

However, avoiding keeping large static datasources for indefinite periods of time is important; therefore:
- for now: ops email when user downgrades will be updated to check there is no large static datasource, and otherwise to contact the user and tell them they will be removed in 7 days
- future: we will have a retention policy of 30 days for free users => untouched datasources will be scrapped after a month

**Comment by philipperolet** [comment]
A runbook will be created + the downgrade faq will be updated to reflect that

**Comment by spolu** [comment]
Thank you!
