### ISSUE TITLE
[Caloris] [Structured Data] Add support for numeric booleans and enums

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#2501]
When inferring a schema from data, we could:
- infer that a column is an enum if it is a string column and there are less than N different values
- infer that a column is a (numeric) boolean if the column is number and there are only 0s and 1s in it. This is particularly important as SQLite doesn't have a bool type and instead relies on REAL 0 or 1.

The information about the enum / boolean could be provided to the model as a "comment" on the schema

**Comment by spolu** [comment]
We obviously want to stick with Sqlite language to not confuse the model and make it clear that it should target sqlite. So this should be generated comments in the schema presented to the model.
