### ISSUE TITLE
[Caloris] [Structured Data] Create the "Query Database" assistant action

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#2504]
Currently, database can be queries via custom assistant by creating a bespoke a Dust app. We want to make the process a lot easier by having a "Query Database" action that we can select from the custom assistant creation page

**Comment by fontanierh** [comment]
We probably want to create a custom assistant action as well

**Comment by PopDaph** [comment]
Shipped: https://dust4ai.slack.com/archives/C05BUSJQP5W/p1702892740920059
