### ISSUE TITLE
[Calories] [Better Data Sources] Support for PDF V1

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#2506]
Framing is here:
https://github.com/dust-tt/dust/issues/2452#event-10942049687

**Comment by lasryaric** [comment]
Implementation is starting now.
cc @gabhubert you can track progress here.

**Comment by gabhubert** [comment]
Thanks for the heads up!

**Comment by lasryaric** [comment]
Test suite to execute (on my dev env):

- [ ] Synchronize a PDF
- [ ] Trigger a RAG with generation
- [ ] Update the PDF on Gdrive and observe incremental sync working
- [ ] Delete the PDF on Gdrive and kick start a full sync - observe garbage collection

**Comment by lasryaric** [comment]
Tests done.
PR here in review:

https://github.com/dust-tt/dust/pull/2542
