### ISSUE TITLE
Improve copy when no data sources

### ISSUE THREAD

**Issue by gabhubert** [dust-tt/dust#2511]
Currently:
![Image](https://github.com/dust-tt/dust/assets/998689/67f1c0ff-9a76-4fe3-9e63-708a2e383a99)

Proposal:

### No data sources or connections
Assistants can retrieve information from company knowledge. Add [data sources](link) (files you upload) or [connections](link) (Slack, Notion, etc...) to the workspace to enable this.

**Comment by spolu** [comment]
Clicking not implemented for 2 reasons:
- Would potentially loose current work
- Would teleport user instead of teaching them to find it on their own.

The first reason is a pretty strong one against doing it

**Comment by gabhubert** [comment]
yeah agreed, hadn't thought that one through. Still think there's a possible pass on the copy to shorten a bit but this isn't high-pri. Closing.
