### ISSUE TITLE
[Production check] Slack Garbage collector

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#2514]

**Comment by spolu** [comment]
What's the status here?

**Comment by spolu** [comment]
friendly bump what's the status here @lasryaric ?

**Comment by lasryaric** [comment]
Lost track of that in the Olympus backlog.
We never discussed it again really. I suppose the idea was to the same thing as the Gdrive production check, but it's been opened for a very long time and we never felt the need for it again, so I suggest we close this for now.
