### ISSUE TITLE
[Caloris2] [Better data sources] Use the new configuration system for the Slack bot

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#2543]

**Comment by spolu** [comment]
@lasryaric what's the status here?

Moving to caloris 2 but maybe should be closed?

**Comment by lasryaric** [comment]
Working on it now.

**Comment by spolu** [comment]
Assigning to you and moving to In progress

**Comment by lasryaric** [comment]
This was done [here](https://github.com/dust-tt/dust/pull/3133). Closing
