### ISSUE TITLE
[Caloris] [Better data source] Frame document upload in conversation

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#2548]
# The need

The need for file upload as Content Fragment in a conversation came up during the Qonto workshop, which increases the priority of this feature.

# Framing

We need to decide how far we want to go for the V1 of this feature.

## Simple version:
- There is a file attachement icon in the input bar, clicking on it triggers the OS file picker.
- The user select a file.
- The file is uploaded as a Content Fragment.
- The user can now send a message

Time to ship: ~2 hours worth of work.

## Elaborated version:
- There is a file attachement icon in the input bar, clicking on it triggers the OS file picker.
- The user select a file.
- The file is listed as an attached file with the option to delete it, along with its title.
- Uploading the file creates a content fragment:

Today content Fragments are not attached to a user nor a UserMessage and are just part of the conversation like UserMessage and AgentMesasge are.
Displaying the content fragment attached to the UserMessage requires some architecture change of the conversation, which might be a bit involving.
So we need to decide what we want to do for a V1 of this feature:
- Display the file as a content fragment as is, not attached to the user message.
- Refactor the content fragment to somehow link it to a user message.
- Something in between: keep it as is but add a `ContentFragment.userId` property to show who uploaded it.

Time to ship highly depends on the decisions we take around file uploading and Content Fragment refactoring (or not).

Input welcome. Thanks.

**Comment by lasryaric** [comment]
cc @Duncid @gabhubert @spolu

**Comment by lasryaric** [comment]
and @dust-tt/product-team

**Comment by fontanierh** [comment]
Maybe it is also worth thinking about what happens when the file is too big

**Comment by lasryaric** [comment]
Agree to start simple @spolu .

**Comment by lasryaric** [comment]
Making progress on the core functionality for now, using content fragment as is.
This work is needed regardless of what we decide here.

**Comment by lasryaric** [comment]
Prototype is working, but still some UI work to do (not aligned with the Figma yet).
https://dust4ai.slack.com/archives/C050A0S2Z7F/p1700002134986039

**Comment by lasryaric** [comment]
For v1 or v2, we could have a data source per workspace dedicated to files upload and RAG from here by using the datasource id and file id. We would need to hide this data source though, to be discussed later.

**Comment by gabhubert** [comment]
Thanks for the push on core functionality @lasryaric! 

## Thoughts on v1
I think your video on Slack is almost there
need-to-haves:
- upload only (vs being able to search in your data sources) --> we have it
- showing there is a doc attached to the conversation --> we have it (let's indeed sparklify)
very-nice-to-haves:
- giving the user info on limitations (file type, file size) upon hover on the clip to avoid disappointment + enforcing
nice-to-haves:
- showing who uploaded the file in the conversation indeed (it seems it would be logical to just display as a user message from the uploader, I agree)
questions for Aric
- what are the limitations on file type? I think we should pdf, txt, initially.
- no ability to view extracted text in v1, correct? that's what I presume you're talking about when mentioning having a hiddne data source to host the file.


## Thoughts on v2
- _a lot more thinking and work_ needed here especially on adding a file from a connection to a conversation (vs RAG) and on adding a file to an assistant vs a conversation. We can open separately.

**Comment by spolu** [comment]
> For v1 or v2, we could have a data source per workspace dedicated to files upload and RAG from here by using the datasource id and file id. We would need to hide this data source though, to be discussed later.

I might be missing something but I don't understand your proposal?

**Comment by gabhubert** [comment]
I belieeeeeve he means that to display the extracted text, we'd need the infra that come with data sources?

**Comment by lasryaric** [comment]
> I might be missing something but I don't understand your proposal?

The first version of file upload as content fragment works when the full file can fit in the context window of the model, but when it's not the case anymore, we will want to chunk the file, embed the chunks, search, and bring chunks back to the model.
For that, we already have data sources, so if we could send a user message with a file and have the backend automatically put it into a data source, then search on this data source by filtering on the file id, we could solve the "big file" problem pretty easily.

**Comment by spolu** [comment]
This would require having shared collections in qdrant. the data source would not be "hidden" this would be a core data source backing another product surface

**Comment by lasryaric** [comment]
I meant one data source per workspace.

**Comment by lasryaric** [comment]
About the question of sending the file to the conversation right after the user selected it ([@spolu on Slack](https://dust4ai.slack.com/archives/C050A0S2Z7F/p1700035219387339?thread_ts=1700002134.986039&cid=C050A0S2Z7F)) vs when the user sends the message, I vote for sending it when the user sends the message, as long as the select file button stays in the input bar. Sending it right away would be confusing to the user otherwise and won't offer a way to validate / correct it a file was selected by mistake.

Regarding the success / error state of the file selection action, I added an error handling around it (see screenshot below).
If there is no error at file selection time, then the file is turned into text.
If something goes wrong when posting the message, another error would be displayed.

![Image](https://github.com/dust-tt/dust/assets/358965/e674ed38-ac0c-4066-aa65-6e5663453f7a)

**Comment by lasryaric** [comment]
(Error copy to be edited)

**Comment by gabhubert** [comment]
"extracting text from PDF"seems more correct?

**Comment by lasryaric** [comment]
As per IRL:
Our appetite for this V1 is shipping by today or tomorrow a first version with a way of measuring how many files are being uploaded on metabase.

We'll with v1 plan expose above by @gabhubert while making sure the UI/UX feels robust.

**Comment by lasryaric** [comment]
New UI, LMK what you think:



![Image](https://github.com/dust-tt/dust/assets/358965/c41f455c-8cfd-4467-b4c5-f5660f86ad6c)
![Image](https://github.com/dust-tt/dust/assets/358965/e5a12889-a82d-40ac-83e8-232def03bd4b)

**Comment by Duncid** [comment]
Propre :)

**Comment by gabhubert** [comment]
Does chip below text look more natural (reminds me more of attachments in
email)?

**Comment by lasryaric** [comment]
If you give me the css classes I can try it 😭

**Comment by gabhubert** [comment]
@duncid thoughts on this vs quality standards (i'd have considered more
padding bove chip then at least, if we don't flip chip to below text? IANAD)

**Comment by lasryaric** [comment]
This is actually implementing what @Duncid recommended but he just ended up not posting it on this thread after our IRL conversation (he was about to post it though).

**Comment by lasryaric** [comment]
Figma here:
https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?node-id=860%3A18417&mode=dev

**Comment by Duncid** [comment]
<img width="660" alt="image" src="https://github.com/dust-tt/dust/assets/4435185/41101a62-eeea-47df-9dda-19845529ca2d">

**Comment by lasryaric** [comment]
Here is what it looks like now.
@spolu said that displaying the avatar of the user twice in a row might not be the best idea, WDYT?



![Image](https://github.com/dust-tt/dust/assets/358965/15f45de8-475e-4596-bd7a-5dc8dbac2cdd)

**Comment by lasryaric** [comment]
With the padding top in the attached file in the input bar as suggested by @gabhubert .


![Image](https://github.com/dust-tt/dust/assets/358965/00ee2c55-45a1-4d0f-8d1b-2d4227ff865b)

**Comment by lasryaric** [comment]
(Updated the screenshot above assuming nobody saw it yet).

**Comment by lasryaric** [comment]
And voila a video demo of the file attachment UX flow end to end.
Let me know what you think, I would like to push a PR ASAP:
https://www.loom.com/share/ae25da820de54b92ae37c6a9af9aef3d

**Comment by gabhubert** [comment]
LGTM

**Comment by Duncid** [comment]
LGTM !
Like the avatar on top right.
(Are you using the Avatar component?)

**Comment by lasryaric** [comment]
> Like the avatar on top right.

Cool, but it's on the top left, right? 

Yes, I am using the avatar component.

**Comment by lasryaric** [comment]
Shipped! Closing this issue.
