### ISSUE TITLE
Dust panics and the UI hangs when the few shot count is larger than the number of few shot pieces of data

### ISSUE THREAD

**Issue by aickin** [dust-tt/dust#26]
I made a Dust app with the new `search` block which pulls news headlines from Google and feeds them in as few shot examples to GPT3. When I used a topic that had no stories, though, the UI hung. Looking at Dust API's console, it looked like it hit an index out of bounds error and panicked, and the UI is left spinning. IMO, Dust should probably just read *up to* few_shot_count and not panic if there aren't enough elements in the array.

**Comment by spolu** [comment]
uh never hit this one. will investigate!

**Comment by spolu** [comment]
zero might be corner case

**Comment by spolu** [comment]
can you confirm it only happens with 0?
