### ISSUE TITLE
[Ahuna] Assistant retrieval optimized for visibility

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#2644]
- Update getAssistants to take in a `view` argument
    - `browse` view:
    - `list` view
    - `conversation` view: `list` view + agents in the conversation (takes in a conversation sId)
- Update all code paths to use the new `view` argument
    - useAgentConfiguration refs and api/w/agent_configuration calls

Related [framing](https://github.com/dust-tt/decisions/issues/111#top) and [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=2677-10559&mode=design&t=B7nphNLIUPBjCls5-0)

Prototypes of what's going to be done are [here for members](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?page-id=2677%3A10559&type=design&node-id=2677-10560&viewport=470%2C31%2C0.25&t=L0qImC25TEHwijGx-1&scaling=min-zoom&starting-point-node-id=2677%3A10560) and [here for admins](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?page-id=2677%3A10559&type=design&node-id=2929-29336&viewport=470%2C31%2C0.25&t=L0qImC25TEHwijGx-1&scaling=min-zoom&starting-point-node-id=2929%3A29336&show-proto-sidebar=1)

**Comment by philipperolet** [comment]
browse = all non-private assistants. At first non-paginated
list = all assistants on my list

**Comment by philipperolet** [comment]
New views after some thoughts:
- list: all agents in the user's list
- conversation: all agents in the user's list + agents in the current
  conversation (requries a conversation sId)
- public: all agents except private ones
- discover: public + private to the user
- all: all agents, including private ones. It is currently used by the agent
  builder to check the number of agents, and if a name is already taken, and
  internally  by poke

**Comment by philipperolet** [comment]
New views, see related PR #2778

**Comment by spolu** [comment]
Closing as I believe this is complete now?
