### ISSUE TITLE
[Ahuna] Assistant gallery modal

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#2646]
- Create the page as per [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=2700-17199&mode=design&t=NATsjHgMbFZdKwHy-4)
- ignore the names under the assistant
- ONLY with All / From workspace / from dust tabs for now
- NO Add / test buttons (but ... button for AssistantDetails modal)
- Button "See all assistants" from home conversation points to gallery
- assistant gallery should
    - not show private assistants
    - not show assistants from my list when shopping for new ones
    - show workspace assistants with triggers? or how?

Related [framing](https://github.com/dust-tt/decisions/issues/111#top) and [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=2677-10559&mode=design&t=B7nphNLIUPBjCls5-0)

Prototypes of what's going to be done are [here for members](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?page-id=2677%3A10559&type=design&node-id=2677-10560&viewport=470%2C31%2C0.25&t=L0qImC25TEHwijGx-1&scaling=min-zoom&starting-point-node-id=2677%3A10560) and [here for admins](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?page-id=2677%3A10559&type=design&node-id=2929-29336&viewport=470%2C31%2C0.25&t=L0qImC25TEHwijGx-1&scaling=min-zoom&starting-point-node-id=2929%3A29336&show-proto-sidebar=1)

**Comment by spolu** [comment]
Test is not implemented yet but will add a card for that
