### ISSUE TITLE
[Ahuna] My assistant page & nav for users

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#2648]
- `Assitants >` as nav item, replacing the tabs
- Create the page as per [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=2698-15117&mode=design&t=NATsjHgMbFZdKwHy-4)
- Update assistant gallery
    - 'Add' button
    - 'Published by team’ tab
- 'My assistant' page => make it available to all (not only dust as per task #)
- Mind the visibility change flow [here](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=3114-21997&mode=design&t=YFE5Hncm6N3CLqdb-4)
    - and the constraint of exactly 1 user for a ‘private’ assistant

Related [framing](https://github.com/dust-tt/decisions/issues/111#top) and [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=2677-10559&mode=design&t=B7nphNLIUPBjCls5-0)

Prototypes of what's going to be done are [here for members](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?page-id=2677%3A10559&type=design&node-id=2677-10560&viewport=470%2C31%2C0.25&t=L0qImC25TEHwijGx-1&scaling=min-zoom&starting-point-node-id=2677%3A10560) and [here for admins](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?page-id=2677%3A10559&type=design&node-id=2929-29336&viewport=470%2C31%2C0.25&t=L0qImC25TEHwijGx-1&scaling=min-zoom&starting-point-node-id=2929%3A29336&show-proto-sidebar=1)

**Comment by philipperolet** [comment]
Optional: add soft warning when sharing conversation of a private assistant (copy link button) "The person you share the conversation will be able to use private (this is also true from other people who get the link)
+ maybe visual cue on the conversation? TBD

**Comment by spolu** [comment]
Will take this one if Ok with you @philipperolet 👍

**Comment by spolu** [comment]
Nav is here: https://github.com/dust-tt/dust/pull/2850

**Comment by spolu** [comment]
Nav is done this is still open for My assistant page
