### ISSUE TITLE
[Ahuna] Admin 'Workspace assistants' page

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#2650]
[Figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=3146-19109&mode=design&t=NATsjHgMbFZdKwHy-4)

- Mind the visibility change flow [here](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=3114-21997&mode=design&t=YFE5Hncm6N3CLqdb-4)

Related [framing](https://github.com/dust-tt/decisions/issues/111#top) and [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=2677-10559&mode=design&t=B7nphNLIUPBjCls5-0)

Prototypes of what's going to be done are [here for members](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?page-id=2677%3A10559&type=design&node-id=2677-10560&viewport=470%2C31%2C0.25&t=L0qImC25TEHwijGx-1&scaling=min-zoom&starting-point-node-id=2677%3A10560) and [here for admins](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?page-id=2677%3A10559&type=design&node-id=2929-29336&viewport=470%2C31%2C0.25&t=L0qImC25TEHwijGx-1&scaling=min-zoom&starting-point-node-id=2929%3A29336&show-proto-sidebar=1)

**Comment by spolu** [comment]
@philipperolet do we agree the scope of this task is to have the Assistant page for users as well where they can see "From the Workspace" assistants and add/remove from their list?

With a disabled toggle for the global assistants?

I guess we also want From Dust ? so that we have no toggle there instead?

cc @Duncid

**Comment by philipperolet** [comment]
Assistant page for regular users is in this [other task](https://github.com/dust-tt/dust/issues/2648) 
I had assigned it to me friday evening but was too eager
Since I'm eng running + demoing artefact tom, putting that task back to in progress
As we discussed IRL, the scope of tasks can be cut out again

**Comment by spolu** [comment]
As per discussion with @Duncid no change of behavior in the workspace assistant page. 

The change of behavior of global assistants will be worked on sperarately
