### ISSUE TITLE
[Caloris] [Structured Data] Support for array columns

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#2659]

**Comment by spolu** [comment]
For record: using JSON in sqlite who mean this:

```
-- Enabling the JSON1 extension if needed
SELECT load_extension('json1');

-- Create a table with a JSON field
CREATE TABLE my_table (
    id INTEGER PRIMARY KEY,
    string_array TEXT
);

-- Insert an array of strings stored as JSON
INSERT INTO my_table (string_array) VALUES (json('[ "string1", "string2", "string3" ]'));
```

To match any string that would be:

```
SELECT mt.*
FROM my_table mt, json_each(mt.string_array)
WHERE json_each.value = 'string2';
```

Which means there is no possibility of indexing and sqlite would have to go over all records to match. This seems fine for not too big databases, since we're already scrolling anyway to create the database and I guess we can accept a bit of latency at query time.

**Comment by spolu** [comment]
I'm not yet fully convinced compared to the table approach:
```
CREATE TABLE main_table (
    id INTEGER PRIMARY KEY
);

CREATE TABLE strings (
    main_table_id INTEGER,
    string_value TEXT,
    FOREIGN KEY (main_table_id) REFERENCES main_table(id)
);

INSERT INTO main_table (id) VALUES (1);
INSERT INTO strings (main_table_id, string_value) VALUES (1, 'string1');
INSERT INTO strings (main_table_id, string_value) VALUES (1, 'string2');
INSERT INTO strings (main_table_id, string_value) VALUES (1, 'string3');

SELECT mt.*
FROM main_table mt
JOIN strings s ON mt.id = s.main_table_id
WHERE s.string_value = 'string2';
```

**Comment by spolu** [comment]
To think about what the model would see:

For JSON: the DBML would be
```
Table my_table {
  id INTEGER 
  string_array TEXT [note: JSON array]
}

// or maybe

Table my_table {
  id INTEGER 
  string_array JSON
}
```

For multi-table:
```
Table main_table {
  id INTEGER
}

Table strings {
  id INTEGER
  main_table_id INTEGER [ref: > main_table.id] 
  string_value TEXT 
}
```

Feels like the JSON solution will always be a bit ambiguous 🤔

**Comment by fontanierh** [comment]
I agree, multi table seems cleaner and looks like it will produce better results 👍

**Comment by fontanierh** [comment]
For now, I landed on a "prompt-only" solution, suggesting to the model a way to properly handle comma-separated lists as a text column. This seems to work well enough for now, so let's revisit if we end up needing the multi-table solution.
That solution would require some extra framing, as it would mean that one `Table` (as seen by users) can actually map to several SQLite tables.
