### ISSUE TITLE
UI Freeze when accessing some public apps

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#267]
The page becomes unresponsive when viewing certain public apps, CPU consumption at 100%. Seems to be caused by an infinite active loop, cf screenshot. 

Bug apparently restricted to public apps with datasources e.g. happens with `spolu/ipcc-ar6-qa` and `spolu/phrack-answers` but not `spolu/web-assistant-2`
Reproduced on Brave, Firefox & Chrome as a logged or unlogged user

![Screenshot from 2023-04-20 17-19-41](https://user-images.githubusercontent.com/5437393/233413272-7f606343-245c-45a2-8305-27b2f9114189.png)

**Comment by spolu** [comment]
(deployed)

**Comment by spolu** [comment]
Thank you for reporting :pray:

**Comment by philipperolet** [comment]
My pleasure, thanks for the quick fix & for dust in general 😉

Le jeu. 20 avr. 2023, 19:26, Stanislas Polu ***@***.***> a
écrit :
