### ISSUE TITLE
[Caloris] [Structured Data] Frame the "ad-hoc" upload (or "JIT-database") experience

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#2699]
This is essentially the "upload document" / "content fragment" experience, but for structured data

**Comment by fontanierh** [comment]
It is challenging because we may have to force a specific assistant once the user uploads ?

**Comment by fontanierh** [comment]
Not doing for now, to frame as part of a more general input-bar related climb.

**Comment by spolu** [comment]
:+1: 

I was thinking about this morning. Writing down here for prosperity.

One solution could consists in forcing an action to be run in certain conditions. Eg here we upload a CSV file, in which case all assistants work as expected but in presence of that CSV file the next interaction will trigger a tables query action independently of the assistant being picked.

That would allow:
- upload CSV
- @gpt4 question 

This goes quite a long way. But still has limitations. Eg, in presence of code interpretation. How would the interplay work? But at the same time we have the same problem with content fragment. When code interpreting we likely don't want a content fragment but instead make the file available to the code environment...

Some leads. Nothing final.

**Comment by spolu** [comment]
cc @dust-tt/product-team

**Comment by spolu** [comment]
You get both actions yes :+1:

**Comment by fontanierh** [comment]
got it

**Comment by fontanierh** [comment]
But then you can only ask a single question ? After that, you'd need to upload the CSV again to ask follow-up questions ?

**Comment by spolu** [comment]
Unless we add the action to the assistant for the whole convo... and let the assistant choose. But it still does not feel perfect for sure.
