### ISSUE TITLE
llm blocks do not do variable expansion of the few shot introduction

### ISSUE THREAD

**Issue by aickin** [dust-tt/dust#27]
To repro, feed in some data from a previous block and try to read it out in a few shot introduction with something like "Here are some news stories about ${INPUT.person}". The variable will not get expanded, and Dust sends the literal string "${INPUT.person}" to GPT3.

**Comment by aickin** [comment]
This should be a pretty easy one line fix in `llm.rs`, but the function is moving files in PR #25, so probably best to wait for that to land before adding the function call.

**Comment by spolu** [comment]
Yep all done :+1:
