### ISSUE TITLE
Can't select a model on Azure Open AI in DUST App interface

### ISSUE THREAD

**Issue by milstan** [dust-tt/dust#2811]
I configured an Azure OpenAI instance (successfully), and then when I try to direct my DUST App to it, I can't deploy the app beacuse the 'select model' is empty. Clicking on it offers 0 options.

![image](https://github.com/dust-tt/dust/assets/317424/792b5435-df3c-4948-a7e6-e0096e1a7fbc)

**What I expected**
- A list of models available on my Azure OpenAI (in this case only one)
![image](https://github.com/dust-tt/dust/assets/317424/09d9931c-dae5-4fbf-9704-85a82fe98349)

- Or alternatively, an error message point me to why the 'select model' list is empty and what can I do to fix it.

**Comment by milstan** [comment]
More info:
 tested the API call from [this line of code](https://github.com/dust-tt/dust/blob/4a53203b889e9b88824715ac133a361d7522eb5f/front/pages/api/w/%5BwId%5D/providers/%5BpId%5D/models.ts#L153), with the same endpoint/API key, and successfully got:
 ```
{
  "data": [
    {
      "scale_settings": {
        "scale_type": "standard"
      },
      "model": "gpt-35-turbo",
      "owner": "organization-owner",
      "id": "gpt_35_turbo",
      "status": "succeeded",
      "created_at": 1702114559,
      "updated_at": 1702144202,
      "object": "deployment"
    }
  ],
  "object": "list"
}
```

Not usre where it gets lost later, but when the frontend makes the call: 
`.../providers/azure_openai/models?chat=false&embed=false`

The response is an empty list:
```
{"models":[]}
```
 
 Also, the the azure openai instance responds correctly in a curl call:
 
 ```
 curl <my_endpoint>openai/deployments/gpt_35_turbo/completions?api-version=2023-05-15 \
>   -H "Content-Type: application/json" \
>   -H "api-key: <my_API_key" \
>   -d "{\"prompt\": \"Once upon a time\"}"
 ```
 yields:
 ```
{"id":"...","object":"text_completion","created":1702155159,"model":"gpt-35-turbo","choices":
[{"text":" there was a persevering, tireless customer services professional, whose job was to","index":0,"finish_reason":"length","logprobs":null}],"usage":{"prompt_tokens":4,"completion_tokens":16,"total_tokens":20}}
 ```
 
Without going throught details of the code, I suspect the fact the model is called `gpt-35-turbo` without the dot between 3.5 might be at odds with this part [here](https://github.com/dust-tt/dust/blob/4a53203b889e9b88824715ac133a361d7522eb5f/front/pages/api/w/%5BwId%5D/providers/%5BpId%5D/models.ts#L188). 

These are the model names Azure proposes (at least in my princing plan):
![image](https://github.com/dust-tt/dust/assets/317424/8d4c3728-eb6f-47b5-aa1a-64dcf78881c6)

**Comment by spolu** [comment]
Hi @milstan 

The model selection in Dust requires a deployment to be active on your azure account.

What name did you use for your deployment ooc?

**Comment by milstan** [comment]
Hi @spolu , thanks for the fast response! 

I do believe I have an active deployment under the name `gpt_35_turbo`. It's possible that I still have to configure something more on Azure, but see curl calls in my previous message, I do manage to get a response from it. The name is returned by Azure openai/deployments? endpoint as 
```
"id": "gpt_35_turbo",
```
The model however is susspciousely named `gpt-35-turbo` without the dot, which I suspect to be the problem here.

**Comment by spolu** [comment]
The selector should be able to accept any model name. Keeping the original model is nonetheless advised as it'll be used to decide whether it's a chat model or not.

**Comment by milstan** [comment]
> If you have the wrong model name and are using the Chat block then the behavior is expected.
> 
> You should see the model under the Model block.

I'm using the LLM block. Still the same result:
![image](https://github.com/dust-tt/dust/assets/317424/18d7e9f8-787b-4be1-8eeb-d74ed65b8506)

Unfortunately in my Azure interface I don't think I have any control over the model names. I can only pick one from the drop-down, the only 3 options being:

![image](https://github.com/dust-tt/dust/assets/317424/8d4c3728-eb6f-47b5-aa1a-64dcf78881c6)
