### ISSUE TITLE
Adding description to Assistant Builder list of actions

### ISSUE THREAD

**Issue by Duncid** [dust-tt/dust#2840]
Use the "Item" component with description the **action list** of the **Assistant Builder**

- Example of items with description
![Image](https://github.com/dust-tt/dust/assets/4435185/8f4dd768-07ea-47f5-9256-459624dbb790)

- The action list as is today
![Image](https://github.com/dust-tt/dust/assets/4435185/75a2c781-b925-4ad7-8eff-880b68c13a72)

**Comment by spolu** [comment]
done in Meru
