### ISSUE TITLE
The InputBar autocompletion on mentions does not select the best proposal by default

### ISSUE THREAD

**Issue by Duncid** [dust-tt/dust#2871]
When user input `@du` the selected mention is "@blablabla-dust" when it should be "@dust" :

![Image](https://github.com/dust-tt/dust/assets/4435185/21632ac4-9c09-4115-b802-20f3a7f31ffe)

**Comment by philipperolet** [comment]
@Duncid could not reproduce the issue, cf screenshot. Maybe it was fixed in the meantime? If you see it again ping me so I can investigate the context

![Image](https://github.com/dust-tt/dust/assets/5437393/f85e5444-693f-4367-ac57-f2f0863e66d7)
