### ISSUE TITLE
[Ahuna] copy edits

### ISSUE THREAD

**Issue by gabhubert** [dust-tt/dust#2886]

**Comment by gabhubert** [comment]
@Duncid assigning to you. 

## Top
![Image](https://github.com/dust-tt/dust/assets/998689/a250118f-abb8-4998-8a50-063be7434b1e)
- **Title**: Workspace Assistants (Camel Case needed + we don't need the manage, it's not in e.g. Connections or Folders)
- **Tagline**: Manage the Assistants available for all workspace members. (_meta: @Duncid can you please remove the word collaborators fro all figma files once and for all please, I don't want it in the product, ever :)_)

## Section 1
![Image](https://github.com/dust-tt/dust/assets/998689/54942fa5-2b5b-433d-a3e8-254ad5509ddb)
- **Title**: Custom Assistants
- **Tagline**: Build Assistants tailored to yours needs with specific Instructions and Actions for better performance.
- Search bar placeholder: unchanged
-

**Comment by gabhubert** [comment]
## Section My Assistants


![Image](https://github.com/dust-tt/dust/assets/998689/89d7165a-7631-439d-8538-454704113dbf)

- title: My Assistants (camel case, remove the verb)
- tagline: Manage the Assistants visible to you and create your own Assistants.

![Image](https://github.com/dust-tt/dust/assets/998689/93fdf4db-a1a6-4ffe-ae04-efbb47c34a19)

- **Button**: I'd say "View Gallery" as this contains remove / delete actions too

**Comment by gabhubert** [comment]
- Manage: we don't use it for data sources, and I think that ligghter is better when we can (especially since the tagline has it)
- Add: I could give you that one, even though it's not the only action in the Gallery (focus on the leading one)
- Suggested: but they are suggested to the admin :). I just don't think they're "Dust assistants", they don't assist Dust and they don't really point to a Dust thing (this list has raw models and data-source assistants)

**Comment by spolu** [comment]
@gabhubert @Duncid @philipperolet what's the status here?

Will move this to in progress and close [Ahuna] as a climb

**Comment by gabhubert** [comment]
@Duncid can you recover state from this discussion into the current work on Ahuna copy/ux edits please.

**Comment by philipperolet** [comment]
@Duncid NRE - ok to close this task? as it has been superseeded by your new framing?

**Comment by gabhubert** [comment]
@Duncid ping to reply so we can move on this?
