### ISSUE TITLE
[Olympus] Support for Gemini Pro

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#2905]

**Comment by fontanierh** [comment]
sitrep: most of the work done, but doesn't work properly yet due to having the wrong roles and our implementation lacking proper function calling support.
PR in the works to fix both.
There will also be a last PR to add a global Gemini asssitant.

**Comment by spolu** [comment]
Can this be closed?

**Comment by fontanierh** [comment]
Indeed, forgot to close
