### ISSUE TITLE
[Multi-actions] [Google Vertex AI] Support function calling / tools on Gemini model(s)

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#2928]

**Comment by philipperolet** [comment]
IMHO this is now part of multi-actions, and we'll adress once gemini is reinstated in a few weeks. As such, moving to the multi-actions column
Correct me if needed :)

**Comment by fontanierh** [comment]
We cannot do it for now (not supported by GOOG), closing for now

**Comment by spolu** [comment]
Heard a couple time that 1.5-flash is really good at it.

**Comment by fontanierh** [comment]
Can't wait to try when we finally get it @spolu
