### ISSUE TITLE
[Ahuna] check Assistant name with a GET query instead of loading the full list

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#2970]
Instead of loading the full list of agents in the AssistantBuilder, use a GET query that is run (debounced) on edits of the assistant name.

This will allow us to not load the agent configurations at all in this view

**Comment by philipperolet** [comment]
should we check against private assistant names? seems semi-leaky but probably acceptable?

**Comment by philipperolet** [comment]
As per irl, acceptable mini-leak
