### ISSUE TITLE
Managing URL in Prompts

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#3018]
Goal:

Being able to use URLs in prompt as a pointer to a data source.

Logic:
- If the URLs is for a connected data source (Notion, GDrive,…) we can find the document it refers to and use it as context for the prompt
  - Beware that a Notion can link to the Notion of the company (connected data source) or to a Notion page external to the company
- If the URL is pointing to an unknown web resources, we crawl the page and use the result as fragment
  - Beware that URL may be un accessible to us (behind authentification) and we need to manage that error

There may be more than one URL in a prompt

**Comment by philipperolet** [comment]
This is now part of an explicit go/pp project AFAICT (input bar actions); closing
