### ISSUE TITLE
[Caloris2] [Github Code] Frame product rollout

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#3027]
Frame rollout: feature flag first? self-serve? on by default moving forward?

See https://github.com/dust-tt/dust/issues/2324

**Comment by gabhubert** [comment]
- **feature flag**: seems we should start there to get some feedback from ~Alan anyway?
- **connector**: I'd make it available but toggle (default==no) by admin at the connector level. It's a (weirdly) sensitive topic and giving control to the admins on will be appreciated for.
- **default moving forward**: let's wait on feedback from Alan?

**Comment by spolu** [comment]
Aligned :+1:

**Comment by spolu** [comment]
# Framing for rollout

## Context

We now have support for Code sync. When activated, a new node appears under each repository of the Github connector called "Code" along with "Discussions" and "Issues". This node has children displaying the code hierarchy we synced.

## Limits

We enforce a whitelist of file extensions and a blacklist of directory names that generally includes binary/build data. We limit ourselves to repos whose total size is 1GB (pre-filtering). We also do not sync files that are more than 1MB of data. We sync the code every 8h.

## Current state

Github code syncing can be enabled in poke.

## Rollout

We propose to have a toggle on the Github connection screen to enable github code syncing (ala Slack bot toggle). We definitely don't want to enable by default for 2 reasons:

(i) Sensitivity of code.
(ii) Existing assistant that have selected Github repository as data sources would now perform retrieval on code as well.

While (i) is solved by having an opt-in (ii) is only partially solved. I presume we could have a popup display a warning covering (ii) when the user attempts to enable it (but a popup on a toggle is not great and not even supported today in sparkle I thiiink).

## Immediate next-steps

Enable it on our workspace + ping Alan to work with them towards enablement (potentially listing assistants that may be impacted) with the objective of deleting the code syncing data source they have today.

## Folllow-up

Implement the toggle in the connection view after converging on what should be the right wording/UX there given (ii).

**Comment by spolu** [comment]
Proposal communication for beta-testing users.
```
# Release: Github code syncing
Status: beta (meaning that the behavior may change as we iterate on it) 

We added support for code syncing in our Github connector. When enabled, the code associated with the repositories synchronized in the Github connection will be ingested and kept up to date every 8h.

<for users having built it internally>
Since you explored this use-case internally, we hope that we can transition your usage on this new feature and delete the data sources associated with your explorations.
</for users having built it internally>

## Limitations

When enabled, this will impact the assistants that perform retrieval on Github repositories, as they will now retrieve code on top of Issues / Discussions. We added the capability to select independently Issues / Discussions and/or Code when selecting data from a Github data source so that you can adapt existing assistants to the new content.

We'll be happy to provide you with a list of potentially assistants to review
```

**Comment by spolu** [comment]
Friendly bump @gabhubert @Duncid

**Comment by spolu** [comment]
(Will go ahead with first design partners messaging)

**Comment by spolu** [comment]
papertrail: https://dust4ai.slack.com/archives/C0525Q93AEL/p1705651289479569

**Comment by spolu** [comment]
Context on first user rollout: https://dust4ai.slack.com/archives/C0525Q93AEL/p1705651289479569

It seems obvious that we want to be able to migrate existing assistants to Issues/Discussions instead of whole repo before enabling code sync

**Comment by spolu** [comment]
Working on that.

**Comment by spolu** [comment]
Alan is live after having run the migration with no issue.

@gabhubert @Duncid @Yutcam ready to add more workspaces among our existing users or move on to the rollout plan proposed above

**Comment by gabhubert** [comment]
Next steps: mention to customers in the weekly round-up, ok to take @Yutcam?

**Comment by gabhubert** [comment]
yeah don't think anyone followed up so it'd be (1) with an eng mentioned and (2) with a CtA to follow up with us!
