### ISSUE TITLE
[Caloris2] [Github Code] incremental sync

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#3107]
Daily resync logic

2 possibilities:
- cron like temporal workflow (but meh to add that to the github connector)
- listen for code change webhooks and have a lastCodeSync element per repo to decide whether to start a new sync or not

@fontanierh WDYT? I think I'm in favor of 2?

**Comment by fontanierh** [comment]
> listen for code change webhooks and have a lastCodeSync element per repo to decide whether to start a new sync or not

This means adding a new "repos" table right ?
cron has the advantage of not requiring a new table but we don't have any cron jobs right now so 1 feels "heavier" than 2.

aligned 👍

**Comment by fontanierh** [comment]
It's also not ideal to download the tarball everyday for repos that don't have code changes, so it seems like we would need to listen to code changes anyway and have some kind of long running workflow and use signals which sounds a lot more painful than storing lastCodeSync

**Comment by fontanierh** [comment]
How will we make sure we don't miss updates though ? What if there are several code changes before the due date, but then no change for several periods (eg weekend) ?

**Comment by spolu** [comment]
I think I'm fine with that. That means the repo is not active anymore and will fix itself as soon as it become active again

**Comment by fontanierh** [comment]
> I think I'm fine with that. That means the repo is not active anymore and will fix itself as soon as it become active again

Fair 👍  That also means that repos data may become stale on weekends / vacations but we can revisit if that ever becomes an issue.
