### ISSUE TITLE
[Caloris2][URL Connector] Add crawling settings

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#3167]
# crawling settings 

## Crawling depth

The depth of links to follow. 
Use cases:
- **A wikipedia page**: you probably want to follow up to 1 depth, in order to crawl the wikipedia page itself and all the links it references.
- **A help center**: You probably want to start from the main page of the help center and crawl up to a few level of links (somewhere between 2 and 5) in order to crawl all the articles.

## Word matching
A list of words that must be in the URL for a page to be crawled.
The problem is that every page of a website references a bunch of "common pages" like Home, Contact Us, TOS etc, that you probably don't want to crawl. 
If you are crawling a large website about a specific topic, you might want to crawl only the pages with an URL that contains a specific word.
For the Wikipedia example, if you are crawling the web page "Product Design", you can set a crawling depth of 1 and a word matching of "design" in order to crawl only pages that are likely related to "product design".

**Comment by spolu** [comment]
I presume this is done @lasryaric
