### ISSUE TITLE
[Caloris 2] Intercom - Base infrastructure

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#3209]

**Comment by spolu** [comment]
cc @philipperolet created that to aggregate pointers

**Comment by spolu** [comment]
https://github.com/dust-tt/dust/pull/3205
https://github.com/dust-tt/dust/pull/3204
https://github.com/dust-tt/dust/pull/3203

We have 3 opened PRs there might be one big PR somewhere as well that covers the 3

**Comment by spolu** [comment]
Context slack thread: https://dust4ai.slack.com/archives/C050SM8NSPK/p1705078319104459

**Comment by philipperolet** [comment]
:pray:  cc @PopDaph for when you're back, I'm the one that's picking up
