### ISSUE TITLE
[Caloris 2] Intercom - Submit app

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#3211]

**Comment by spolu** [comment]
Issue to track our app submission

**Comment by PopDaph** [comment]
We got an answer from Intercom, I'm handing feedback and resubmitting accordingly: 


_Thank you for submitting your app for review! We need a few more details/clarification, once you provide them we would be happy to review your app again._ 
 
 _1. We would need to see the OAuth flow that an end user would go through including the client_id and the presence of the state parameter in the OAuth URL. In the recording you submitted I am not able to see the state parameter. Please resubmit with a video showing this workflow. More on that here in our docs: https://developers.intercom.com/building-apps/docs/setting-up-oauth (https://developers.intercom.com/building-apps/docs/setting-up-oauth)_ 
_2. You should only be selecting the scopes that are needed based on the app's current functionality and also provide a description in the app description section of the submission or in the walkthrough video of why each scope is needed that would be helpful. More information here in our docs: https://developers.intercom.com/docs/build-an-integration/learn-more/authentication/oauth-scopes/ (https://developers.intercom.com/docs/build-an-integration/learn-more/authentication/oauth-scopes/)_ 
_3. The long description section of your App Store listing should be 2-3 paragraphs outlining how the app would be useful specifically for Intercom customers. More information on this can be found here: https://developers.intercom.com/docs/publish-to-the-app-store/listing-your-app/#long-description (https://developers.intercom.com/docs/publish-to-the-app-store/listing-your-app/#long-description)_ 
_4. Also suggest adding images. Images help customers quickly understand what your app does and let you highlight key features. Please refer to the section here in our docs for more information as well as examples of how they should be formatted: https://developers.intercom.com/docs/publish-to-the-app-store/listing-your-app/#app-images (https://developers.intercom.com/docs/publish-to-the-app-store/listing-your-app/#app-images)_

**Comment by PopDaph** [comment]
App validated yesterday!
