### ISSUE TITLE
Update agent message UX in conversation

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#3262]
As per [here](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22846&mode=design&t=Dlhq25QyeMahW2OI-4)

Changes including (but check figma for others)
- Assistant name in a message now is clickable (opens the Assistant Detail View)
- A more clickable icon (iconButton) opens a menu

Full [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22251&mode=design&t=Dlhq25QyeMahW2OI-0) (source of truth)

Full [issue](https://github.com/dust-tt/decisions/issues/147#issue-2081773564)

**Comment by philipperolet** [comment]
Even clearer specs via the [prototype](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22252&t=PrquaF04miEgyEMq-0&scaling=min-zoom&page-id=4050%3A22251&starting-point-node-id=4050%3A22252&show-proto-sidebar=1)

**Comment by flvndvd** [comment]
**- Assistant name in a message now is clickable (opens the Assistant Detail View)**

This has been merged in https://github.com/dust-tt/dust/pull/3534 and is only released to the Dust team for now. Waiting more refactoring of the `AssistantDetails` component.

**- A more clickable icon (iconButton) opens a menu**

PR is waiting for review here: https://github.com/dust-tt/dust/pull/3547
