### ISSUE TITLE
Update assistant selection menu

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#3263]
According to section Screens/inputbar [here](https://github.com/dust-tt/decisions/issues/147#issue-2081773564)

Including:
- The Assistant selection menu needs to be updated with right wording and iconography.
- Add a "more" button that opens Assistant Detail View
(note: use the newly updated dropdown component that can do all that's in the figma)

**Comment by philipperolet** [comment]
Figma link: https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22255&mode=design&t=675WBPvIgubbwQiv-4

**Comment by spolu** [comment]
Fixed by https://github.com/dust-tt/dust/pull/3410#event-11586453965
