### ISSUE TITLE
Small changes in the empty conversation help content

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#3264]
As per [here](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22254&mode=design&t=Dlhq25QyeMahW2OI-4)

Full [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22251&mode=design&t=Dlhq25QyeMahW2OI-0) (source of truth)

Full [issue](https://github.com/dust-tt/decisions/issues/147#issue-2081773564)

**Comment by flvndvd** [comment]
@philipperolet @Duncid, could you clarify what the "small changes" means? It's challenging to infer from the Figma designs. I noticed @Duncid added an `AssistantPreview2` alternative to `AssistantPreview`. Does this involve switching to it?

**Comment by Duncid** [comment]
Lates version [here](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=180%3A4077&mode=design&t=7VuSZ0PzV0LezQXe-1).

Changing the AssistantPreview is clearly one of them.
- **Member**: Seems it's just the item
- **Builder / Admins**: The action in "Assistants" don't link to the gallery but to the "manage assistants" screen.
  - Make the Notion / Drive… icons clickable (-> go to connections)

Following usability test, it makes sense to display the editors here as well (By: x, y, z).
So I updated the AssistantPreview2 in figma. It needs to be updated in Sparkle as a consequence.

<img width="1071" alt="image" src="https://github.com/dust-tt/dust/assets/4435185/b094374d-8abb-4db0-9a85-8eeae7b756a1">

<img width="783" alt="image" src="https://github.com/dust-tt/dust/assets/4435185/238b0c4e-59bd-4d3e-a8fd-794769042a60">
