### ISSUE TITLE
Update Assistant Detailed View

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#3265]
As per [here](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22778&mode=design&t=wGVRT1IiZNJ18Mm1-4) and note the 4 other views

The screen depends on 2 settings:

- The member rights (Member, Builder)
- The assistant type (Default, Company, Shared, Personal)

Edit rights cover editing Type (Company, Shared, Personal) and editing the assistant instructions.

All actions are in a dropdown behind an Action menu.

Note: use the newly updated dropdown component that can do all that's in the figma

Also, there is a specific interaction to add/remove from list (see section Assistant Detail view of the [issue](https://github.com/dust-tt/decisions/issues/147#issue-2081773564))
For this, a specific (non-sparkle) component should be made and mutually used with the assistant preview in the gallery

Full [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22251&mode=design&t=Dlhq25QyeMahW2OI-0) (source of truth)

Full [issue](https://github.com/dust-tt/decisions/issues/147#issue-2081773564)

**Comment by philipperolet** [comment]
Mildly depends on #3270

**Comment by philipperolet** [comment]
In dropdown, blue means "current selection" (not hover), which is a sparkle component option

**Comment by philipperolet** [comment]
### The Activity Sentence
When we want to explain how much an assistant is used, we use the activity sentence:

"This assistant is active for X members, has sent Y messages in the last 30 days."

- Active for X members means that is in the my assistant list of X members. If it's a shared assistant it means how many people have added it to there list. If it's a company assistant, it means all the members.
- Messages is the number of posted messages by the assistant (not number of threads)

**Comment by flvndvd** [comment]
@philipperolet are you working on that one?

**Comment by philipperolet** [comment]
yep

**Comment by philipperolet** [comment]
Merged. As per discussion IRL with ed, no need to do the "Chevron left" on the modal, we can leave the cross

The chevron left will be done as part of another larger modal refactor and is not critical for now
