### ISSUE TITLE
Update assistant gallery

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#3274]
As per [here](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22609&mode=design&t=675WBPvIgubbwQiv-4) and importantly see video at section Assistant Gallery of the [issue](https://github.com/dust-tt/decisions/issues/147#issue-2081773564)
Use AssistantPreview component (to be soon pushed by @Duncid)

Changes include hover, test button, add/remove to list using same component as in #3265, etc.

Depends on #3265 

----------
Full [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22251&mode=design&t=Dlhq25QyeMahW2OI-0) (source of truth)

Full [issue](https://github.com/dust-tt/decisions/issues/147#issue-2081773564)

Even clearer specs via the [prototype](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22252&t=PrquaF04miEgyEMq-0&scaling=min-zoom&page-id=4050%3A22251&starting-point-node-id=4050%3A22252&show-proto-sidebar=1)

**Comment by flvndvd** [comment]
@Duncid the prototype does cover it, do we want to let builders try assistants already in their list from the gallery?

**Comment by Duncid** [comment]
I don't see a strong reason not to let them.

**Comment by flvndvd** [comment]
Should the `AssistantDetails` view offers the same behavior?
