### ISSUE TITLE
[Ahuna II] [Nice-to-have] Search allows finding assistants in the gallery

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#3278]
As per bottom of the framing [issue](https://github.com/dust-tt/decisions/issues/147#issue-2081773564)

----------
Full [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22251&mode=design&t=Dlhq25QyeMahW2OI-0) (source of truth)

Full [issue](https://github.com/dust-tt/decisions/issues/147#issue-2081773564)

Even clearer specs via the [prototype](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22252&t=PrquaF04miEgyEMq-0&scaling=min-zoom&page-id=4050%3A22251&starting-point-node-id=4050%3A22252&show-proto-sidebar=1)

**Comment by spolu** [comment]
Is this still relevant?

**Comment by philipperolet** [comment]
IMHO no, the need is not strong enough. If it becomes so, it will resurface. Closing.
