### ISSUE TITLE
Rework assistant usage to match newly defined business rules

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#3330]
A usage sentence is already present (initialy coded by @lasryaric ) but the definition of what product wants as 'usage' has been clarified, and may thus differ with the existant

This task consists in updating what's been coded to match the new business logic, described below (see the related [framing](https://github.com/dust-tt/decisions/issues/147#issue-2081773564) for all context)

## The Activity Sentence
When we want to explain how much an assistant is used, we use the activity sentence:

"@xxx is active for X members and has been used Y times by Z members in the last 30 days."

- X: Number of workspace members having the assistant in their My assistant list. If it's a shared assistant it means how many people have added it to there list. If it's a company assistant, it means all the members.
- Y: Number of posted messages by the assistant (not number of threads)
- Z: Members having mentioned the assistant in the last 30 days

**Comment by lasryaric** [comment]
@philipperolet I think there is an updated version of it:
```
X: Number of workspace members having the assistant in their My assistant list. If it's a shared assistant it means how many people have added it to there list. If it's a company assistant, it means all the members.
Y: Number of posted messages by the assistant (not number of threads)
Z: Members having mentioned the assistant in the last 30 days
```

**Comment by philipperolet** [comment]
### The Activity Sentence
When we want to explain how much an assistant is used, we use the activity sentence:

"@xxx is active for X members and has been used Y times by Z members in the last 30 days."

- X: Number of workspace members having the assistant in their My assistant list. If it's a shared assistant it means how many people have added it to there list. If it's a company assistant, it means all the members.
- Y: Number of posted messages by the assistant (not number of threads)
- Z: Members having mentioned the assistant in the last 30 days

**Comment by philipperolet** [comment]
The Assistant Details phrase, a bit different, is not affected by this change
