### ISSUE TITLE
[Caloris2] [Confluence] Add production checks for Confluence

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#3381]
Production checks to ensure that Confluence workflows are running, it includes:
- Sync workflows
- Personal data report workflows

**Comment by spolu** [comment]
@flvndvd do you plan to do or can we kill?

**Comment by flvndvd** [comment]
I'll add them tomorrow.

**Comment by flvndvd** [comment]
Done for both Confluence and Intercom in https://github.com/dust-tt/dust/pull/3887.
