### ISSUE TITLE
Improve error handling of OpenAI embedding flakyness

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#3394]
When OpenAI embedding api is flaky, a few percent of the api call fail, leading to
- monitor: High 500 errors on front from upsert failures
- Failed retrievals from assistants
If the API is just flaky but not down, we want users to understand it's not us, and they can retry. For that, we should adapt the error
Best way to handle this is to detect and treat the specific OAI errors
1. Add an error layer in types (e.g. isOpenAIEmbeddingError, corresponding errror code)
2. In front, yield the right error in events and handle the specific error message (do it in a generic way so other errors we want to handle can be
3. Regarding failed upserts, mark them with the same error code, and move them to a specific monitor (remove them from high 500 volume)

**Comment by spolu** [comment]
Not a problem these days
