### ISSUE TITLE
[Caloris 2][URL Connector] Deploying to all users

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#3513]

**Comment by spolu** [comment]
Open questions for me:
- creation UI
- Incremental sync
- Advanced settings support 
- Do we want to give custom names?

**Comment by lasryaric** [comment]
CLosing this issue as this has just been shipped.

@spolu I forgot to address:
> Do we want to give custom names?

We'll see if users ask for it. For now we derive the name form the URL.
