### ISSUE TITLE
[Caloris][Structured Data] Improve UX of CSV upload

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#3570]
I found the UX of CSV upload quite confusing (the button showing the file name but remaining clickable. It's also clickable while uploading. And still clickable post pressing Save.

Given that the structured data product is a bit hard to understand I think we want the experience to be as smooth as possible wherever possible 👍

**Comment by spolu** [comment]
Also the Description field seems quite big. It almost feel like it's the content and therefore appear as intimidating.

**Comment by fontanierh** [comment]
> is this still relevant?

Partly. We do have proper loading indicators now

**Comment by fontanierh** [comment]
Closing. We have the right loading indicators and buttons are disabled while upload is ongoing

**Comment by fontanierh** [comment]
Closing. We have the right loading indicators and buttons are disabled while upload is ongoing
