### ISSUE TITLE
Fix code scanning alert - Server-side request forgery

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#3631]
@fontanierh what are the expectations on these URLs? Can we enforce they are on googleapis.com ?

Tracking issue for:
- [ ] https://github.com/dust-tt/dust/security/code-scanning/15

**Comment by spolu** [comment]
Took a stab here: https://github.com/dust-tt/dust/pull/3632

**Comment by fontanierh** [comment]
This tool is quite powerful ! will TAL and try to fix the warnings on yout fix pr.

> what are the expectations on these URLs? Can we enforce they are on googleapis.com ?

I think we can, will dig further
