### ISSUE TITLE
Move "New block" and "Run" CTAs to the bottom 

### ISSUE THREAD

**Issue by ngarnier** [dust-tt/dust#37]
As you build your app and start stacking blocks, having to scroll back up each time you want to add a new block or run the app doesn't feel like the best experience.

Another alternative could be to keep the top sticky (might make sense to navigate to datasets too?). Happy to try a PR if you think it makes sense.

**Comment by spolu** [comment]
Thanks! Was about to work on this one :)

I think, as a starter, I'll just show run/block at the end when there is more than 2 blocks
