### ISSUE TITLE
[Caloris] Slugify table name

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#3760]
We should slugify table name and use lowercase with underscore. 
Example:
```
Slack usage per workspace id - [VIEW] Slack missing membership per workspace
```

Should become:
```
slack_usage_per_workspace_id_view_slack_missing_membership_per_workspace
```

**Comment by flvndvd** [comment]
@fontanierh playing a bit with GSheet, should we consider doing the same thing for the headers?

**Comment by fontanierh** [comment]
This is done AFAIK
