### ISSUE TITLE
[Caloris] Properly bubble up SQLite errors

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#3791]

**Comment by fontanierh** [comment]
I think this should be widened as "bubble up SQL error in SQliteWorker HTTP response". The thing is, we log the error on sqlite worker, but the actual error response from SQLite is not being forwarded to core in the HTTP response (so it makes debugging harder).

**Comment by flvndvd** [comment]
Is this partially fix with this [PR](https://github.com/dust-tt/dust/pull/3794) @fontanierh ?

**Comment by fontanierh** [comment]
Closing this. Situation is good enough for now (easy for us to see the sqlite errors)
