### ISSUE TITLE
[Meru - AB] [Nice-to-have] Sharing Button - Link to assistant

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#3857]
As per [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4743-20569&mode=design&t=gf3MRjZJaUE3ERWG-0) 

We want a copy link button in the sharing dropdown that will redirect to the assistant gallery with the assistant drawer being opened

2 tasks here:
- Ability to link to the assitstant gallery with a drawer open
- add the button / link in the sharing dropdown

**Comment by philipperolet** [comment]
Editing title to reflect framing in which this is considered a Nice-to-have

**Comment by philipperolet** [comment]
Oh hadn't seen you took it already 👍

**Comment by spolu** [comment]
Reverted due to regression on the gallery close button
https://github.com/dust-tt/dust/pull/3902

Will re-revert tomorrow
