### ISSUE TITLE
[Caloris] Notion page + link from app to explain Query Tables

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#3879]
cc @fontanierh created this to track in Caloris

**Comment by fontanierh** [comment]
the page is here :
https://dust-tt.notion.site/Table-queries-on-Dust-2f8c6ea53518464b8b7780d55ac7057d?pvs=25

Not sure where to link it yet

**Comment by spolu** [comment]
Let's slap a button somewhere in the description of the action in the assitsant builder as first itention

**Comment by fontanierh** [comment]
Sounds good, on it
