### ISSUE TITLE
[Meru AB] Action screen: data selection display

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#3896]
When selecting data sources, show them similarly to what is done in connections.

See [figma details](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4777-2737&mode=design&t=uAjDMEbXPunWZvLv-4)
 and part 3 of issue [here](https://github.com/dust-tt/decisions/issues/164#issue-2134311899)

**Comment by PopDaph** [comment]
Announcement: https://dust4ai.slack.com/archives/C05BUSJQP5W/p1709649627493159


Pull Requests: 
https://github.com/dust-tt/dust/pull/4065
https://github.com/dust-tt/dust/pull/4031
https://github.com/dust-tt/dust/pull/4044
https://github.com/dust-tt/dust/pull/4050
https://github.com/dust-tt/dust/pull/4083
https://github.com/dust-tt/dust/pull/4084
https://github.com/dust-tt/dust/pull/4118
https://github.com/dust-tt/dust/pull/4119
https://github.com/dust-tt/dust/pull/4122
https://github.com/dust-tt/dust/pull/4125
https://github.com/dust-tt/dust/pull/4132
https://github.com/dust-tt/dust/pull/4134
https://github.com/dust-tt/dust/pull/4136
https://github.com/dust-tt/dust/pull/4138
https://github.com/dust-tt/dust/pull/4139
