### ISSUE TITLE
[Nice to have] instructions suggestions: suggest existing assistants

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#3898]
Following the lines of #3876

- Dust app able to detect whether there is/are assistant(s) closely matching the instructions
- If yes, use the 3rd suggestion box to display "Look at @aaa or @bbb for inspiration" (clicking on handle displays assitant detail view)

**Comment by philipperolet** [comment]
@Duncid ok for you ? covers indirectly the case of an existing assistant that already actually does what I want

**Comment by Duncid** [comment]
Not sure I understand.
IMO should be part of the instruction suggestion and not split out.

**Comment by philipperolet** [comment]
Yes, I agree, this is why I wrote "use the 3rd suggestion box to display..."
The description here is a proposition on how to have the "existing assistant suggestion" and the "advice on writing suggestions" mix, under the same "Suggestions" heading; wdyt about it? if not good, how would you do differently

**Comment by philipperolet** [comment]
Closing, since nice-to-have, can be rescoped later as discussed IRL with @spolu
