### ISSUE TITLE
[Upsert Queue] GCS client for `front` + Bucket creation

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#3945]
We need a GCS interface in typescript for the upsert queue that we will likely use as well for content fragment v2.

We already have the SERVICE_ACCOUNT that has access to our GCS in front secrets.

We'll create 1 new bucket and make sure we add access to it to the service account (production and test):

- [x] Create bucket `dust-upsert-queue-prod`
- [x] Create bucket `dust-upsert-queue-test`
- [x] Make sure service account have access to it (prod and dev)
- [x] Add import for GCS library in typescript and test it
- [ ] add secret `DUST_UPSERT_QUEUE_BUCKET`

**Comment by spolu** [comment]
Actually we already have the Storage import available.

**Comment by spolu** [comment]
Created https://console.cloud.google.com/storage/browser/dust-upsert-queue;tab=objects?hl=en&project=or1g1n-186209&prefix=&forceOnObjectsSortingFiltering=false with no retention, no versioning, unifrom access, multi region, public access prevention

**Comment by spolu** [comment]
```
gsutil iam ch serviceAccount:dust-api-svc@or1g1n-186209.iam.gserviceaccount.com:roles/storage.objectAdmin gs://dust-upsert-queue-prod
```
```
gsutil iam ch serviceAccount:dust-api-svc-test@or1g1n-186209.iam.gserviceaccount.com:roles/storage.objectAdmin gs://dust-upsert-queue-test
```

**Comment by spolu** [comment]
Added `export DUST_UPSERT_QUEUE_BUCKET=dust-upsert-queue-test ` to dev setup

**Comment by lasryaric** [comment]
Thanks.
