### ISSUE TITLE
[Meru] [New Pricing] Remove the Free plan

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4008]
As per https://github.com/dust-tt/decisions/issues/178, the Free plan must be removed.

[Figma is here](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=2654-17224&mode=dev).

That means:

- [x] Removing the free plan from the pricing page.
- [x] Set the subscription at `trialing` when it starts in our DB.
- [ ] Remove free plan from documentation: remove from the helper prompt in `front/prompt/global_agent_helper_prompt.md`
- [x] Add the `Try it for free for 2 weeks` right above the `Start now` button.
- [ ] If a user arrives on a free workspace url `dust.tt/w/[wId]`, display the subscription page.
- [x] The subscription page should have a "close" button if the user is part of another paying workspace.
- [ ] Remove all mentions of the free plan for external documentation.
- [x] Find out who is going to be impacted by this change (especially users of the Dust apps who are not interested in using the assistants). For non apps users, it should be fine since they don't have access to connected data sources and can only send up to 50 messages. [There is a subtask for that here](https://github.com/dust-tt/dust/issues/4012).

### Screenshots

![Image](https://github.com/dust-tt/dust/assets/358965/c9c0f5a4-e03c-44d2-9fe9-9f69f07894ce)
![Image](https://github.com/dust-tt/dust/assets/358965/1ed0f6ad-5639-4b0d-a8f7-e4331644fd12)

# Dependencies

Depends on: https://github.com/dust-tt/dust/issues/4012 and https://github.com/dust-tt/dust/issues/4022

**Comment by spolu** [comment]
For existing users we'll likely grand-father their account on a plan that let them be logged in and browse the app but maybe prevent them some actions.

**Comment by spolu** [comment]
Depends on #4263

**Comment by spolu** [comment]
@lasryaric any update on the timeline and events for plans with free trial and their cancellation before the end of the free trial?

Also what is the first charge? Is it for 1 month or for 2 weeks?

**Comment by lasryaric** [comment]
# Timeline

## No cancellation
- Free trial starts for 14 days.
- User is not charged until the end of the free trial.
- User is charged at the end of the free trial for the next month, like if the user had just subscribed to a plan without a trial period, the day of the free trial is over.


## Cancellation during the free trial
- The Stripe default is to keep the user on the plan, as a valid, but cancelled plan, until the end of the free trial.
- There is a button on the Stripe user's dashboard to allow the user to renew or cancel.
- Renewal would put it back on the free trial, as if the user never cancelled.

# Charges

The first charge is an invoice of $0.00 under the free trial

**Comment by spolu** [comment]
Cool, we likely want to change the wording on the subscriptions page to make it clearer that cancellations happen in the stripe dashboard

What happens if the subscriptions ended and the user wants to upgrade? What system takes care of skipping the free trial in that case?

**Comment by lasryaric** [comment]
> What happens if the subscriptions ended and the user wants to upgrade? What system takes care of skipping the free trial in that case?

We can just check in the database if we ever had a subscription for a given workspace id, we can set trialDays to 0 when talking to Stripe. Good catch.
