### ISSUE TITLE
[Meru] [New Pricing] Implement the confetti page of the subscription flow

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4010]
The confetti page in the subscription flow is modeled [here on Figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4850-20236&mode=dev).

![Image](https://github.com/dust-tt/dust/assets/358965/f2b961b2-4cb6-4a7a-bde8-af4c5ffaf63e)

@Duncid pointed to a library to help with that, [here](https://alampros.github.io/react-confetti/?path=/story/props-demos--knobs) it is.

Check [framing](https://github.com/dust-tt/decisions/issues/178) for more details

**Comment by Duncid** [comment]
Yes

**Comment by Duncid** [comment]
(cc @gabhubert https://dust4ai.slack.com/archives/C050A0S2Z7F/p1709741244289949)
