### ISSUE TITLE
Export an app to code in a language of your choice

### ISSUE THREAD

**Issue by mholtzhausen** [dust-tt/dust#402]
I find this platform a fantastic way to iterate over a process.

Now I wish I could generate code for such a dust app, so that I can have more fine-grained code control over the flow.

Suggested starting languages:
 - Python
 - Rust
 - Golang
 - Node / Deno

I know this is a tall order 😎

**Comment by spolu** [comment]
Thanks @mholtzhausen! That's an interesting idea indeed. That being said, not our current priority to be perfectly transparent as we build towards providing customizable but packaged applications to the enterprise on top of their internal data (through data sources).

**Comment by spolu** [comment]
Closing as our current product direction in that respect is reliance on our API :+1:
