### ISSUE TITLE
[Meru][Pricing] Free trial on pro plan

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4022]
# Description

Enable a 2 weeks free trial on the PRO plan.

- The user must go through Stripe
- Stripe must ensure the credit card is valid and "chargeable" (as much as we can validate that without actually charging it).

# Reference

Look at the business rules section on the framing: 
https://github.com/dust-tt/decisions/issues/178

# Dependencies

Depends on: 
https://github.com/dust-tt/dust/issues/4008

**Comment by lasryaric** [comment]
Emails are done, see this doc:
https://www.notion.so/dust-tt/Design-Doc-pro-plan-transactional-mailing-5be13d62922d4814b3c7d203df74fe62

**Comment by lasryaric** [comment]
All missing emails are now configured to be sent directly by Stripe.

Free trial days can be updated in the database via poke -> plans -> `PRO_PLAN_SEAT_29`

**Comment by lasryaric** [comment]
> Free trial days can be updated in the database via poke -> plans -> PRO_PLAN_SEAT_29

When releasing.

**Comment by flvndvd** [comment]
@lasryaric based on https://github.com/dust-tt/dust/pull/4279, can you make sure to create the subscription in our DB with status = "trialing", please?

**Comment by lasryaric** [comment]
The only thing needed fo this task is to set the free trial days on the plan on Poke at release time. Closing this task.
