### ISSUE TITLE
[Meru][Onboarding] Join a workspace

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4026]
# Description

Adjust the existing "Join a workspace" / "Create a workspace" workflow to comply with the look and feel of the new design.

On the [Figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=3928-157934&mode=dev), we are talking about the following **4 screens**:

![Image](https://github.com/dust-tt/dust/assets/358965/ecd9897c-406d-4697-9f80-def49f3b4035)

**Comment by flvndvd** [comment]
Has only the subscription part of the "Admin idle" flow been modified from the current version, @lasryaric?

**Comment by Duncid** [comment]
Hey @flvndvd !
My naming of frames was not very good, so I don't understand your questions.
Updated the frame naming here:
https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=1845%3A45444&mode=design&t=8ijdY9y53WavQJH3-1

Also you can comment directly.

**Comment by flvndvd** [comment]
@Duncid those 4 screens have been updated, if you wanna take a look, here are some links for you to test:
- Join workspace => https://dust.tt/w/0ec9852c2f/join?t=test
- Welcome => https://dust.tt/w/0ec9852c2f/welcome
- **DO NOT CLICK ON CREATE WORKSPACE!!!** Workspace already exist => https://dust.tt/no-workspace?flow=no-auto-join
- **DO NOT CLICK ON CREATE WORKSPACE!!!** Revoked from workspace => https://dust.tt/no-workspace?flow=revoked

**Comment by spolu** [comment]
Ooc what happens if we click? (Just to understand as some users will land here and will click eventually :-))

**Comment by flvndvd** [comment]
Actually it does not do anything and throws an error since the user already has a workspace.

**Comment by spolu** [comment]
Roger that :+1:

**Comment by spolu** [comment]
Note I got a 500 on  https://dust.tt/no-workspace?flow=no-auto-join

**Comment by flvndvd** [comment]
I guess you are connecting with your GitHub account ([log](https://app.datadoghq.eu/logs?query=%40panic%3Atrue%20&agg_m=count&agg_t=count&cols=host%2Cservice&event=AgAAAY4200c2v-uK1QAAAAAAAAAYAAAAAEFZNDIwMVFOQUFCTHFkbWV5WHAwSUFBRAAAACQAAAAAMDE4ZTM2ZDMtNDdmZi00ZDU4LWI3NWEtMDBlMjE3OTIzYWVi&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&sort=time&source=monitor_notif&spanID=230593063926245247&storage=hot&stream_sort=desc&view=spans&viz=stream&from_ts=1710315008000&to_ts=1710316808000&live=false)). Those pages should not be access, we should probably add a check to prevent people from accessing them.
