### ISSUE TITLE
[Meru] Invite by email

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4055]
# Description

Implement / make sure the invite by email flow has the same look and feel as the one designed on [Figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=3928-157802&mode=dev).

Email copy and design needs to be adjusted too.

- [x] Design the emails and make them functionals.
- [x] Design the landing page once the user clicks on the email.
- [x] Make sure the invite flow works.

# Screenshots

![Image](https://github.com/dust-tt/dust/assets/358965/478e6386-51c2-48f8-8746-53dbc4626f0b)

**Comment by flvndvd** [comment]
@Duncid can you provide a design for the email templates?

**Comment by spolu** [comment]
@flvndvd do you confirm the screens are done?

As for the emails I think it's lower priority than many other things. Feel free to drop IMHO

**Comment by flvndvd** [comment]
Yep screens are done.

**Comment by flvndvd** [comment]
Invite template is done as well and live.
