### ISSUE TITLE
Google Drive Webhooks: stable fix for better renewal

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#4162]
As discussed with @lasryaric and @spolu IRL; related [discussion](https://dust4ai.slack.com/archives/C05F84CFP0E/p1709651440495549)

**Comment by philipperolet** [comment]
@lasryaric do you plan to have a look? do you have time?

**Comment by spolu** [comment]
sitrep?

**Comment by lasryaric** [comment]
Still planning to work on it, next in my list.

**Comment by lasryaric** [comment]
Done. PR is [here](https://github.com/dust-tt/dust/pull/4699). Closing
