### ISSUE TITLE
Add Account Linking flow

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#4216]

**Comment by spolu** [comment]
What needs to be done here? Happy to tackle to close the column

**Comment by flvndvd** [comment]
See https://dust4ai.slack.com/archives/C0512MMRACQ/p1710228327699549?thread_ts=1710141236.277919&cid=C0512MMRACQ.

**Comment by spolu** [comment]
Won't do

Context: https://dust4ai.slack.com/archives/C050SM8NSPK/p1710321759823659
