### ISSUE TITLE
[Content Fragment] Start writing all content fragment to GCS + migrate

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#4240]
Based on #4239 start writing content fragment original doc + text if appropriate to GCS (in addition to `url`)

This requires creating a new bucket + dev bucket on GCS. Bucket must be private (we would intermediate the download when we build it)

sourceUrl is:
- `file_attachment`: the GCS URL of the uploaded file (internal GCS only not accessible directly publicly) 
- `slack_thread_content`: the slack thread URL

Have the product still rely on `url` and `content` for now

Migrate existing content fragments:

When `url` is available copy it to `sourceUrl`
Upload `content` to GCS and update `textUrl` (all content fragment for now are presented to the model and have a textUrl)

For `file_attachment` we won't have `sourceUrl` for these old content fragments

Note on `textUrl` and `sourceUrl`

When the content is transformed to extract text (eg PDF) we have different textUrl and sourceUrl. When it's not (eg .md or .txt or future .csv) we use the same Url. We will rely on textUrl non nullity to decide whether to render the content for the model.

We also want to record `textByte` and `textTokens` . Both are set only if `textUrl` is no null.

As an example if we support uploading binary files that we can't convert to text, all these fields along with `textUrl` would be null.

Examples:
|type|mime-type|textUrl|
|--|--|--|
|file_attachment|text/plain|is equal to sourceUrl|
|file_attachment|application/pdf|specific one with dump of text|
|file_attachment|application/pdf|specific one with dump of text|
|slack_thread_content|text/plain|specific one with copy of data|

In the future

|type|mime-type|textUrl|
|--|--|--|
|file_attachment|application/mpeg4|specific one with transcript|
|file_attachment|text/csv|equal to sourceUrl|

**Comment by spolu** [comment]
Depends mostly on #4239 but can be started without it

**Comment by philipperolet** [comment]
it would be nice to enforce the constraint that `sourceUrl` is not null
We could for instance migrate old file_attachment to  constant url of a plain text file in GCS saying that the content fragment is unavailable. We can use the string (of the url) to distinguish whether the attachment is available or not

**Comment by philipperolet** [comment]
Naming schemes in GCS:
`uploadToGCS`: bucket/wid/cid/raw/normalized_title
`storeToGCS`: bucket/wid/cid/text/normalized_title

**Comment by philipperolet** [comment]
> it would be nice to enforce the constraint that `sourceUrl` is not null, since from now on we want all new content fragments to have one We could for instance migrate old file_attachment to constant url of a plain text file in GCS saying that the content fragment is unavailable. We can use the string (of the url) to distinguish whether the attachment is available or not

Actually not sure about that. Typing unavailability via null also have its upsides

**Comment by spolu** [comment]
A PDF attachment can't have a sourceURL right? (at least I think that was my thinking). And `null` means just that.

**Comment by spolu** [comment]
(the purpose of sourceUrl is to got back to the original data, and in the case of a PDF, there is no such thing)

**Comment by spolu** [comment]
> uploadToGCS: bucket/wid/cid/raw/normalized_title
> storeToGCS: bucket/wid/cid/text/normalized_title

What is normalized_title?

**Comment by philipperolet** [comment]
> A PDF attachment can't have a sourceURL right? (at least I think that was my thinking). And null means just that.

From what I had understood, we download the PDF on GCS and the GCS URL is the sourceUrl; did I misunderstand?

**Comment by philipperolet** [comment]
> What is normalized_title?

just a quick way of saying we'll check title does not contains characters that are unsuitable for GCS object names

**Comment by spolu** [comment]
Yes sorry I do agree with that. null sourceUrl are for past attachment :+1:

**Comment by spolu** [comment]
The `null` type can give us a chance to implement a fallback in the product but we can also link to a text version for legacy file_attachment

I'll let you figure out what's best :+1: 

Sorry for the confusion (had to bring back context in RAM :))

**Comment by spolu** [comment]
> just a quick way of saying we'll check title does not contains characters that are unsuitable for GCS object names

I'd go UUID here 

bucket/wid/cid/UUID_or_hash_of_document/{raw|text} ?

**Comment by philipperolet** [comment]
> The `null` type can give us a chance to implement a fallback in the product but we can also link to a text version for legacy file_attachment
> 
> I'll let you figure out what's best 👍
> 
> Sorry for the confusion (had to bring back context in RAM :))

NP, perfectly understand. Ok will decide

**Comment by philipperolet** [comment]
> > just a quick way of saying we'll check title does not contains characters that are unsuitable for GCS object names
> 
> I'd go UUID here
> 
> bucket/wid/cid/UUID_or_hash_of_document/{raw|text} ?

Ack, good for me

**Comment by philipperolet** [comment]
Another topic: we allow posting content fragments via our public API (v1)

Currently, null url is `allowed` and we only have parsed text content in that case. We can either leave as is, and allow null sourceURL --- then null sourceURL becomes not only legacy docs but also content fragments posted without URL

Or force sourceURL not null and put the responsibility on the consumer of the API to set something meaningful 

Will also figure it out but if you have an opinion, glad to hear it

**Comment by spolu** [comment]
I think from an API perspective it’s better to allow null url because as a user I might just want to push text 👍

**Comment by philipperolet** [comment]
Will allow `null` sourceUrl for now. The invariant: null = we don't have access to the original document

**Comment by philipperolet** [comment]
Our messages crossed. null it is

**Comment by spolu** [comment]
\o/

**Comment by philipperolet** [comment]
> > > just a quick way of saying we'll check title does not contains characters that are unsuitable for GCS object names
> > 
> > 
> > I'd go UUID here
> > bucket/wid/cid/UUID_or_hash_of_document/{raw|text} ?
> 
> Ack, good for me

Gave thought about this
- The raw upload part is better done after the content fragment and conversations are stored (since better to be able to tie it to conversation which only gets an sId after it's created)
- so, we can directly use the content fragment sId here

**Comment by philipperolet** [comment]
Added thoughts:
- raw upload => not critical to the conversation, better happen async from creating a content fragment (since a PDF may be large (and if it fails the conversation can continue))
- text upload => critical to the conversation, should happen at creation of content fragment
See incoming PR for details

**Comment by philipperolet** [comment]
Sliced this in 3:
- this card => correctly filling sourceUrl + uploading raw content to gcs when needed
- card #4399 => filling textXXX fields
- card #4400 => migrating old fragments

**Comment by philipperolet** [comment]
> > The `null` type can give us a chance to implement a fallback in the product but we can also link to a text version for legacy file_attachment
> > I'll let you figure out what's best 👍
> > Sorry for the confusion (had to bring back context in RAM :))
> 
> NP, perfectly understand. Ok will decide

=> after some thought, ending up with => link to a text version for legacy, or in general when no URL is given

Both options had upsides & downsides. This one has the upsides of:
- always allowing 'download' from front
- faster to ship
with limited downsides
