### ISSUE TITLE
On google drive file sync failure, do not resync all already-synced files from the same activity

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#4247]
Split from #518

When an incremental sync or syncFiles activity fails on one file, resyncing files that were previously correctly synced causes various issues, including potentially blocking the sync while it could go on (#518) and / or repeated quota issues (#521)

To be adressed by https://github.com/dust-tt/dust/pull/4246

**Comment by flvndvd** [comment]
Fix has been deployed.
