### ISSUE TITLE
[Meru] Frame fair usage of the free trial

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4263]
# Conclusion

- Up to 5 workspace members
- 25 messages / day / workspace
- There must be a clear call to action in the UI to send the user through the upgrade flow.
- When the user upgrade during a free trial, the free trial must be disabled from the subscription object (setting `subscription.trial_end=now` is the way to go apparently. Feel free to double check).

# Initial discussion

Since free trial can open the door to a "unlimited usage of Dust" for the duration of the free trial, we need to implement a fair usage policy.

Here is a suggestion:
- maximum 5 workspace member during the free trial
- A maximum number of agent messages for the workspace over a 24 hours rolling window.

After that, the user is required to upgrade their subscription, to do so, we can call:
```
  await stripe.subscriptions.update(stripeSubscriptionId, {
    trial_end: "now",
  });
```

**Comment by lasryaric** [comment]
@Duncid seems reasonable to you as a fair usage?

**Comment by spolu** [comment]
That means we have a new button on the subscription page to cover that action right?

Let’s do 25 messages per 24h ?

We probably want to give some love to the rate limit error UX or at least check it makes it clear that the user can accelerate the end of free trial 👍

**Comment by lasryaric** [comment]
>We probably want to give some love to the rate limit error UX or at least check it makes it clear that the user can accelerate the end of free trial 👍

Yes UX will need some love there because this is potentially the perfect lead we want to convert.

**Comment by lasryaric** [comment]
Updated the description with :
```
# Conclusion
- Up to 5 workspace members
- 25 messages / day / workspace
- There must be a clear call to action in the UI to send the user through the upgrade flow.
- When the user upgrade during a free trial, the free trial must be disabled from the subscription object (setting subscription.trial_end=now is the way to go apparently. Feel free to double check).
```

**Comment by spolu** [comment]
LGTM

**Comment by flvndvd** [comment]
Can we also disable "Auto-join" for those free trials so we can have one single place to add members?

**Comment by lasryaric** [comment]
> Can we also disable "Auto-join" for those free trials so we can have one single place to add members?

It's a bit sad to disable this feature during the free trial I think :/

**Comment by flvndvd** [comment]
> > Can we also disable "Auto-join" for those free trials so we can have one single place to add members?
> 
> It's a bit sad to disable this feature during the free trial I think :/

Ok I have a way to keep the feature for trial plan and block at login.

**Comment by flvndvd** [comment]
PR for 👇  is here: https://github.com/dust-tt/dust/pull/4280
> Up to 5 workspace members

**Comment by flvndvd** [comment]
PR for 👇 is here: https://github.com/dust-tt/dust/pull/4293
> 25 messages / day / workspace
