### ISSUE TITLE
[Meru] [New Pricing] release of new pricing timeline.

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4269]
# Goal

The goal of this doc is to define in which order we should release all pieces of the new pricing.

# Already deployed

The following tasks have already been deployed:
- #4024
- #4026 
- #4053 
- #4010 

# Remaining
 
1.  Release free trial fair usage as this has no impact on existing users (nobody is under a free trial).
2.  (deprecated) [Place holder to figure out what to do with the existing users of dust-apps]
3.  (deprecated) [Place holder to manage comms around the free plan and users of dust-apps only]
4. Release the free trial configuration (done on Poke, all emails discussed in #4022 are already live and sent by Stripe)
5. Plan on releasing #4008 right after the setup of the free trial on Poke

**Comment by lasryaric** [comment]
@gabhubert @spolu I would need guidance on 2. and 3. of the `Remaining` section:
```
2. [Place holder to figure out what to do with the existing users of dust-apps]
3. [Place holder to manage comms around the free plan and users of dust-apps only]
```

**Comment by spolu** [comment]
> [Place holder to figure out what to do with the existing users of dust-apps]

No change for now we can tackle this independently.

> [Place holder to manage comms around the free plan and users of dust-apps only]

As a consequence nothing :)
