### ISSUE TITLE
[Meru] [New Pricing] Grandfathering of existing users

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4270]
Make sure that all workspaces created before a specific date will be free forever, with the current free plan limits imposed on them.

Technical implementation TBD.

**Comment by spolu** [comment]
The main question here is whether we have a free plan object in DB or not and whether the free plan has a special role or not.

**Comment by spolu** [comment]
The problem is that we don't have a subscription (link between plans and workspaces) for existing free users, logic happens here: https://github.com/dust-tt/dust/blob/main/front/lib/auth.ts#L517-L559

**Comment by lasryaric** [comment]
>Add logic to create a Subscription object for all workspaces as they get created, that put them in the current FREE_TEST_PLAN

Ok, so this should be removed when we remove the free test plan.

Plan looks good to me.

**Comment by flvndvd** [comment]
Given that other pieces depend on this PR, I'm wondering if we could not be more aggressive 🤔. If we were to start by doing:

> Add logic to create a Subscription object for all workspaces as they get created, that put them in the current FREE_TEST_PLAN

We could probably infer in the `Authenticator` that if there is no subscription, then it's a `FREE_TEST_PLAN` . We can always backfill later.

**Comment by spolu** [comment]
This is the role of lib/auth.ts not the middleware. The idea here is to prepare the `FREE_NO_PLAN` and be ready to start using it. This reduces the risk of the final switch as we will have derisked the use of a grand-fathered `FREE_TEST_PLAN` entirely IMHO.

We could keep lib/auth.ts as is (return FREE_TEST_PLAN) but that adds more risk down the road so I'd rather spray it as much as possible.
