### ISSUE TITLE
[Meru] [New Pricing] Implement fair usage of the free trial.

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4271]
Framing here:
#4263

**Comment by flvndvd** [comment]
> # Conclusion
> - Up to 5 workspace members
> - 25 messages / day / workspace
> - There must be a clear call to action in the UI to send the user through the upgrade flow.
> - When the user upgrade during a free trial, the free trial must be disabled from the subscription object (setting subscription.trial_end=now is the way to go apparently. Feel free to double check).

1. is done in https://github.com/dust-tt/dust/pull/4280
2. is done in https://github.com/dust-tt/dust/pull/4293
