### ISSUE TITLE
[Meru] [New pricing] Implement middleware to check that the user has a valid subscription for pages of the app.

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4284]
All pages of the app (but a few, like the subscribe and settings pages) needs to be gated by a valid subscription,  we need to add a new flag to the `requireSubscription` to `withDefaultUserAuthRequirements` in `front/lib/iam/session.ts` and mark all to be gated pages with that flag set to true.

**Comment by spolu** [comment]
Will use plan.limits.canUseProduct once #4290 lands
