### ISSUE TITLE
Unable to run or deploy an app after revert

### ISSUE THREAD

**Issue by DippyArtu** [dust-tt/dust#429]
Hi!

This issue concerns AppID `381cd6bee4`

After reverting to an older version of an app, I was unable to revert back to current. It is also not possible to run the app and any modifications to the app do not effect the runs. Cloning the app doesn't solve the issue either. The API works fine, but it seems to be impossible to modify the app.

I was able to resolve only by creating a new app and copying the broken one.

Below is the screenshot of my app:

![Screenshot 2023-05-12 at 01 13 05](https://github.com/dust-tt/dust/assets/54483417/312d397e-4d90-422e-b0ed-36e9d2823ded)

Thanks!

**Comment by spolu** [comment]
Thank you @DippyArtu 

@fontanierh looks like the block `data EXAMPLES` is wrongly handled. Assigning the issue to you
