### ISSUE TITLE
[Meru][New Pricing] Should we add a "enterprise / contact us" on the paywall page?

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#4300]
@Duncid what do you think about enterprise who would like to "contact us" but are landing on the paywall page?

Should we add an enterprise contact us here?

cc @spolu who inquired about that.

# screenshot of the paywall page as of today
![Image](https://github.com/dust-tt/dust/assets/358965/05900b64-b63d-4abd-8054-70dd535adc6d)

**Comment by Duncid** [comment]
I've thought of that possibility when designing this.

Hypothesis here is that at this point the user has already seen both options and picked one, therefore would be redoundant.

If we were to create a generic entry point ("start with dust") we'd probably need to ask at some point (pro or enterprise).

**Comment by lasryaric** [comment]
Ok sounds good to me. @spolu WDYT?

**Comment by spolu** [comment]
SGTM

Only caveat: Enterprise user who contacter us. We agreed on a pilot. They will need to create an account and will lend on that page. Maybe we need a special link so that their account gets flagged + they land on something that tells them to wait for their workspace to be upgraded (+ they always land on it thanks to the flag)

This is fine-tuning but likely something we want earlier than later

**Comment by Duncid** [comment]
> SGTM
> 
> Only caveat: Enterprise user who contacter us. We agreed on a pilot. They will need to create an account and will lend on that page. Maybe we need a special link so that their account gets flagged + they land on something that tells them to wait for their workspace to be upgraded (+ they always land on it thanks to the flag)
> 
> This is fine-tuning but likely something we want earlier than later

Oh.
It's pointing to another problem IMO (we don't want an enterprise to subscribe via the "pro" funnel.
We need a way to invite companies to create a Enterprise account on pilot.

**Comment by spolu** [comment]
> It's pointing to another problem IMO (we don't want an enterprise to subscribe via the "pro" funnel.

Yes that's my point.

**Comment by Duncid** [comment]
So, Dust people should have a way to create an invite link the enterprise admin will follow to create the company with the enterprise plan.

**Comment by spolu** [comment]
Related: https://dust4ai.slack.com/archives/C050A0S2Z7F/p1710497585425669

**Comment by lasryaric** [comment]
Closing this task and concluding "no" for this climb. Thanks.
