### ISSUE TITLE
[Meru] [Templates] New Creation Flow page

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#4372]
the Templates project introduces a new full page modal right before creating an assistant.
The page layout and UI is well described in the making issue: https://github.com/dust-tt/decisions/issues/179

The goal of this task is to implement the UI and layout of the page, including the sticky category list, the side modal for the template details, the search bar and the list of templates

Blocked on https://github.com/dust-tt/dust/issues/4373

**Comment by flvndvd** [comment]
Shipped. @Duncid feel free to open new issues with Q&A items.
