### ISSUE TITLE
[Meru] [Templates] Assistant Builder presets

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#4375]
Assistant builder templates come with pre-sets for some configurations as defined in https://github.com/dust-tt/dust/issues/4373.
The goal of this task is to automatically pre-fill the assistant builder with the right values for the various fields defined in the template

blocked on https://github.com/dust-tt/dust/issues/4373

**Comment by flvndvd** [comment]
Done in https://github.com/dust-tt/dust/pull/4486.
