### ISSUE TITLE
[Meru] [Templates] Improve template admin CRUD tooling

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#4462]
As per https://github.com/dust-tt/dust/pull/4457, we have rudimentary tooling to create Templates.

We'll need to improve this with something that allows to:
- [x] view all templates
- [x] delete templates
- [x] edit templates
- [x] allow setting a preset description
- [x] change the visibility status of a template
- [ ] ~maybe sync from another resource such as notion~. -> won't do

- [x] Background Color field should give an example of color and explain we expect a tailwind bg color css class.
- [x]  I think we need a "status" (published / draft)

**Comment by flvndvd** [comment]
Implemented:
- view all templates
- edit templates
- allow setting a preset description

**Comment by fontanierh** [comment]
I guess we can close @flvndvd  ?

**Comment by flvndvd** [comment]
We are still missing the delete and change visibility. Will take a stab at those tomorrow.

**Comment by PopDaph** [comment]
Also from this Framing Issue: https://github.com/dust-tt/decisions/issues/179#issuecomment-2050041199. 
We need: 

- Background Color field should give an example of color and explain we expect a tailwind bg color css class.
- I think we need a "status" (published / draft)

(From the "No Brainers > UI Fixes > Poké" section)

**Comment by PopDaph** [comment]
✅  Delete template is done: https://github.com/dust-tt/dust/pull/4760

**Comment by PopDaph** [comment]
✅  change the visibility status of a template https://github.com/dust-tt/dust/pull/4761

**Comment by PopDaph** [comment]
✅  Background Color field should give an example of color and explain we expect a tailwind bg color css class. https://github.com/dust-tt/dust/pull/4762

**Comment by PopDaph** [comment]
Closing! 🙏
