### ISSUE TITLE
Local installation issues

### ISSUE THREAD

**Issue by Matthieu24** [dust-tt/dust#4464]
I've tried to install it locally, docker takes Qdrant, Postgresql and Redis but not the front end, when I run it next to it it tells me that @dust-tt/types is missing, I install it but the dist folder is missing.
Can you tell me how to install it?

**Comment by spolu** [comment]
HI @Matthieu24 

We do not support local deployments anymore unfortunately. We're open-source out of transparency and as a way to communicate more efficiently with our users.

I invite you to use our hosted version at https://dust.tt
