### ISSUE TITLE
[Meru] [Templates] Templates view categories behavior

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#4593]
When clicking on a category I'd like the templates to be filtered by that category.
When selecting 2 I see templates from both categories

cc @Duncid OK with you?

**Comment by Duncid** [comment]
I would prefer to stick with current behavior of scrolling.
I think it does a better job at serendipity.

**Comment by spolu** [comment]
Agreed with serendipity but I'd make the argument that having a selected status with scrolling is a bit inconsistent + when trying to find engineering use-cases I felt a bit confused.

**Comment by Duncid** [comment]
> when trying to find engineering use-cases I felt a bit confused, esp as we have no garantee that we land at the top of the screen

I'll keep that in mind.
I think can create a visual hint pretty easily.

**Comment by PopDaph** [comment]
https://github.com/dust-tt/dust/pull/4745
