### ISSUE TITLE
[Multi-Actions] Move `instructions` out of `AgentGenerationConfiguration` up to `AgentConfiguration`

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#4596]
Reference: https://www.notion.so/dust-tt/Multi-Actions-Technical-Proposal-662aa8afbc584f4285d89becc0a6417b

**Comment by PopDaph** [comment]
### Working plan (to be adapted following discussion)

- [ ] Add a new 'instructions' nullable field to `AgentConfiguration`. 
- [ ] Shadow-write on this new field.  
- [ ] Write a script to fill it for all, run the script.
- [ ] Call the new field from `AgentConfiguration` and stop relying on the one from `AgentGenerationConfiguration`.

**Comment by spolu** [comment]
Generation becomes a tool/action indeed and we have only one set of instructions on the top level agent configuration 👍

**Comment by PopDaph** [comment]
@spolu got it, but then generation action still have their own optional prompt right, maybe optional? 🙏

**Comment by spolu** [comment]
Nope no prompt

**Comment by fontanierh** [comment]
That part is unclear for now right ? We may or may not want tool-specific instructions

**Comment by spolu** [comment]
Maybe in the future but for now tools will only have an optional description likely but that will be handled uniformly for all actions in a later task 👍

**Comment by PopDaph** [comment]
OK so please correct me if I'm wrong 🙏🏻 

### About the Task 

-> The instructions are now at the `AgentConfiguration` level and they are kind of the "script of the agent". 
-> Generation is just an action that say: generate something with this model and this context.
-> Actions will have an optional description to help the model identify the valid action to handle in which order (but this is not part of this task).

### About the Generation Action

On the UI: 
- **Today** we support exactly one Generation action.
- **Tomorrow** we want to support one or none. If no generation action, there will be no text generated. 
- **Tomorrow ++** we will support multiple generations to potentially use different models at different steps of the workflow. The description field and instructions of the agent will define which generation is used when. 

On the data model: 
We want to be ready for "Tomorrow ++".
