### ISSUE TITLE
[Multi-Actions] Implement new execution loop

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#4602]
Reference: https://www.notion.so/dust-tt/Multi-Actions-Technical-Proposal-662aa8afbc584f4285d89becc0a6417b

New execution loop should make no model call when `force_use_at_iteration` is present (backward compatible configuration) 

Otherwise implement the router app that and the new execution logic based on the new data model.

**Comment by spolu** [comment]
There's a bit of design thinking to do here.

The main question is whether we merge the scheduler model and the input query generator. I thiink it's obvious that tjhis will be yes.

The second question is what do we show to the scheduler (full conversation? do we have a concept of output summary for actions to not flood the conversation context?).

**Comment by spolu** [comment]
Some additional thoughts here:  https://dust4ai.slack.com/archives/C050SM8NSPK/p1712944914746749

This task likely require to be split in mutliple sub-tasks.

As per thoughts above I'm bullish to keep the existing code-path untouched when we detect a legacy assistant (0/1 actions with fixed iteration + generation + max run steps = 1 or 2).

That way we can iterate agressively without fear of breaking things on new assistants 👍 

Once we converge on something we'll be able to remove the old code-path (since the new converged scheduler should be able to handle schedules that correspond to legacy assitsant and we will be done iterating on it too often 👍)

**Comment by fontanierh** [comment]
Closing, we'll open other cards to iterate
