### ISSUE TITLE
[Mutli-Actions] Browse action framing

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#4605]
Behind flag

Headless browsing of a specified URL

**Comment by lasryaric** [comment]
@philipperolet I was about to take this one and learned that you are on it, so I am assigning it to you.

Please LMK if that's wrong.

**Comment by lasryaric** [comment]
@philipperolet this is wrong, we got confused with the WebSearch action.

**Comment by lasryaric** [comment]
Assigning it to me.

**Comment by philipperolet** [comment]
As per IRL discussion with @lasryaric who's eng-runner this week, I'm taking it over, we've discussed the handover

**Comment by philipperolet** [comment]
Issue is actually better understood as framing; framing has been ~done, closing
