### ISSUE TITLE
[Multi-Actions] Figure out which model to use and how to use it for the scheduler

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#4613]
See discussion here: https://www.notion.so/dust-tt/Multi-Actions-Technical-Proposal-662aa8afbc584f4285d89becc0a6417b?pvs=4#c774c4d171454e49a9936bbaa8be0815

OpenAI does not support picking functions but prevent generation.
Alternatives:
- Prompting the model to not generate ever (to be tested)
- Having 2 step. One tool picker and input generation (slow)
- Using another model
 
As part of this task we likely want to add function calling to Anthropic and Cohere to evaluate them as potential scheduler models.

Principle here is that we'll test all of that a lot and we should design with the ability to switch from one approach to another in mind.

**Comment by fontanierh** [comment]
@spolu WDYT if closing this ? I think we are converging towars using whatever the user picked (and only letting them pick models that support function calling, which atm means every assistant builder model)

**Comment by spolu** [comment]
Agreed!
