### ISSUE TITLE
[Multi-Actions] Move model selection out of `GenerationConfiguration` and into `AgentConfiguration`

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#4708]
## Context

> working on ProcessAction I realized that it is likely that we will want to move the model configuration up to the AgentConfiguration.
=> We already use the model information to infer topK in retrieval, which means we won't have any model to look for if generation is deactivated
=> Process action uses a model as well and it would be clumsy to have to specify a model for each action
=> Do we want to have different models for different generation actions? I doubt for now.
Also moving from 1 model setup to mutli-model setup per action is an easy migration. The other way around is not.

Source: https://dust4ai.slack.com/archives/C050SM8NSPK/p1712935960085079

**Comment by PopDaph** [comment]
PR: https://github.com/dust-tt/dust/pull/4723
