### ISSUE TITLE
Add developers secrets to avoid sharing sensitive data

### ISSUE THREAD

**Issue by albandum** [dust-tt/dust#4715]
Context : https://dust4ai.slack.com/archives/C066R3PMUAU/p1712928504363659

We're leaning towards more and more private or public sharing or assistants and apps (templates, etc) 
This means that somewhere in there will be secure variables people don't want to share with the rest of their app/assistant (API keys, etc) 

**Proposed design**

Add a _Secrets_ tab for developers that allows them to define secure variables usable in both assistants (use case to define yet) and apps 
Example usage in apps: `env.state.secrets.VAR_NAME` or ${secrets.VAR_NAME}`

**Comment by spolu** [comment]
Thanks for framing + adding to go/pp. I think this lands at the intersections of solutions/engineering and could totally be tackled by you if you wish to :+1:
