### ISSUE TITLE
Find out what is starving the notion worker

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#4759]
They starve quicker and quicker. Good candidate is the discovered resources that might end up in an infinite loop

**Comment by fontanierh** [comment]
Disabled the infinite discovered resource thing. Looking good so far but early to tell

**Comment by fontanierh** [comment]
awaiting confirmation that workers are no longer starved

**Comment by spolu** [comment]
Nice find if that's confirmed. Maybe we can cap the number of iterations to give us a chance to make progress nonetheless?

**Comment by fontanierh** [comment]
It's not confirmed sadly

**Comment by fontanierh** [comment]
And they get more frequently starved now

**Comment by fontanierh** [comment]
My main focus for tomorrow

**Comment by spolu** [comment]
Mistery remains :/

**Comment by spolu** [comment]
Hopefully we have a way to introspect how worker slots are taken by workers....

**Comment by fontanierh** [comment]
Yeah not exactly sure how yet… but it does look like the notion worker stop doing anything all of a sudden

**Comment by fontanierh** [comment]
For some reason this hasn't happened in days. Moving back to committed. I can't repro and I have no example

**Comment by philipperolet** [comment]
Following this https://github.com/dust-tt/tasks/issues/664#issuecomment-2091111664

**Comment by fontanierh** [comment]
They seem well-fed for at least a week now 🤷‍♂️

**Comment by philipperolet** [comment]
Hey, since we can't repro for > a month, and no news good news, would you be ok to close @fontanierh ?

**Comment by spolu** [comment]
We believe it was fixed this weekend👍

**Comment by fontanierh** [comment]
Let's close it, since we don't have a "hold before close" :)
