### ISSUE TITLE
[Multi-Actions] Invert relationship  `AgentMessage <> Agent*Action`

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#4787]
Context: https://dust4ai.slack.com/archives/C050SM8NSPK/p1713562612648479

`AgentMessage` <> `Agent*Action` have a 1-1 relationship that needs to be inverted and turned into a 1-many

**Comment by fontanierh** [comment]
@lasryaric  mentioned you [here](https://github.com/dust-tt/dust/pull/4963/files#r1589155879) wrt this task -- is having an `actions` array on the `MessageType` within the scope of the task ?

**Comment by lasryaric** [comment]
>@lasryaric mentioned you [here](https://github.com/dust-tt/dust/pull/4963/files#r1589155879) wrt this task -- is having an actions array on the MessageType within the scope of the task ?

No it does not.

**Comment by spolu** [comment]
We can do it asap 👍

**Comment by lasryaric** [comment]
Ok I will work on it once I am done with the task I just picked up 👍

**Comment by spolu** [comment]
We def want to do it now rather than later because we already went all the way to the end for retrieval :+1:

**Comment by spolu** [comment]
(we want to create the CSVs etc... and store them in google drive similarly if/when needed)

**Comment by lasryaric** [comment]
> (we want to create the CSVs etc... and store them in google drive similarly if/when needed)

💯 


> We def want to do it now rather than later because we already went all the way to the end for retrieval 👍

Will do it today, ASAP, just did not want to context switch too much on something a bit touchy I am working on right now 👍

**Comment by lasryaric** [comment]
Done. Closing this task.

https://github.com/dust-tt/dust/pull/4995
