### ISSUE TITLE
Toggle to hide sidebar

### ISSUE THREAD

**Issue by albandum** [dust-tt/dust#4988]
User request : https://dust4ai.slack.com/archives/C0525Q93AEL/p1714996043758629

**Comment by spolu** [comment]
While it's great to link to original context, please include all necessary context in the issue 🙏

**Comment by spolu** [comment]
From the linked thread: the idea is to hide the sidebar for privacy in screen recording setups

**Comment by spolu** [comment]
+ fix hamburger above modal on mobile

**Comment by JulesBelveze** [comment]
As per IRL, @flvndvd will soon introduce a new app layout -> waiting for it to implement it
