### ISSUE TITLE
Handle Gdrive rate limits error in connectors

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#5025]
Example monitor: https://dust4ai.slack.com/archives/C05F84CFP0E/p1715583926015779

**Comment by PopDaph** [comment]
@flvndvd said we did not have this error once during his eng runner week so he did not prioritized it for more urgent tasks. 
I'll opt of the same strategy. 🙏

**Comment by spolu** [comment]
We lost the logs closing
