### ISSUE TITLE
Investigate burst of Intercom errors

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#5026]
Example monitor: https://dust4ai.slack.com/archives/C05F84CFP0E/p1715578642011119

**Comment by flvndvd** [comment]
Relevant logs are [here](https://app.datadoghq.eu/logs?query=Unhandled%20activity%20error%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=paused&storage=hot&stream_sort=desc&viz=stream&from_ts=1715575466430&to_ts=1715581085942&live=false).

**Comment by flvndvd** [comment]
Shipped https://github.com/dust-tt/dust/pull/5039 that adds some logs to debug.

**Comment by spolu** [comment]
\o/

**Comment by PopDaph** [comment]
Shipped https://github.com/dust-tt/dust/pull/5242 so we get the content from the logs. 
We have a small burst each morning around 7am, only for Connector 809.

**Comment by PopDaph** [comment]
Content of the files erroring every morning is 😅  

```
<noscript>
        <h1>JavaScript is disabled</h1>
        In order to continue, you need to verify that you're not a robot by solving a CAPTCHA puzzle.
         The CAPTCHA puzzle requires JavaScript. Enable JavaScript and then reload the page.
    </noscript>
```

**Comment by PopDaph** [comment]
https://github.com/dust-tt/dust/pull/5342
