### ISSUE TITLE
[Goodgle Drive] Avoid calling Google API when retrieving content nodes for drives or root folders

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#5100]
Follows PR #5090 and issue https://github.com/dust-tt/tasks/issues/711

Root folder = at the top of the selected folders hierarchy for the workspace's Google Drive

Currently, each time we need content node objects (permissions, retrieval data source selection, ) we call google API. We should avoid that and have the info available directly, just like for other files and non-root folders

Options:
A. merge google_drive_folders into google_drive_files table, indicate they are a user selection via a column
B. have rows for root folders both in google_drive_files and in google_drive_folders
C. just add a name column to google_drive_folders

C seems brittle; A and B enforce the invariant that every object we synchronize is in the `google_drive_files` table (no reason to treat a root folder differently from other folders, and somehow imply we don't sync it by leaving it out of `google_drive_files`)

Also, would be a good time to rename the tables

**Comment by lasryaric** [comment]
I think it's best to keep both tables:
- One for local data of the remote data (GoogleDriveFiles)
- One for the selected folders (GoogleDriveFolders, but should be renamed).

Lets just read the data directly from GoogleDriveFiles, without talking to the Gdrive API all the time 👍

**Comment by philipperolet** [comment]
>  without talking to the Gdrive API all the time 👍

That we agree on. It's the title of the card :)

If I read correctly you're saying you're in favor of option B rather than A or C. Why do you think it's better? (asking naively, haven't put that much thought on it yet)

**Comment by philipperolet** [comment]
(probably agree that B is good btw :) )

**Comment by lasryaric** [comment]
I agree with B 👍

**Comment by philipperolet** [comment]
google_drive_folders rows who do not appear in google_drive_files [here](https://metabase.dust.tt/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJTRUxFQ1QgKlxuRlJPTSBcImdvb2dsZV9kcml2ZV9mb2xkZXJzXCIgZm9sZGVyc1xuTEVGVCBKT0lOIFwiZ29vZ2xlX2RyaXZlX2ZpbGVzXCIgZmlsZXMgT04gZm9sZGVycy5cImZvbGRlcklkXCIgPSBmaWxlcy5cImRyaXZlRmlsZUlkXCJcbldIRVJFIGZpbGVzLlwiZHJpdmVGaWxlSWRcIiBJUyBOVUxMIG9yZGVyIGJ5IGZvbGRlcnMuXCJ1cGRhdGVkQXRcIiBkZXNjO1xuIiwidGVtcGxhdGUtdGFncyI6e319LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInBhcmFtZXRlcnMiOltdLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=)

**Comment by philipperolet** [comment]
It seems when we delete a google drive file, we don't delete it in "folders", which explains part of this log. @lasryaric sending a PR to fix that, eager for your thoughts (maybe there's a reason for not deleting in "folders" that I'm not seeing)

**Comment by philipperolet** [comment]
**Sitrep**
It might be that the issue was legacy, i.e. that we actually already did solution B for a while. Root issue would have been about legacy files, and not operating anymore

PR above makes a step towards ensuring that folders & files tables are in sync by making sure we delete from folders when we delete from files

Next steps:
- remove all folders in the table that have no associated google drive file AND are not available to us as objects;
- check if any folder remain, backfill them
- control: monitor no new folder pops up that does not have any google drive file row

**Comment by philipperolet** [comment]
After some more digging, it seems there is a scenario where an object both in GoogleDriveFolders and GoogleDriveFiles could get in an inconsistent state during garbage collect
See code [here](https://github.com/dust-tt/dust/blob/5a15ac5823300a76bdbc6ff4ef4491a29c4d059a/connectors/src/connectors/google_drive/temporal/activities.ts#L600)

- a drive or toplevel folder has not been seen before lastSeenTs, it is considered by garbage collection
- since it's top level, `isInFolder` is false
- therefore, it's deleted from `GoogleDriveFiles` (and with PR above, from `GoogleDriveFolders` too)

This is likely the root cause of this issue from the very beginning. It would cause unfrequently seen drives / toplevel folders to get removed

Fixing PR incoming

**Comment by philipperolet** [comment]
There are still orphaned Google Drive Folders as per the [query](https://github.com/dust-tt/dust/issues/5100#issuecomment-2137083902) :cry: 
Reopening to investigate

**Comment by philipperolet** [comment]
Re-checking the query, only 4 orphan rows remain, quite old (not cleaned due to hiccups in the script)
This would mean fix did indeed work. Leaving open for a while, will check next week that no new rows appear.

**Comment by philipperolet** [comment]
No new rows appeared. Problem is solved. Closing for good this time
