### ISSUE TITLE
Confirm Qdrant setup with Qdrant core team

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#5150]
Working doc: https://www.notion.so/dust-tt/Design-Doc-Qdrant-re-arch-d0ebdd6ae8244ff593cdf10f08988c27

**Comment by flvndvd** [comment]
I dropped the notes are in the Notion [doc](https://www.notion.so/dust-tt/Design-Doc-Qdrant-re-arch-d0ebdd6ae8244ff593cdf10f08988c27).

**Comment by spolu** [comment]
Thanks!
