### ISSUE TITLE
[Multi Actions] Anthropic support

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#5157]
Currently, Multi Actions doesn't work with Anthropic because we use streaming mode with function calls, which Anthropic doesn't support in the GA mode. 
We have access to a Beta of the models that does support it. So we want to switch to that model, and make it work with MA

**Comment by fontanierh** [comment]
context from anthropic available here: https://dust4ai.slack.com/archives/C0735P3JH9T/p1715876190159309

**Comment by flvndvd** [comment]
Added in https://github.com/dust-tt/dust/pull/5328 and  https://github.com/dust-tt/dust/pull/5347.
