### ISSUE TITLE
[Multi Actions] GPT4o "invalid output" error

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#5158]
GPT4o currently has an issue in Multi Actions mode. It randomly throws 500 errors ("The model generated invalid content").

Here's a repro (it's random so if you re-run it, it might work. But run it enough times and it will fail): https://dust.tt/w/0ec9852c2f/a/0c01a3a178

**Comment by spolu** [comment]
@fontanierh did you send the email to Romain Huet? What was the other point to cover?

**Comment by spolu** [comment]
Ah yeah it was the generation of tokens in auto mode right?

**Comment by fontanierh** [comment]
I did not send the email indeed, I got side-tracked on other stuff before going OoO. The other point was GPT4 generating both text (`content`) and function calls.

**Comment by fontanierh** [comment]
Here's the issue for the other point: https://github.com/dust-tt/dust/issues/5159

**Comment by spolu** [comment]
Want me to send the email?

**Comment by fontanierh** [comment]
I can take, but I need to finish my ongoing stuff first (customerio/tracking stuff that is blocking for bizops).
