### ISSUE TITLE
[Multi-Actions] [Websearch] Production pass

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#5192]
- test & improve dust app if needed
- Create & use SerpApi Dust account: Big Data plan ($275/month, 30K searches), can be upgraded if/when needed

**Comment by spolu** [comment]
We already have serp api account. Happy to upgrade it :+1: 

This is the one on the Dust workspace.

**Comment by philipperolet** [comment]
Discussion on slack [here](https://dust4ai.slack.com/archives/C050SM8NSPK/p1716306463079989)
Card can be closed
