### ISSUE TITLE
Improve token streaming UI

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#5280]
Explore what Claude, ChatGPT Perplexity do and improve token streaming look and feel

(animated token/sentence/paragraph appearance)

**Comment by spolu** [comment]
Discussion here: https://dust4ai.slack.com/archives/C050A0S2Z7F/p1716985603093109

**Comment by Duncid** [comment]
- Scroll smooth move the new agent message at a distance from top roughly equal to a 2 liner user message
- Let the model generate but don't auto-scroll

**Comment by spolu** [comment]
Above comment is not related to this  but rather #5411 

This issue is about the UI effects around streaming of tokens / sentences / paragraphs

**Comment by gabhubert** [comment]
@spolu is this an ask for design to frame?

**Comment by spolu** [comment]
Not really. Even if framing is welcome. It was created to be used in on-sites more than anything else 👍

**Comment by spolu** [comment]
closing as this is mostly for on-site
