### ISSUE TITLE
[Qdrant] Store sections in GCS alongside document_id and content

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#5297]

**Comment by spolu** [comment]
We do rely on the existing GCS content to get data source documents full content. So this will likely require a migration.

The idea is to double write existing + a json that has title, content and sections | null
Fix the scrubber to delete old and new format
Then migrate all existing files
Then start reading from new structure
Then remove double write
Then clean-up all previous files


There won't be a folder per document anymore just internal_id.json in the data source folder

Structure:

```
{
  document_id: string,
  full_text: string,
  sections: Section | null
}
```

**Comment by flvndvd** [comment]
All data sources documents have been backfilled ✅

**Comment by spolu** [comment]
:fire:

**Comment by flvndvd** [comment]
Still required:
- [ ] Switch all reads
- [ ] Then remove double write
- [ ] Then clean-up all previous files

**Comment by flvndvd** [comment]
Paused because of https://github.com/dust-tt/tasks/issues/852.

**Comment by flvndvd** [comment]
Switched retrieval read operation to use the new file in https://github.com/dust-tt/dust/pull/5584.

**Comment by flvndvd** [comment]
Switch all read operations in https://github.com/dust-tt/dust/pull/5704.

**Comment by flvndvd** [comment]
Will remove the double write this week as we got no report for the past ~10 days.
