### ISSUE TITLE
[Model Deactivation] - Update `Workspace` with a list of supported providers

### ISSUE THREAD

**Issue by JulesBelveze** [dust-tt/dust#5327]
Add `whiteListedProviders` and `embeddingModel` attributes to the `Workspace` model

**Comment by spolu** [comment]
Interesting question how we want to model that.

We will use that information in many critical places. Yet a JSONB on workspace is a bit dissatisfying...

**Comment by JulesBelveze** [comment]
What about having a `string[]` field within the `Workspace` model with default value `MODEL_PROVIDER_IDS` ?

**Comment by spolu** [comment]
This definitely works here. This can be `string[] | null` which would mean all when null is selected. But also we'll need something for the embedding provider, and all of the sudden it's 2 new fields on Workspace.

But I guess these are workspace related information so that kind of make sense.
