### ISSUE TITLE
[Multi Actions] Better conversation UI when multiple actions

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#5350]
![Image](https://github.com/dust-tt/dust/assets/14199823/f486534c-1c97-4ee9-b9e7-bd04f908dcf3)

For now it is pretty ugly

**Comment by fontanierh** [comment]
There's this Figma: https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=7026-16818&t=NMrnk2wmBQl5azmh-0  (related to https://github.com/dust-tt/tasks/issues/827)

But doesn't solve the issue: we need the to look good in a list, + maybe make it clear when some actions are executed in parallel (at the same step)

**Comment by flvndvd** [comment]
Checked with @Duncid on our requirements:
- We only display the last known state, such as "searching" or "web browsing," without providing additional details while it's running.
- Once the agent message is completed, clicking the "search results" CTA will open the drawer containing all the visible information.

**Comment by fontanierh** [comment]
Some of my interrogations
- This seems to only cover websearch and data source search. What about dust apps ? Extract data ? Tables query ? Browse ?
- What happens when you have several actions in a row ?
- What happens when you have several actions running at the same time ?

**Comment by spolu** [comment]
Let's schedule an IRL chat about this ASAP (maybe tomorrow). And of course continue build state here in the meantime.

@fontanierh can you share a few conversations with a loooong list of actions + can you compute a list of in-progress events for each actions to ease the discussion tomorrow :pray:

**Comment by fontanierh** [comment]
@spolu @flvndvd @Duncid let's definitely chat tomorrow if possible

> We will always display the last known step in the chip, which includes the dust app, query tables ... all of them. The goal of this new UI is to reduce clutter by minimizing the amount of information displayed. All relevant information can be found in the search results panel.

I don't quite get it. If my assistant just calls a dust app, then I have this "search" thing that pops up ?  And what is a search result panel ? Is it some kind of side modal that isn't on the Figma yet ?

> We only display the last know state in the conversation UI. The full list will be available once the message is finished in the drawer.

Even once all the actions are complete ? Shouldn't we display something like "ran 6 actions" ?

> It's true that this design does not take this into account, did we decide to support many tool calls in parallel?

Yes, we already support it. We at least need to display multiple actions running simultaneously (as we do now).


I think we have a lot of things to discuss, because IMO this design looks better but for now seems like a big regression in terms of functionality

**Comment by fontanierh** [comment]
Here's a conversation with a long list: https://dust.tt/w/0ec9852c2f/assistant/fec1f40c3d

**Comment by fontanierh** [comment]
Could we add the Dust app name in the drawer as well ?

**Comment by flvndvd** [comment]
> Could we add the Dust app name in the drawer as well ?

Done ✅ .

**Comment by fontanierh** [comment]
Awesome 🙏

**Comment by spolu** [comment]
This is mostly completed right? 

What do we miss?

**Comment by flvndvd** [comment]
Remaining (non-blocking) work is tracked here:
- https://github.com/dust-tt/dust/issues/5673
- https://github.com/dust-tt/dust/issues/5674
