### ISSUE TITLE
[Multi Actions] Websearch & Browse appear as a single action in the Builder, with no config

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#5379]
- Websearch & browse are 2 actions in the backend, but in the assistant builder they appear as a single action (discussed in this [thread](https://dust4ai.slack.com/archives/C050A0S2Z7F/p1716883751545989?thread_ts=1716369237.385929&cid=C050A0S2Z7F) and confirmed in this [issue](https://github.com/dust-tt/dust/issues/5425#issuecomment-2146065523) )
- Adding the action should just add it, no side modal (discussion [thread](https://dust4ai.slack.com/archives/C050A0S2Z7F/p1717146453939199?thread_ts=1717145842.127109&cid=C050A0S2Z7F) )
- Should only be able to add a single websearch & browse action
-  Should leverage the "capabilities" category.

**Comment by philipperolet** [comment]
Will handle once the [browse action](https://github.com/dust-tt/dust/issues/4605) is done

**Comment by PopDaph** [comment]
> Adding the action should just add it, no side modal (discussion [thread](https://dust4ai.slack.com/archives/C050A0S2Z7F/p1717146453939199?thread_ts=1717145842.127109&cid=C050A0S2Z7F) )

-> Make sure to test with Templates, you'll most likely have to tweak the templates logic for that, currently it always opens the modal with the pre-filled action 🙏
