### ISSUE TITLE
Improve scrolling behavior

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#5411]
Auto-scrolling is a bit broken since it keeps moving as tokens get streamed which prevent users from reading the text at the beginning of the message if streaming is fast.

Investigate what other platforms are doing (chatGPT, Claude, Anthropic), then define and implement a better UX.

Our current belief is that the best experience would be:
- As the new agent message appear we scroll to it at a distance from top roughly equal to a 2 liner user message
- Let the model generate but don't auto-scroll

it's more challenging than it looks to properly implement.

**Comment by Duncid** [comment]
- Scroll smooth move the new agent message at a distance from top roughly equal to a 2 liner user message
- Let the model generate but don't auto-scroll

**Comment by spolu** [comment]
(some discussion here: https://dust4ai.slack.com/archives/C050A0S2Z7F/p1716985603093109)

**Comment by Duncid** [comment]
https://dust4ai.slack.com/archives/C066R3PMUAU/p1718014220896619
