### ISSUE TITLE
[Multi Actions] Feature flag and/or command to "switch" a workspace to multi-actions

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#5436]
"Switching" a workspace means all their assistants start behaving as multi-actions assistants. Their "single action" builder UI is no longer accessible.
This has to be entirely reversible.

> **Transitioning workspaces from single action world to multi action world**
> We won't keep the single action builder. Once you switch, you switch.
> All your assistants, including existing ones, start behaving as multi action agents.
> The migration is entirely reversible (we keep your forceUseAtIteration  settings, so if we switch you back, all assistants that can be used as legacy agents will start behaving that way again)

**Comment by spolu** [comment]
Meditating for a bit

**Comment by spolu** [comment]
Ok with your plan to kill it with fire and have the flag drive the code path we use.

Agreed we need to rename to maxSteps

One thing we could consider is replacing the forceUseAtIteration by a simple boolean `forceUse` which would force the use at Step 1. But I don't think it's worth it if we believe the agentic route to be the future here, and I think we do.

**Comment by fontanierh** [comment]
> One thing we could consider is replacing the forceUseAtIteration by a simple boolean forceUse which would force the use at Step 1. But I don't think it's worth it if we believe the agentic route to be the future here, and I think we do.

I would be in favor of dropping for simplicity. I think we'll be fine, but we'll try on our own workspace first. If it turns out to not be fine, then we can re-introduce as a bool easily before shipping

**Comment by spolu** [comment]
Tots
