### ISSUE TITLE
[UX] Make input sticky

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#5455]
- when users scroll on assistant list, input never goes out of sight, stays sticky on top of screen

Depends on [5446](https://github.com/dust-tt/dust/issues/5446)

As mentioned in item 5.A. of the framing [issue](https://github.com/dust-tt/decisions/issues/212)

///

Full Figma [here](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=5713-48822&m=dev)

**Comment by spolu** [comment]
Conditioned on #5395 + #5458 not assigning for now

**Comment by philipperolet** [comment]
Hey,
We're not sure about these 2 nice-to-haves for new conversation -- they would take some work for eng, and seem not that important to prioritize?
On product end, do you think these tasks are necessary or could they be dropped? If necessary, could we have a quick discussion as to  what makes them important so that we can either do them with conviction or maybe strike and advantageous 80/20 tradeoff?

**Comment by spolu** [comment]
Closing as won't fix. Might be revisited as part of Favorites
