### ISSUE TITLE
[New conversation] [Nice to have] Focus on inputbar / focus on search

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#5457]
- focusing on inputbar: when user click or starts typing, smoothly focus on the input bar as described in figma  [here](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=6420-29639&m=dev)  (disappear the search)
- vice versa if focusing on the search

and go back to orignal state on unfocus

See specific figma [here](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=6420-29639&m=dev) 

///

Full Figma [here](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=5713-48822&m=dev)

**Comment by philipperolet** [comment]
Feels like a nice to have, what we already have is quite good. TBD

**Comment by philipperolet** [comment]
👍 edited com, but honestly quite nice to have

**Comment by spolu** [comment]
I must have a skill issue with figma but I don't see anything related to that in the page linked or when running it :p

**Comment by spolu** [comment]
(but the description is clearer :+1:)

**Comment by spolu** [comment]
We can likely move that to Olympus?

**Comment by spolu** [comment]
Motivation to move to Olympus was that amount of work vs value was a bit off for the New Conversation project

**Comment by spolu** [comment]
Conditioned on #5395 + #5458 not assigning for now
