### ISSUE TITLE
[New conversation] Better "entering conversation" transition

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#5458]
- Avoid page refresh when a message is posted from a new conversation
  - Smoothly go to a new conversation
  - don't work too much on maintaining a good autoscroll, since it will be revamped very soon to be suppressed

Depends on [5446](https://github.com/dust-tt/dust/issues/5446)

As mentioned in item 7. of the framing [issue](https://github.com/dust-tt/decisions/issues/212)

///

Full Figma [here](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=5713-48822&m=dev)

**Comment by spolu** [comment]
@flvndvd since you have the most state can you comment on what is feasible and not and at what cost?

**Comment by flvndvd** [comment]
Done
