### ISSUE TITLE
Get and store token usage from providers

### ISSUE THREAD

**Issue by tdraier** [dust-tt/dust#5459]
Initially from  https://github.com/dust-tt/tasks/issues/622 , the goal is to have a precise idea of tokens used for every workspace/provider/app/assistants/ .. 

Gather prompt and generated token stats from core and send them to front , then store them in proper tables for easy querying.

**Comment by spolu** [comment]
Hi hi! As per IRL not quite yet :)

We want to store the usage on Run objects. From there we will likely want to link run objects to agent messages and conversations (for title generation)

The likely good solution is a new join table that maps conversation.id || agent_message.id to run.id. To be discussed :+1:

**Comment by spolu** [comment]
Side benefits is that we would be able to have a debug mode allowing us to get to the runs from a conversation directly
