### ISSUE TITLE
Gdrive - add support for "Shared with me".

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#5477]
One of our users has one shared drive for the whole company and want to share with more granularity content to Dust (in the sense of the OAuth token for security reason).

A potential path towards this is to share sub-folders with an account used to sync with Dust and then short cut that content in a shared folder created for the account used for syncing with Dust.

This is not compatible with the webhook incremental sync system we have right now.

The goal of this issue is to track progress on adding support for that flow.

- [x] Do not trigger a webhook subscription for drive that are outside of the user's account
- [x] Show a "shared with me" folder
- [x] Add incremental sync for non shared drive items
- [x] Stop hardcoding `userland`
- [ ] Remove all webhooks related code.

**Comment by spolu** [comment]
@lasryaric mind describing here the 2 potential solutions we discussed 🙏

**Comment by lasryaric** [comment]
It all seems to be working [really well](https://app.datadoghq.eu/apm/traces?query=%40_top_level%3A1%20%40workflow_id%3AgoogleDrive-IncrementalSync-%2A%20&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2Cresource_name%2C%40duration%2C%40http.method%2C%40http.status_code&fromUser=true&graphType=flamegraph&historicalData=true&query_translation_version=v0&saved-view-id=93702&shouldShowLegend=true&sort=time&spanType=service-entry&spanViewType=logs&traceQuery=&view=spans&viz=stream&start=1718032288414&end=1718034088414&paused=false), 3 iterations of the icrementalSync workflow for everyone, no error (5 minutes interval).

I also tested on our Dust workspace that we can sync a "Shared with me" folder and I went through 3 rounds of update. Works well too 👍 .

I will send a message to Watershed right now.

**Comment by lasryaric** [comment]
Shipped. Closing.
