### ISSUE TITLE
[Multi Actions] Track assistant builders step to figure out if / where we are losing people

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#5490]
@mgxlebrun :
> Thought: checking the new assistant creation flow, I think we will really want to understand what users do when they create assistants and where they potentially get stuck to iterate on the experience
> 
> So I'd add a item "set up tracking builder experience" towards the end of the list - it's not 100% necessary to launch and maybe having it in the "Builder experience" section https://github.com/dust-tt/tasks/issues/789 is enough, but I'm afraid it might be dropped if not added here (and then we'll have no data like for templates)

`assistantActionType` on Amplitude should become an array (see https://dust4ai.slack.com/archives/C050SM8NSPK/p1712667284829569)

**Comment by fontanierh** [comment]
@mgxlebrun Do you have ideas of what events could be useful to understand this ?

**Comment by mgxlebrun** [comment]
### Foreword
I believe what we want to see 2 things to assess success:
1. If users actually manage to create assistants vs. we lose them along the way 
2. An idea of how well multi-action assistants perform 

- I imagine **Amplitude** is the right place to store this
- Meta - the events below were actually included in the card I had written about product usage tracking: https://github.com/dust-tt/tasks/issues/789. I reformatted the list to avoid overlap. 

### 1. How easy is it to create an assistant?
I believe what's informative here is the funnel from clicking on `New assistant` to actually saving an assistant (to assess the % of losses between each step, and identify where potential bottlenecks are)

- - [ ] Click on new assistant > 
- - [ ] Click on action & data sources > 
- - [ ] Click on action XYZ (Search, Extract data, Table query, etc.) >
- - [ ] Click on "save" action XYZ (i.e. the user managed to find the right data sources and describe them) >
-   [Already tracked] Assistant created 

_What is success?_ I'd say % of builders dropping between click on `action & data sources` and `save` is below 20% (no strong view on the exact figure, the idea is that it should be relatively low)

### 2. Once an assistant is created, how do they perform depending on their action configuration?
To do this, we want to track how assistants with different actions are used over time. This could be done by having an **attribute** at the assistant level storing: 
- [Already tracked] its built-in actions (I believe this is already ActionType)?
- - [ ] [TBD, if easy to do] its type of data sources (Table, folder, Gdrive, Notion, etc. - to track how action + data source interactions impact performance)

On how to handle assistant edits - I think for now attributes only correspond to the latest version? Would keep it that way for now

_What is success?_ Some assistants with several actions are used weekly by a growing base of users, across workspaces

**Comment by fontanierh** [comment]
bullish, thanks @mgxlebrun

> [Already tracked] its built-in actions (I believe this is already ActionType)?

This will need to become an array
Let's close [[Multi Actions] Amplitude: assistantActionType should become an array
[#4648]](https://github.com/dust-tt/dust/issues/4648) and merge it in here 👍 


> the events below were actually included in the card I had written about product usage tracking: https://github.com/dust-tt/tasks/issues/789. I reformatted the list to avoid overlap.

Is the work on https://github.com/dust-tt/tasks/issues/789 already started @lasryaric ? I imagine the person who will work on this issue will want to align with your work there 👍

**Comment by mgxlebrun** [comment]
> bullish

yes trying not to push for overkills, but if the feature is not used I do imagine we'll be happy to have somewhere to look for why

>  I imagine the person who will work on this issue will want to align with your work there 👍

Indeed, overlooked the cc. Thanks!

**Comment by lasryaric** [comment]
>Is the work on https://github.com/dust-tt/tasks/issues/789 already started @lasryaric ? I imagine the eng who will work on this issue will want to align with your work there 👍

I am planning on releasing today the Template usage tracking which is a P0, but other than that no.

**Comment by fontanierh** [comment]
Are you interested in

**Comment by fontanierh** [comment]
Ok thank @lasryaric 

Are you interested in taking this one as well ?

**Comment by fontanierh** [comment]
(would qualify as p0 as well IMO)

**Comment by lasryaric** [comment]
@fontanierh I can take 👍

**Comment by fontanierh** [comment]
Thank you 🙏  🙏

**Comment by lasryaric** [comment]
Hello, I have not work on it yet. 
I  am planning to work on it tomorrow.

**Comment by fontanierh** [comment]
Thanks @lasryaric can I assign to you an move to olympus ?

**Comment by lasryaric** [comment]
Already assigned to me and yes to move it to Olympus.

**Comment by lasryaric** [comment]
PR is out, we agreed IRL with @mgxlebrun on focusing on two events for now:

- `AssistantBuilderOpened`
- `AssistantBuilderStepViewed`

The `AssistantCreated` event already exists.

We'll revisit if we need to get deeper for this analysis.

**Comment by lasryaric** [comment]
Code is deployed. Closing this task.

**Comment by lasryaric** [comment]
>2. Once an assistant is created, how do they perform depending on their action configuration?
i.e. track how assistants with different actions are used over time - could be having an attribute at the assistant level storing:

> [Already tracked] its built-in actions (I believe this is already ActionType)?
> [TBD, if feasible] its type of data sources (Table, Folder, Gdrive, Notion, self-made connexion, etc. - to track how action + data source interactions impact performance)

All of that is already accessible on Metabase. Is that enough @mgxlebrun ?

**Comment by gabhubert** [comment]
Catching up, my understanding of ownership here is that @mgxlebrun will suggest dashboards?

**Comment by mgxlebrun** [comment]
Yes will have a look this week

**Comment by mgxlebrun** [comment]
- First results are here: https://dust4ai.slack.com/archives/C061J53LTLN/p1720427963179869
- They would need to be reworked to check for **interactions** 
   - e.g. add an attribute "_interaction_" if the user did write a prompt in the instructions tab / selected a tool in "tools and data sources" / wrote a name in the last step
   - The goal would be to filter out people who checked out the assistant builders without any **intention** of creating an assistant. 
- I won't have time to tackle this unfortunately, but this can be picked up by the rest of the business ops teams when it's time to add data to complement user test notes. Checking first, is this feasible @lasryaric?

**Comment by lasryaric** [comment]
>I won't have time to tackle this unfortunately, but this can be picked up by the rest of the business ops teams when it's time to add data to complement user test notes. Checking first, is this feasible @lasryaric?

It is doable, but it's not high priority enough right now.
The funnel seems healthy IMHO.
