### ISSUE TITLE
[Multi Actions] Templates experience

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#5493]
Current templates are not multi actions, and the templates experience in multi actions needs to be refined.
To be defined in collaboration with @Duncid  and implemented

**Comment by fontanierh** [comment]
Can we close @PopDaph  ?

**Comment by PopDaph** [comment]
Yes! The only thing now is to create some multi-actions templates, but it's supposed to be in another card right?

**Comment by fontanierh** [comment]
> Yes! The only thing now is to create some multi-actions templates, but it's supposed to be in another card right?

Indeed, still haven't created it. Doing now !
