### ISSUE TITLE
[New Conversation] [Nice to have] Keyboard shortcuts to put focus "start a new conversation" or "focus on input bar"

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#5516]
- Scoping [here](https://github.com/dust-tt/decisions/issues/198)

Add shortcuts to the app, and show them in the help drawer

Depends on [5453](https://github.com/dust-tt/dust/issues/5453)

///

Global framing [issue](https://github.com/dust-tt/decisions/issues/212)

Full Figma [here](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=5713-48822&m=dev)

**Comment by spolu** [comment]
We can likely move that to Olympus?

**Comment by spolu** [comment]
Motivation to move to Olympus was that amount of work vs value was a bit off for the New Conversation project

**Comment by spolu** [comment]
No update since June 17. Clausing. If someone cares about keyboard shortcut they will be able to pick it up.
