### ISSUE TITLE
[Multi Actions] create some multi-actions Templates

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#5607]

**Comment by PopDaph** [comment]
From: https://dust4ai.slack.com/archives/C050A0S2Z7F/p1718295974152449?thread_ts=1718289229.685489&cid=C050A0S2Z7F

I've created two multi-actions templates @codingBuddy & @customerSuccessTraining that can be improved :pray::skin-tone-2:

Note about templates:
For a single-action workspace, we display all the Templates that have no action set in presetActions
For a multi-action workspaces, we display all the Templates that have at least one action in presetActions or that are in reply only.
=> So the 2 new templates are in prod but only displayed for Multi-Actions activated workspaces.
