### ISSUE TITLE
[Conversations] Search past conversations

### ISSUE THREAD

**Issue by Yutcam** [dust-tt/dust#5707]
JTBD:  As a user, I want to find past and important conversations so I can quickly pick up where I left off without losing context.

## Adding Search

Ideally, fuzzy search on title & conversation:
![Image](https://github.com/dust-tt/dust/assets/4435185/e795d1f1-4d31-424c-8571-4accd2a804f8)

**Comment by spolu** [comment]
Conditioned on keyword search infra

Will move product roadmal

**Comment by spolu** [comment]
Will move that to product roadmap given the dependecy on https://www.notion.so/dust-tt/Keyword-Search-Infrastructure-9a95c42710574551b09b29cf9f10c52a?pvs=4

**Comment by spolu** [comment]
Created https://www.notion.so/dust-tt/Search-past-conversations-86ff201dc5244e54927323c2d93df807?pvs=4 for tracking given dependency on existing task that is not ready.
