### ISSUE TITLE
[MS connector] check connection with non-admin user

### ISSUE THREAD

**Issue by tdraier** [dust-tt/dust#5738]
As stated [here](https://www.notion.so/dust-tt/Design-Doc-Microsoft-connector-s-d727df50da13419a898233cb1f32e60c?pvs=4#929e2163f5744436aeb60f26fd71b531) , connecting with a non admin gives an error message "Need admin approval". Check how to fix if possible, and which permissions are used

**Comment by philipperolet** [comment]
@tdraier NRE when you're back
For now, can we just tell customers that the microsoft admin should be the one to make the connection? would that work out-of-the box?

We can work on making this simple for non-admins later on

**Comment by tdraier** [comment]
Actually the admin does not need to add the user, only grant consents. Grant request can be reviewed and accepted here : 

![Image](https://github.com/user-attachments/assets/189c2739-8326-4c9d-b866-6d4a122c4767)

If the application already exist but is missing some permission, by going to security/permissions and clicking "Grant admin consent for .."

Or, manually, through a url call : 
https://login.microsoftonline.com/<tenant-id>/adminconsent?client_id=3719c875-37d4-40ba-94a3-577c9d4cc86a

(casquedelumiere tenant-id=55df461b-3618-4315-b6df-6eba12eb1063)
