### ISSUE TITLE
Do not count mentions from workflow in assistant usage count

### ISSUE THREAD

**Issue by JulesBelveze** [dust-tt/dust#5759]
We want to get rid of the mentions that are generated by workflows.

This requires to change the SQL query and the `signalAgentUsage` logic.

**Comment by JulesBelveze** [comment]
@philipperolet Dug a little bit and I'm not sure there's actually a way to make a distinction.. Using `message.parentId` is unfortunately not feasible as the first message of each convo has no `parentId`

**Comment by spolu** [comment]
We know have an origin on the user message that might be helpful

**Comment by JulesBelveze** [comment]
We found a way to isolate those mentions: the corresponding `userMessage` has no `userId`

**Comment by spolu** [comment]
You should def use userContextOrigin = web instead 👍

**Comment by JulesBelveze** [comment]
Definitely better indeed ! Thx 🙏🏼

**Comment by philipperolet** [comment]
Counterpoint: it seems usercontextorigin can be "slack" | "web" | "api"
=> "slack" should def be counted too for the most popular, lots of users interact via slack & we want to count thos
"api" not sure we can post as users via api but wouldn't we want to one day?

 To be discussed, but afaict the message's origin interface seems transversal to whether it's from a human user or not?

**Comment by spolu** [comment]
Web or Slack is the way to go 👍

**Comment by philipperolet** [comment]
In general, I'd say the title could be "Only count mentions from real users" vs "do not count mentions from workflows"

**Comment by spolu** [comment]
Then let's do web I think that's fine here 👍

**Comment by philipperolet** [comment]
What we want is to filter on "real users", not filter on the interface those users came from. 

We don't want to count slack workflows, but we absolutely want to count messages posted by users from slack

So I think filtering by userId === null remains the most adapted to the use case here; it's the most straightforward way of expressing what we want in the code.

**Comment by JulesBelveze** [comment]
+1

**Comment by spolu** [comment]
Ok. Only worry is that it's best effort and might change in the future in weird ways for Slack IMHO
