### ISSUE TITLE
agent_chain_of_thought is not sent to the ui

### ISSUE THREAD

**Issue by tdraier** [dust-tt/dust#5773]
I don't know if there's an issue, but looking at the code, the `agent_chain_of_thought` does not seem to be yield to the pubsub (and then to AgentMessage) - according to :   

https://github.com/dust-tt/dust/blob/d922548795e169794f05b4aea3bc326fe67cb051/front/lib/api/assistant/conversation.ts#L1715 

it's supposed to be sent, but in :   

https://github.com/dust-tt/dust/blob/d922548795e169794f05b4aea3bc326fe67cb051/front/lib/api/assistant/conversation.ts#L1799 the event is swallowed, and not sent anywhere else.

**Comment by fontanierh** [comment]
Feel free to yield it 👍  

I don't remember if this is really used in the UI, but I guess we should still yield it
