### ISSUE TITLE
[Code-Interpreter] File to description

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#5780]
Design doc is [here](https://www.notion.so/dust-tt/DesignDoc-Code-Interpreter-aeffe26ce3ee47e494bba88da28af5da).

For the model to generate code that can properly operate on files, the model should know the "structure" of the file.
For example, if we ask the model to generate code about a file `house_prices.csv`, the model can not possibly generate the appropriate code without knowing about the CSV structure.

So to help the model generate correct code, we want to have a brief description of each file that the model should know about.
For example, if we have the following file:
house_prices.csv:
```
House Id;	# of rooms;	Year built;	Price
1;	5;	2020;	$600,000
2;	4;	1920;	$300,000
3;	3;	1220;	$350,000
....
100;	6;	2220;	$1250,000
```

We want to tell the model about this file in the following format:
```
<file name="house_prices.csv" sizeInBytes="12341">
House Id;	# of rooms;	Year built;	Price
1;	5;	2020;	$600,000
2;	4;	1920;	$300,000
(truncated....)
</file>
```

For each file extension we support, we want to generate a description that helps the model.

Check out the section `Files extension to file description` [here](https://www.notion.so/dust-tt/DesignDoc-Code-Interpreter-aeffe26ce3ee47e494bba88da28af5da?pvs=4#c8ef1adebadd4afdbab95161605854c1) on the design doc.

**Comment by PopDaph** [comment]
Handling as part of https://github.com/dust-tt/dust/issues/5779
