### ISSUE TITLE
Refactor chat block API to support complex type

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#5784]
See full design doc [here](https://www.notion.so/dust-tt/Design-Doc-Vision-8f1c56ed82b44d06a1b43eab8af36c33?showMoveTo=true&saveParent=true).

To better accommodate diverse content types, including images, our API needs to evolve. Currently, it's restricted to text, which limits our platform's functionality. We propose a more flexible structure that can handle complex data formats, potentially including future support for other media types.

Example:
```rust
#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct RawOpenAIChatMessage {
    pub content: Option<Vec<ContentBlock>>,
    // Other fields.
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct TextContent {
    pub r#type: String,
    pub text: String,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct ImageUrlContent {
    url: String,
}

#[derive(Debug, Serialize, Deserialize, PartialEq, Clone)]
pub struct ImageContent {
    pub r#type: String,
    pub image_url: ImageUrlContent,
}

#[derive(Serialize, Deserialize, Debug, PartialEq, Clone)]
#[serde(untagged)]
enum ContentBlock {
    TextContent(TextContent),
    ImageContent(ImageContent),
}
```

**Comment by spolu** [comment]
Closing as marked as done
