### ISSUE TITLE
[Code-Interpreter] assistant-v2-code-interpreter app

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#5793]
Create the app `assistant-v2-code-interpreter`.
Checkout the `assistant-v2-code-interpreter` [section](https://www.notion.so/dust-tt/DesignDoc-Code-Interpreter-aeffe26ce3ee47e494bba88da28af5da?pvs=4#8a8d10f0944244268c2cb28422f0cecb) of the design doc.

**Comment by PopDaph** [comment]
Probably will need some tweaking but first version is done.

**Comment by lasryaric** [comment]
Thanks!
