### ISSUE TITLE
[Multi Actions] Fix bug where assistant tries to use tool even if not allowed

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#5839]
Mostly observed on 3.5 sonnet.
Could be related to system prompt
We could decide to:
- change system prompt to discourage this (or at least not encourage it when no tools are allowed)
- increase max steps to limit cases where we would have this error
- check if the "dummy tool" hack is still required, if not remove and see if we still have the issue

**Comment by fontanierh** [comment]
It is somewhat similar to https://github.com/dust-tt/tasks/issues/940

**Comment by fontanierh** [comment]
Anyway, this starts with a good repro.

We have the run here: https://dust.tt/w/78bda07b39/a/0e9889c787/runs/18eee44fd1511f2c767f031dac494afb588217cffb0a23c0e1c77db32518a24d

Now we need to reproduce it

**Comment by spolu** [comment]
As per IRL, first step is really to ensure we have a digestible error for users that invites them to retry. Is that the case right now?

From there we can optimize with Anthropic to prevent this as much as possible.

**Comment by fontanierh** [comment]
@spolu  we have the one you added here: https://github.com/dust-tt/dust/blob/3e2281e2eb3b6e048a109a318d4c04ded4612f57/front/lib/api/assistant/agent.ts#L650

**Comment by spolu** [comment]
Maybe we should add a sentence to invite to retry in that case?
