### ISSUE TITLE
Endpoint for batch tokenization in core

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#5934]
We should have a batch end point for tokenization that we can use here:

https://github.com/dust-tt/dust/blob/656576bff4220b84a68099c5e926ec42949c83e6/front/lib/api/assistant/generation.ts#L172-L194

**Comment by flvndvd** [comment]
Moved to Olympus!

**Comment by fontanierh** [comment]
So after digging a bit, all our tokenizers are singletons behind a RW lock. So unless we accept to change that, we wouldn't get much from a batch endpoint since everything will continue to be sequential.

@spolu Is there a strong reason to have a lock on the tokenizers ?

**Comment by spolu** [comment]
The RW lock is used in read mode for tokenization and therefore allow for parallelization within `core`, additionally this would save the N connections + Promise.all which would overall be much more efficient :+1:

**Comment by fontanierh** [comment]
Thanks @spolu
