### ISSUE TITLE
[Websearch] Add other results than organic results

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#5963]
Currently, the web search action only returns results from browserless's `organic_results`
A lot of other results are available, that may be quite useful to the search and are often more relevant than organic results --- direct question answering by google, sports results and more generally event results, main relevant news, etc.

We receive those results from browserless, but discard them in the dust app.

We could product frame, but as a first step we can isolate and add easily accessible stuff directly from the API

**Comment by spolu** [comment]
The most useful other result that I've seen being used in the past the question/answering part of the response. But you can't reference it.

News might be useful but we'll get good coverage even on news use-cases with the organic results.

**Comment by flvndvd** [comment]
Waiting for Philipp3 to be back.

**Comment by spolu** [comment]
Stallness close
