### ISSUE TITLE
[MS connector] .xlsx extraction

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6010]
Different from #5745 since here we need to be able to table-query them

**Comment by philipperolet** [comment]
**Sitrep**
@tdraier already pushed .xslx extraction in #6042 
Remaining todo for new assignee:
- integrate .xlsx extraction to fullsync
- add csv extraction (which should resemble xlsx extraction closely)

**Comment by JulesBelveze** [comment]
Can handle the CSV extraction (did it for Google Drive)

**Comment by JulesBelveze** [comment]
- CSV implemented ni #6237 
- .xslx in #6242
