### ISSUE TITLE
[DB Load] Optimize query for most popular agents

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6068]
The queries notably increased the DB load, as noted last week by @fontanierh 
By performing a few tweaks and caching for 12h instead of 2, the load became ~acceptable cc @JulesBelveze 
Diving deeper in query optimization to reach an acceptable load time and switch back to 2 to 4 hours caching would be 👍

**Comment by philipperolet** [comment]
Axes of optimization:
- work on query plan / profile (toughest)
- limit popularity to 7 days
- only perform one of the 2 queries on new page load (currently there's agent popularity by #mentions and by #users)
- put the queries on snowflake

**Comment by philipperolet** [comment]
Also, confirm that ~700 queries / hour makes sense --- queries are per-workspace per 12h so that would mean ~ 8k active workspaces, and should probably not be smooth since cache hits are when the /new conversation page is loaded

**Comment by spolu** [comment]
(note that snowflake is not to be considered a production system at this stage, unfortunately)

**Comment by spolu** [comment]
The queries are run async right? If so should we consider using the secondary?

**Comment by philipperolet** [comment]
Not async per se, but could be made so
A first path of investigation is that it seems the caching isn't working (much more calls than what we'd expect as noted by @fontanierh )
Assigning myself & will look this week
