### ISSUE TITLE
Investigate high number of connections on Redis

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6167]

**Comment by spolu** [comment]
Aren't we way below levels still?

**Comment by flvndvd** [comment]
First step was to ship [this fix](https://github.com/dust-tt/dust/pull/6181) to free Redis connection earlier as it seems to tbe the main root cause of all the abnormal spikes we [observed](https://app.datadoghq.eu/dashboard/9ew-d95-ag8/redis?fromUser=true&refresh_mode=paused&view=spans&from_ts=1720704406028&to_ts=1720706003322&live=false). 

<img width="528" alt="image" src="https://github.com/user-attachments/assets/1cadc519-a995-4bee-9837-44eee70459e4">

Second step will be to limit all Node processes to one single connection (except for streaming).

**Comment by lasryaric** [comment]
Any update on that @flvndvd ?

**Comment by flvndvd** [comment]
I haven't checked in a while. Last time I looked, not everyone had updated their app, so they weren't benefiting from the latest changes. I'll take a look today.
