### ISSUE TITLE
[MS Connector] Connector deletion

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6194]
A base implementation has been made already
Goal here is to make sure it is thorough; notably at the time it does not delete qdrant data

**Comment by JulesBelveze** [comment]
@philipperolet it seems like we are properly deleting resources on the connectors tables and revoking OAuth tokens. 
Are you sure QDrant data is not deleted properly? It seems to be calling the `deleteDataSource` from front.

**Comment by JulesBelveze** [comment]
It indeeds looks like it..
When deleting a datasource from poke though you hit that endpoint which calls the `deleteDataSource` function which seems to be in charge of the QDrant cleanup
https://github.com/dust-tt/dust/blob/338d7c0ebbd65139549d1ea48fe110d373f332c9/front/pages/api/poke/workspaces/%5BwId%5D/data_sources/%5Bname%5D/index.ts#L34

**Comment by philipperolet** [comment]
You're right! I think it's an issue that we have different delete paths that don't behave the same; all should be in the delete connector IMHO
However, not a microsoft-specific thing
If you agree, can you create an Olympus task for that, and refer to it here in a closing comment?

**Comment by JulesBelveze** [comment]
Link to task: https://github.com/dust-tt/dust/issues/6336

**Comment by spolu** [comment]
For the record the connectors delete cli deletes the connector as intended :) Not the data source since it's a connector cli command.

Will remove it since it's confusing
