### ISSUE TITLE
[MS connector] Feature-flag pptx and csv ingestion

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6273]
As explained in the [Design Doc](https://www.notion.so/dust-tt/Design-Doc-Microsoft-connector-side-topics-c27726652aae45abafaac587b971a41d?pvs=4#e179d67dd13e4470a929b1f72cb71df3) and following this [thread](https://dust4ai.slack.com/archives/C05B529FHV1/p1721062416006399)
Also add a confirm popup when enabling those feature flag explaining that it can slow down sync and manual impact should be assessed.

**Comment by JulesBelveze** [comment]
@philipperolet I have same info as you. Let's only add a CSV feature-flag 👌🏼
