### ISSUE TITLE
[MS Connector] Front edge testing

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6291]
- create connector, ensure fullsync works well
  - check all files and folders
- make a few changes, ensure incremental syncs pick it up
- make RAG with assistants on the whole datasource, then on a specific folder only
- make table queries
- move folders, ensure that after incremental sync picks up, children are correctly matched by datasource selection in assistant builder
  - end-to-end test that also proves their parents array has been correctly updated
- make a few deletions, ensure they took effect after incremental sync and/or GC
- delete connector, enture nothing remains

Depends on #6288 #6289

**Comment by spolu** [comment]
Closing as marked as completed
