### ISSUE TITLE
[cli] thorough cleanup on datasource deletion

### ISSUE THREAD

**Issue by JulesBelveze** [dust-tt/dust#6336]
Currently deleting a datasource through the cli doesn't clean up data in QDrant. Which is different behaviour than when deleting a datasource through poke.

**References:**
- https://github.com/dust-tt/dust/issues/6194

**Comment by flvndvd** [comment]
Should we keep the CLI here?

**Comment by spolu** [comment]
Yes let's just remove the cli functions in favor of poke

Moving to eng runner

**Comment by spolu** [comment]
See comment here: https://github.com/dust-tt/dust/issues/6194#issuecomment-2302267564
