### ISSUE TITLE
[MS Connector] [Post-ship - Stabilization] Reduce risk of "resync required" and lost deletes

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6365]
When calling delta lists on toplevel folders (as opposed to drives)
- the api frequently returns "resync required", which can be costly
- a folder that was deleted from the toplevel folder is not easily detected

When the root is already a drive, all is fine.

What should be done: for a toplevel folder root, call the delta on its parent drive, and filter it appropriately, rather than calling it on the folder

Optionally, only call the delta once, even if there are multiple toplevel folders in the same drive

**Comment by philipperolet** [comment]
Log the resync required and monitor them so we see how much we get them

**Comment by spolu** [comment]
Closing as marked as completed
