### ISSUE TITLE
[MS Connector] [Post-ship - Stabilization] Paginate deltas

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6366]
Currently, we have to go through all the delta to remove all but last occurences
There is a single activity for all the change list.

It would be more stable to save the delta, then have activities work on pages of e.g. 50 changes.

**Comment by spolu** [comment]
Closing as stale

**Comment by philipperolet** [comment]
Post-close note: we can revisit ifever/whenever this becomes an issue. We will notice if an activity regularly fails on a big delta. At the time, it does not seem urgent indeed.
