### ISSUE TITLE
[MS Connector] [Post-ship stabilization] Selective fullsync on add/remove data

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6368]
When the user adds new folders, we currently run a full resync.
Change the logic to only run the fullsync on the newly added folders, not on those that were already synced

**Comment by spolu** [comment]
Closing as stale.

What's the status of Gdrive?

**Comment by tdraier** [comment]
Gdrive is done here : https://github.com/dust-tt/dust/pull/6711
Reopening as PR is opened and ready for review

**Comment by philipperolet** [comment]
Yes, important to adress, reopening indeed :)
