### ISSUE TITLE
[Visualization] Create a doc section docs.dust.tt

### ISSUE THREAD

**Issue by lasryaric** [dust-tt/dust#6440]

**Comment by albandum** [comment]
Sent you a new invite to docs admin @lasryaric

**Comment by albandum** [comment]
Or if you have a short brief of what should be in there I could get to it

**Comment by spolu** [comment]
@albandum mind taking this one in Solutions so that we can close this column 🙏 

What would be the right section of our docs to document visualization? I think the content should explain what it is and how to use it (easy). Maybe dive a bit more in how it works to provide helpful context to users.

**Comment by albandum** [comment]
https://docs.dust.tt/docs/data-visualization-1
