### ISSUE TITLE
[Groups Infra] DataSourceView internal endpoints for creation and edition (admin only)

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#6457]
https://www.notion.so/dust-tt/Engineering-e0f834b5be5a43569baaf76e9c41adf2?p=5d15a65989da4b11aa99ed1c213f9fb3&pm=s

Only admins can create DataSourceViews
The DataSourceView should be assigned to a GroupSpace at creation directly. Can't be moved.

**Comment by flvndvd** [comment]
I guess this is done @tdraier ?
