### ISSUE TITLE
[UX] - Fix: Browser back in assistant builder

### ISSUE THREAD

**Issue by JulesBelveze** [dust-tt/dust#6544]
Browser back should ideally bring user back the previous state (from "select data source" to "assistant builder", from "select a Notion data source" to "select data source" and so on)

**Comment by Duncid** [comment]
@PopDaph I think you tackled this one did you not?

**Comment by PopDaph** [comment]
iirc I fixed part of it, there was still a bug left on the datasource modal but that is supposed to disappear with vault since we're reworking this modal so we agreed to keep living a bit with it
