### ISSUE TITLE
Improve Error handling on connector's API

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6555]
See https://github.com/dust-tt/dust/pull/6556

**Comment by spolu** [comment]
@flvndvd can you provide more context. Quite cryptic from reading the PR description?

**Comment by flvndvd** [comment]
IIRC, the issue is that front swallows connector's API status code, and default to 5xx which in many different places yields an error. A specific example of this is listing Confluence spaces/Google Drive drives when the token has been revoked but does not need to be refreshed, it yields a 5xx where as we should have a proper status code propagated from connectors so the user can re-authorize.

**Comment by spolu** [comment]
Worked on by @fontanierh closing
