### ISSUE TITLE
Improve Poke search

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6653]
Improve Poke search so:
- it matches on domain name (we can use membership table to start)
- sort by Enterprise > Pro > Friend & Family > Free
- display the most recent sign ups by default instead of the list of unsorted workspaces.

**Comment by flvndvd** [comment]
@Fraggle last improvements are in https://github.com/dust-tt/dust/pull/6510.

**Comment by spolu** [comment]
(closing as marked as done)
