### ISSUE TITLE
[Groups infra] Fetch right groups/users when calling from Slack.

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6664]
To whitelist a Slack workflow, we aim to assign it to a specific group or vault. This involves the following steps:

- Implement support for an `x-dust-group-ids` header on the public API endpoints used for creating conversations and associating actions (such as new messages, etc.).
- Implement support for an `x-dust-group-ids` header on the public API endpoint used to run a Dust app. 
- Remove the existing `x-dust-user-id` header (implemented in https://github.com/dust-tt/dust/pull/6648).

When a system key is used as the API key and this header is present, an Authenticator object should be created with the specified groups. This is necessary to ensure that access to a data source or data source view can consistently be associated with a group.

**Comment by lasryaric** [comment]
Done.

**Comment by flvndvd** [comment]
Re-opening until we fix the gap 😉

**Comment by flvndvd** [comment]
This is done @lasryaric, right?

**Comment by lasryaric** [comment]
We still have [some](https://app.datadoghq.eu/logs?query=%28%22No%20access%20to%20data%20source%20view.%22%20OR%20%22No%20access%20to%20data%20source.%22%29%20&agg_m=count&agg_m_source=base&agg_t=count&cols=service%2C%40workflowName%2C%40activityName%2C%40error.__is_dust_error&event=AgAAAZHVy0rrOAItlwAAAAAAAAAYAAAAAEFaSFZ5MWgwQUFEYlZoanhxNkxjS2dBWgAAACQAAAAAMDE5MWQ1Y2ItNWQzZi00MzY3LWJlYWUtNzFlNTQ5NTY5M2Fh&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=%40duration%2Cdesc&viz=stream&from_ts=1725856224167&to_ts=1725870624167&live=true)... Looking into it ASAP.

**Comment by flvndvd** [comment]
Fixed in https://github.com/dust-tt/dust/pull/7210.
