### ISSUE TITLE
Handle groups/vaults permission for Slack workflow and guests

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6702]
See thread [here](https://dust4ai.slack.com/archives/C050A0S2Z7F/p1723043361046739).

**Comment by spolu** [comment]
We likely want indeed to tie the workflow to a group at setup time (when we whitelist it) 👍

**Comment by flvndvd** [comment]
Duplicated of https://github.com/dust-tt/dust/issues/6664#issuecomment-2312448791.
