### ISSUE TITLE
Improve table headers detection

### ISSUE THREAD

**Issue by tdraier** [dust-tt/dust#6782]
When upserting a table we usually tries to detect the headers by taking the first non empty row. This is often inefficient, as the headers can be on another row.

We could use a dustapp to detect more accurately the headers.

discussion here : https://dust4ai.slack.com/archives/C050SM8NSPK/p1723817681344219

example dust app : https://dust.tt/w/0ec9852c2f/a/phqtuUSqcy

**Comment by flvndvd** [comment]
The main issue with a dust app is that it does not contain any lib to handle CSV parsing properly. So the question is how good models are to find headers?

**Comment by tdraier** [comment]
> The main issue with a dust app is that it does not contain any lib to handle CSV parsing properly. So the question is how good models are to find headers?

Actually it does not receive csv but json. I will add more examples in the dataset, but it already works well in finding or guessing headers : https://dust.tt/w/78bda07b39/a/OJSd3KpoDU .
