### ISSUE TITLE
[Groups UI] Add overflow menu actions in data source document item

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6785]
![Image](https://github.com/user-attachments/assets/28e12c18-e78b-4315-8efb-ad23cd6e72ba)

This should display view/link and prevent clicking on leaf items.

**Comment by flvndvd** [comment]
⚠ This one https://github.com/dust-tt/dust/issues/6784 needs to be done before.

**Comment by PopDaph** [comment]
@tdraier so this task includes handling edition/deletion of folder/website that are accessible from the overflow menu?
