### ISSUE TITLE
[Groups UI] Support add data in vaults

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6791]

**Comment by PopDaph** [comment]
@flvndvd this task is about implementing adding data in vaults for all "types" of datasources right? 

-> Attaching managed ds in a vault (selects in a tree and it creates views)
-> Creating a website in a vault (this creates the website inside the vault, no view).
-> Creating a folder in a vault (this creates the website inside the vault, no view).

⬆️ Could you confirm this is what we want?

**Comment by flvndvd** [comment]
> @flvndvd this task is about implementing adding data in vaults for all "types" of datasources right?
> 
> -> Attaching managed ds in a vault (selects in a tree and it creates views) -> Creating a website in a vault (this creates the website inside the vault, no view). -> Creating a folder in a vault (this creates the website inside the vault, no view).
> 
> ⬆️ Could you confirm this is what we want?

This is indeed about supporting adding data to any vaults. All data sources are now associated to a view.

**Comment by PopDaph** [comment]
Managed data: https://github.com/dust-tt/dust/pull/6838/files
Folders: https://github.com/dust-tt/dust/pull/6850. 
Websites: WIP

**Comment by PopDaph** [comment]
Edition/deletion is in another task:  https://github.com/dust-tt/tasks/issues/1199
