### ISSUE TITLE
[Groups UI] Connect data source

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6795]
Implement the connection data source flow based on this [design](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=8487-51609&t=r6bkNDUt7DHKcJYN-4).

**Comment by PopDaph** [comment]
What is this task about? 🙏

**Comment by flvndvd** [comment]
Done @PopDaph

**Comment by flvndvd** [comment]
Duplicated of https://github.com/dust-tt/dust/issues/6905.
