### ISSUE TITLE
Add CTA to export viz as screenshot

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6822]
We use models to create React code, which can then be rendered as part of an agent's message. This is particularly useful when dealing with data. We should consider adding a feature to export the generated data as a PNG file.

![DemoViz](https://github.com/user-attachments/assets/54518c25-e6d8-4e92-84e1-cc22a2a3cb53)

**Comment by spolu** [comment]
closing as mostly on-site used

**Comment by flvndvd** [comment]
Do we plan to ship it at some point, still?

**Comment by Adugre** [comment]
Alan, Kyriba & Converteo asked about it as well - can you update me on status? Ty!
