### ISSUE TITLE
[Vaults UI] Plumbing for view to see a document

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6900]
Use the new `DataSourceViewDocumentModal` in the overflow menu of the list item.

**Comment by PopDaph** [comment]
@flvndvd are you already working on this? 
I realize the one of the card I created is partly a duplicate of this one: https://github.com/dust-tt/tasks/issues/1238.

**Comment by flvndvd** [comment]
Yep I shipped the component and just miss a few places to use it.

**Comment by PopDaph** [comment]
Nice! Then I unassigned myself and assigned you to the other task. 
Since this one does not have a real description I'm not sure the overlap was 100% between both task so I'll let you check and add the missing things if any 🙏🏻
