### ISSUE TITLE
[Vaults UI] Add Connection management screen in "Data Sources" tab

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6905]
We should move the fetch of data sources/data source views outside of the `getServerSideProps` to avoid the need to reload. SWR is the way to go here!

**Comment by philipperolet** [comment]
👋 @flvndvd hey, did you assign it to me? (history says self assigned only because I turned it into an issue, but I did not create the card nor assign)

No prob doing it, but I was under the impression someone else had taken it on (@PopDaph maybe)? so wanted to check

**Comment by PopDaph** [comment]
I did not take this one!

**Comment by flvndvd** [comment]
Yep I did assign it to you based on our discussion from this morning.

**Comment by philipperolet** [comment]
Our discussion was in regard to breadcrumbs / parents visibility, which is an other card (that I did self assign). 

I have no recollection of leading discussion or taking on this card, but good for me :) will come to you for context when I get to it
