### ISSUE TITLE
[Vaults UI] Improve navigation to show all the parents

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6906]
See description below (screenshot)
This includes creating an endpoint to get the full parents hierarchy for a content node

We should ensure this **fixes an issue for Google Drive breadcrumbs** in which the ellipsis is not shown, see #6889 (this should be done automatically by using the new endpoint mentioned above)

**Comment by philipperolet** [comment]
@Duncid here the likely 80/20 pareto-optimal solution seems to me to do like google drive, allow submenu in breadcrumbs

![Image](https://github.com/user-attachments/assets/d7d3cb18-54e3-48de-b07c-b2359bdecc1d)

WDYT? Good or would you like smth else?  I would of course take the opportunity to move the Breadcrumbs componnent to sparkle 😉

**Comment by Duncid** [comment]
Works for me.

I'd keep the root thought (Company Data > ... > folder > folder) to be extra clear on what data source user is impacting.

**Comment by philipperolet** [comment]
Absolutely
