### ISSUE TITLE
[Vaults UI] Add developer tools in PP (Profile Picture) Menu

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6912]
This menu should contains "Developer Tools" which opens a full screen Modal and display tabs "Providers" and "App Secrets" from the current "Developer Tools" menu item.

**Comment by PopDaph** [comment]
Closing since we don't want to do that, creating new cards for the dust apps tasks discussed here: https://dust4ai.slack.com/archives/C050SM8NSPK/p1724686850587629
