### ISSUE TITLE
[Vaults Infra] Fix Microsoft documents parents

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6944]
The current standard for the parents array in a Document is set as [currentElement, ..., n], where n represents the oldest ancestor. At the moment, there is a reverse operation that inverts this order for Microsoft. This needs to be corrected to ensure we can accurately enforce view restrictions when displaying content nodes and their parent hierarchy for a view.

https://github.com/dust-tt/dust/blob/8e4bcad7c80ba6dc99046d64b8c29e52b3725c63/connectors/src/connectors/microsoft/temporal/file.ts#L290-L298

**Comment by philipperolet** [comment]
Fixed by #6976 and #7001
