### ISSUE TITLE
[Vaults Infra] Double check that Intercom follow parent convention

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#6945]
The current standard for the parents array in a Document is set as [currentElement, ..., n], where n represents the oldest ancestor. Can we double check that Intercom help centers and conversations are properly implementing this behavior.

**Comment by PopDaph** [comment]
Is okay for conversation since only one parents. 
For help center articles not good since we use a field provided by intercom to get the parents so we can't trust it. We need to edit the logic in sync_help_center.ts
