### ISSUE TITLE
Assistant Creation: Suggested Handles Include Existing Assistant Names

### ISSUE THREAD

**Issue by cadinette** [dust-tt/dust#6987]
#### Description
During the assistant creation process, suggested assistant handles sometimes include names that are already in use. 

When one of these existing handles is selected, an error is displayed. 

Existing assistant handles probably shouldn't be suggested, as they will always result in an error when attempting to create or modify an assistant.

#### Relevant Test Cases
* [I can use a suggested assistant handle when creating an assistant](https://docs.google.com/spreadsheets/d/1m0PYXdSEwRkvrDsKfs-_V1VZSBZeBwV25_ANR4cAgDc/edit?gid=0#gid=0&range=C24)

#### Steps to Reproduce

1. Start the assistant creation process.
2. Review the suggested assistant handles.
3. Select a handle that is already in use by another assistant.
4. Attempt to proceed with the creation or modification.
5. Observe that an error is displayed due to the handle being in use.

**Comment by PopDaph** [comment]
Task prioritization: https://dust4ai.slack.com/archives/C050SM8NSPK/p1725960262643199
