### ISSUE TITLE
File Upload: Conflicting Information on Supported File Types for Chat

### ISSUE THREAD

**Issue by cadinette** [dust-tt/dust#6988]
#### Description
There is conflicting information regarding the file types supported for upload in chat. When hovering over the paperclip icon, it indicates that .md files are allowed, but when dragging a file into the chat, a message appears stating that only `.doc`, `.pdf`, and `.txt` files are supported. 

Additionally, attempts to upload `.md` or `.doc` files fail, suggesting these file types may no longer be supported.

#### Relevant Test Case(s)
* [I can upload and start a chat with .md or .doc files](https://docs.google.com/spreadsheets/d/1m0PYXdSEwRkvrDsKfs-_V1VZSBZeBwV25_ANR4cAgDc/edit?gid=0#gid=0&range=C8)

#### Steps to Reproduce:

1. Hover over the paperclip icon in the chat to view the supported file types.
2. Attempt to drag and drop an `.md` or `.doc` file into the chat.
3. Observe the message stating that only `.doc`, `.pdf`, and `.txt` files are supported.
4. Attempt to upload a `.md` or `.doc` file and observe that the upload fails.

**Comment by flvndvd** [comment]
Fixed in https://github.com/dust-tt/dust/pull/7019.
