### ISSUE TITLE
Chat Deletion: Deleted Conversations Remain Visible Briefly and Cause UI Issues

### ISSUE THREAD

**Issue by cadinette** [dust-tt/dust#6989]
#### Description
When deleting a chat conversation, the system redirects to the home page, but the deletion process takes several seconds to complete. 

During this period, the deleted conversation remains visible and clickable. If the deleted chat is clicked, an error message appears, and the chat user interface becomes distorted, squashing to the bottom half of the page.

The page should immediately reflect the deletion, ensuring that deleted conversations are no longer visible or clickable.

#### Videos/Screenshots
[Loom](https://www.loom.com/share/fa1c64b3487d455580f479247cfefa80)

#### Relevant Test Case(s)
* [I can delete a chat conversation](https://docs.google.com/spreadsheets/d/1m0PYXdSEwRkvrDsKfs-_V1VZSBZeBwV25_ANR4cAgDc/edit?gid=0#gid=0&range=C21)

#### Steps to Reproduce

1. Delete a chat conversation.
2. Observe that the system redirects to the home page, but the deleted chat remains visible in the chat history.
3. Click on the chat that was just deleted.
4. Observe the error message displayed and the distorted chat conversation UI.

**Comment by flvndvd** [comment]
Fixed in https://github.com/dust-tt/dust/pull/7033.
