### ISSUE TITLE
/parents API returns 200 instead of 404 when the document to update does not exist

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#7009]
Example curl below
```
curl -X POST 'http://localhost:3000/api/v1/w/nX1GBNVVMN/data_sources/managed-microsoft/documents/FAKE_DOC_OOOH/parents' \
-H 'Authorization: Bearer ***' \
-H 'Content-Type: application/json' \
-d '{ 
"parents": [ "p1" ]
}'
```
API should return 404

**Comment by Fraggle** [comment]
@philipperolet

After digging, it seems that it comes down to [this method](https://github.com/dust-tt/dust/blob/b0d41ba52af414432b2e6428d2f8739b0dbacd84/core/src/data_sources/data_source.rs#L419) in core api that returns OK regardless if the qdrant query modified anything or not.

It seems coherent with the other methods in the file so I'm reluctant to touch it until I get @spolu's feedback.

**Comment by philipperolet** [comment]
not important enough, closing
