### ISSUE TITLE
[Vaults UI] Add pagination on static data source items

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#7053]
We used to have pagination on static data sources in the previous UI, we should re-implement it. The back end already support it, it's purely Front-end.

**Comment by JulesBelveze** [comment]
Heads up: for now we only return the total number of elements when dealing with `documents`

**Comment by flvndvd** [comment]
We can probably leverage tan stack pagination check [this](https://tanstack.com/table/latest/docs/guide/pagination#pagination-apis).

**Comment by flvndvd** [comment]
Done in https://github.com/dust-tt/dust/pull/7188.
