### ISSUE TITLE
[Connection Management] - Connection setup screens

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#7354]
Figma: [here](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=8507-45257&t=k0UeNRa9SLyAup4g-4)

**Details:**
- We have a nice looking title bar
- Read documentation are in the title
- The “IMPORTANT” notice is only visible in situations were VAULTS are not available (We do not need them in Vault situation)

![Image](https://github.com/user-attachments/assets/9fd21ff3-c3f6-4200-a889-863194e9400d)

Implement those screen for connection.

**Comment by spolu** [comment]
closing as marked as done
