### ISSUE TITLE
[Vaults UI] Implement the "Data sync has started" screen

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#7361]
When adding connections to a workspace, data should not be available outside of the system vault. It should require one admin step to make it available in a vault (including the workspace one).

A new screen is required in the connection flow to provide information about vault. Design is [here](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=10016-81544&node-type=frame&t=0Is6G6nLOEVq5D9J-0).

⚠️ For now we will implement only the "Connect an un-mapped" case (I left a comment on it with more details).

<img width="719" alt="image" src="https://github.com/user-attachments/assets/b2cba5a1-b107-41ef-8c38-2171438d858a">

**Comment by spolu** [comment]
Wording "Data access is limited to Admins by default" is not very accurate IMHO the admin does not really have access to that data it can only operate on it. Probably some noodling to do here, not blocking in any case.
