### ISSUE TITLE
Timeout errors from Browserless API interrupt runs

### ISSUE THREAD

**Issue by tmontana** [dust-tt/dust#74]
Error with HTTP status 400 and body "Navigation timeout of 30000 ms exceeded"

**Comment by spolu** [comment]
Yeah this one is annoying as it is handled as a run error and the whole run is interrupted preventing the rest of inputs to complete.

We can extract that error and return a JSON to represent it. That means apps would have to gracefully handle that state which requires more logic.

**Comment by tmontana** [comment]
Any way to adjust timeout length?

**Comment by spolu** [comment]
I think these pages are just going to timeout whatever value you put. But to answer your question, not at the time, need to add that as a parameter to the browserless block.

**Comment by spolu** [comment]
30s is already... a lot.

**Comment by aickin** [comment]
Worth noting that it's 30s not just for downloading the page, but for downloading all the scripts, images, etc., *and* running all the JavaScript until the page settles down. I also suspect but am not sure that:
* Browserless uses pretty underpowered machines
* The browsers start with nothing in cache
* Low usage accounts may have low numbers of simultaneous browsers spun up until they hit timeouts

**Comment by spolu** [comment]
Agreed. But some pages just fail repetitively and consistently. The first fix is really to return errors as a result instead of interrupting the run I think?

**Comment by tmontana** [comment]
I can confirm there is something badly implemented here.  I ran my own code in python using browserless API as a test and never getting any errors from default parameters.

**Comment by spolu** [comment]
Nice. Can you share some urls where you see discrepancies ?

**Comment by tmontana** [comment]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/18288458/202865106-d84f349f-24bb-462f-b10e-6d12da89b8c2.png">

**Comment by tmontana** [comment]
https://www.cnn.com/2020/02/21/business/wells-fargo-settlement-doj-sec/index.html

**Comment by tmontana** [comment]
This happens a lot

<img width="932" alt="image" src="https://user-images.githubusercontent.com/18288458/202865188-7c63a222-bb8c-486d-a9db-86d12a0c6654.png">

**Comment by spolu** [comment]
Yes I had the same issue on CNN. Will investigate :+1:

**Comment by spolu** [comment]
Added 16s timeout instead of 30s and the networkidle2 option, should solve most issues, let me know if that's not the case :+1:

**Comment by bcjordan** [comment]
I still have this error for many webpages, is there any way to code around a solution to allow it to allow failures or have them null in the results array? In instances where you're navigating to multiple search result pages to parse there's still good data in the other pages

**Comment by spolu** [comment]
@bcjordan we've added a configuration flag (only available behind API at this stage) to have the browser block return an error object instaed of erroring the run[0]:

You need to pass in your API call: `config: { "BROWSER_BLOCK_NAME": { "error_as_output": true } }`

[0] https://github.com/dust-tt/dust/blob/main/core/src/blocks/browser.rs#L91-L100

**Comment by bcjordan** [comment]
@spolu oh that's perfect, thanks so much!
