### ISSUE TITLE
Display both tables and documents under the same view

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#7426]
See [thread](https://dust4ai.slack.com/archives/C050A0S2Z7F/p1726498434377949).

**Comment by JulesBelveze** [comment]
There's already a ticket here https://github.com/dust-tt/tasks/issues/1272

**Comment by flvndvd** [comment]
Good catch @JulesBelveze , let me consolidate everything in the one you shared.

**Comment by flvndvd** [comment]
Consolidated in https://github.com/dust-tt/tasks/issues/1272.
