### ISSUE TITLE
[Remote Databases] [Step 0] Add ability to create secrets in `oauth`

### ISSUE THREAD

**Issue by fontanierh** [dust-tt/dust#7449]
`oauth` should be extended to allow creating "plain text" secrets.
API should look something [like this](https://www.notion.so/dust-tt/Design-Doc-Remote-Databases-e28217bc290b465a9e892ab4c20b0da6?pvs=4#97caad9f828d4e90bf7218320b93175e)

**Comment by fontanierh** [comment]
Good to close this one right @Fraggle  ?

**Comment by Fraggle** [comment]
@fontanierh sorry didn't see your message, yes of course.
