### ISSUE TITLE
getting errors when google result includes .pdf files

### ISSUE THREAD

**Issue by tmontana** [dust-tt/dust#75]
example:

BrowserlessAPIError: Error with HTTP status 400 and body "net::ERR_ABORTED at https://www.juniper.net/content/dam/www/assets/factsheet/us/en/corporate-social-responsibility-report-2021.pdf"

**Comment by spolu** [comment]
Yeah I think there is not much we can do here. You should filter out URL that are PDFs when talking to browserless, and we can of course think in the future of adding a way extract info from PDFs. But that's low on the priority list quite obviously.

Will close for now.
