### ISSUE TITLE
Server side pagination alter the browsing experience

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#7527]
It seems we've recently transitioned to fully server-side pagination for browsing content from data sources. This change has made the search bar at the top of the page useless as it only search in the current active page, significantly hindering the browsing experience. With a page size limited to only 25 items, users typically want to quickly find a specific document and will naturally head to the search input first. You can easily experience the issue [here](https://dust.tt/w/0ec9852c2f/vaults/vlt_ZqMdUAzI0OTf/categories/managed/data_source_views/dsv_EjhZxkIuTYmG?parentId=unknown#?tablePageIndex=0&tablePageSize=25&viewType=documents) by searching for "Edouard," a record which exists but is located on page 4.

**Comment by flvndvd** [comment]
FYI @Duncid.

**Comment by tdraier** [comment]
I would suggest that we remove pager, and replace with infinite scroll with increased default page size.
Interesting thing with infinite scroll is that filtering will automatically trigger the load of new pages if not enough results are available in the current page (we'll reached the end of the table)

**Comment by Duncid** [comment]
works for me

**Comment by tdraier** [comment]
Server-side pagination disabled for now, followup in  https://github.com/dust-tt/dust/issues/7566
