### ISSUE TITLE
[BUG] Assistant builder state with Websites

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#7535]
- Create an assistant with a page from a website that is not the top node
- Save it (the assistant)
- Close the assitsant builder
- Reopen it
- Visit the search actions: children are gone

**Comment by spolu** [comment]
I was not able to reproduce today...

**Comment by spolu** [comment]
Do we know what it was?

**Comment by Fraggle** [comment]
> Do we know what it was?

@spolu I had the error locally as well and [traced it up to a point](https://dust4ai.slack.com/archives/C07L7A5K2NM/p1726857172825969) where it seems it was not returning any nodes. I passed the torch to @flvndvd as he knew more about this part, and he couldn't repro either.

**Comment by spolu** [comment]
Roger that. Weird. I'll keep an eye on it as we were multiple to repro at some point 👍
