### ISSUE TITLE
[Bug] Connection management tree uses the data source view filtering

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#7616]
I filtered the github connection on code only in the company data

then naivated to connection management. I see issues there in the main screen but not in the left tree

![Image](https://github.com/user-attachments/assets/e144062d-bb76-4e7e-a89f-f5359680c9a4)

**Comment by tdraier** [comment]
I cannot reproduce, the screenshot here shows the "company data" vault, not connection management ?

**Comment by spolu** [comment]
Sorry wrong screenhot 
![Screenshot from 2024-09-23 13-39-25](https://github.com/user-attachments/assets/42f86c2e-66e6-40de-8a98-f1cdd7dc0781)

**Comment by spolu** [comment]
Not an issue due to the fact that Issues is not expandable
