### ISSUE TITLE
[Polish] rename "Add data from connections" to "Filte data from connections" for the global vault

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#7617]
![Image](https://github.com/user-attachments/assets/07cf8c50-f52e-49a7-926e-991051fa71eb)
![Image](https://github.com/user-attachments/assets/f4e04357-c480-4001-a467-6d9e3d736cd6)

Since we have everything by default manybe we should name this one "Filter" for the global vault?

Title of the modal should be align and not say connected datasources but connections

**Comment by spolu** [comment]
Context https://dust4ai.slack.com/archives/C07L7A5K2NM/p1727091183380749?thread_ts=1727090273.269319&cid=C07L7A5K2NM

**Comment by Duncid** [comment]
> Since we have everything by default manybe we should name this one "Filter" for the global vault?

That's transitional right?
I mean with vault won't be the case any more?

**Comment by spolu** [comment]
@Duncid even with vault we'll continue creating a view that includes everything in the workspace data by default.

So after creating a connection, by default everything will be included in the workspace data by default so most action taking in that screen will be about filtering more than adding?
