### ISSUE TITLE
[Polish] as s User I should be able to request a website

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#7618]
![Image](https://github.com/user-attachments/assets/2ed5256d-2e1c-4f6e-beb1-9b57fe665079)

**Comment by JulesBelveze** [comment]
@spolu Currently the way we handle "Data Request" for a given data source is that we send an email to the admin of that data source.

In the scenario of requesting a new website, would should we send the email to?

**Comment by spolu** [comment]
I presume the admin as well no?

**Comment by JulesBelveze** [comment]
I might be missing something here, but there's no admin as there's no data source set up yet, right?

**Comment by spolu** [comment]
Ah I see you mean there is no dedicated admin. And I agree it's unclear which admin we should send that to.

I presume fine to close for now :+1:
