### ISSUE TITLE
[Favorites] UX: change assistant modal menu to button bar

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#7707]
See figma below

Link to [Figma](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=7033-45013&t=gUYgBFDqdJbosTa1-4)
Link to [Notion page](https://www.notion.so/dust-tt/Assistants-Favorites-50277abe540b4d5480f2f78e119c31fb?pvs=4)

**Comment by aubin-tchoi** [comment]
Incorrectly tagged and merged in #8017
