### ISSUE TITLE
[Favorites] [Nice-to-have] UX: mentionning gets ready faster by loading only favourites first

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#7712]
This is an extra from @pr. Sometimes, we have to wait before mentioning becomes available (that the call to getAgentConfig finishes). If we grab favorites we could fasten this up

Link to [Figma](https://www.figma.com/design/QOxHwppG64GtPocpDhS6Y7/Product?node-id=7033-45013&t=gUYgBFDqdJbosTa1-4)
Link to [Notion page](https://www.notion.so/dust-tt/Assistants-Favorites-50277abe540b4d5480f2f78e119c31fb?pvs=4)

**Comment by spolu** [comment]
Let's not have "Nice to Have", we know how they end. As a DRI you have to make a call. It's in or it's out :pray:

**Comment by philipperolet** [comment]
All right!

**Comment by spolu** [comment]
tyty
