### ISSUE TITLE
[New Sparkle] - Add new effects

### ISSUE THREAD

**Issue by JulesBelveze** [dust-tt/dust#8062]
- [ ]  Adding to Sparkle a similar effect [to rainbow button](https://magicui.design/docs/components/rainbow-button)
    - Just the effect, not the button. Ideally, applicable to a div. Idea is to bring attention to the input bar in empty conversation mode.
- [ ]  Adding to Sparkle an [Animated Shiny Text](https://magicui.design/docs/components/animated-shiny-text) effect

**Comment by philipperolet** [comment]
Done #8554
