### ISSUE TITLE
Preview has a loader always unless expanded in Query Tables action panel

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#8063]
![Image](https://github.com/user-attachments/assets/3b01f2e3-65d3-4fc9-a896-569fbf63e873)

If you don't do anything the loader is there. It disapears if you expand the preview. Reappear if you collapse it again I believe.

**Comment by tdraier** [comment]
The loader stays here until streaming is ended - it's not depending on the fact you're clicking on collapse/expand

![Image](https://github.com/user-attachments/assets/35268acc-6bbc-4ac7-a627-d52e44fdfaf5)

**Comment by spolu** [comment]
Ok fair. A bit misleading when you're in the modal but I guess fine.
