### ISSUE TITLE
Refactor how we store `group_ids` on conversations and agent_configurations

### ISSUE THREAD

**Issue by flvndvd** [dust-tt/dust#8268]
Today's `group_ids` on `conversations` and `agent_configurations` performs a conjunction on all group ids, this is too limiting as one space can have more than one group, we should perform disjunction between a space's groups.

To achieve this we need to update the way we store those to store a List of List of groupIds.

**Comment by Fraggle** [comment]
I don't understand the problem (and therefor, the solution).

**Comment by flvndvd** [comment]
The problem is that a space can have more than one group (we apply a disjunction/OR on the groups of a space). At the moment we only store a simple array of group ids on the `agent_configurations` and `conversations` on which we run a conjunction/AND. This does not work as a user is not expected to be in all space's group only one is enough.

We want to move towards a pattern that makes this easy to apply the same logic on `agent_configurations` and `conversations`.
