### ISSUE TITLE
[Zendesk] Correctly open the `ConnectorPermissionsModal` at the end of the auth workflow

### ISSUE THREAD

**Issue by aubin-tchoi** [dust-tt/dust#8424]
- Currently, when we setup Zendesk for the first time the modal disappears after setting up OAuth and we never get a chance to select what to sync.
- The modal should stay in place.

# Steps to reproduce

- If a Zendesk connection is already setup, delete it using the button in poke.
- Add a Zendesk connection with the following subdomain: d3v-dust (credentials in 1P).

**Comment by Fraggle** [comment]
@aubin-tchoi do you plan on doing this one ? (it's a shame we can't remove the zendesk column 😛 )

**Comment by aubin-tchoi** [comment]
not really, was gonna wait until it bothered someone so much that they did it 😇

**Comment by spolu** [comment]
Which Zendesk column?

**Comment by spolu** [comment]
Ah the go/todo one.

**Comment by albandum** [comment]
Should that stay in Olympus? That's a user-detectable broken thing we know about, usually is eng-runner more than olympus no?

**Comment by aubin-tchoi** [comment]
yes, we have plans to TAL on monday with @Fraggle
