### ISSUE TITLE
Assistant Builder: navigation bug

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#8536]
Go to personal tab. Edit an assistant. Close the assistant builder.

The URL goes back to https://dust.tt/w/0ec9852c2f/assistant/new#?selectedTab=personal but the page does not update. If you click another time it goes back to whatever was before in your history.

It does work well when not moving to the personal tab first.

**Comment by PopDaph** [comment]
Indeed, nasty one 😮

**Comment by PopDaph** [comment]
Now that the extension is submitted I wanted to go back to this bug, but I can't reproduce anymore.
I don't know who fixes it but it is fixed!! Thank you mystery bug solver

**Comment by spolu** [comment]
Seems like it indeed. The edit flow changed from the conversation page (no direct edit, modal instead which means we change the URL which means we go back to the modal)
