### ISSUE TITLE
[Ext] Handle capture when the content is not text/html [[[NOT MVP]]]

### ISSUE THREAD

**Issue by tdraier** [dust-tt/dust#8816]
Right now w have the include content button, which does nothing - we should just attach the file the conversation if it's something that can be handled. 
It would be nice to have a different action for that, and enable/disable actions dependin on the current tab.

**Comment by PopDaph** [comment]
Closing since not MVP, referenced on the extension feedback page: https://www.notion.so/dust-tt/Centralized-Feedback-about-Chrome-extension-15028599d941801b87e8dd93a8bad8be
