### ISSUE TITLE
Fix loading state in the ActionDetails drawer (as well as action verb)

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#8924]
When actions are all done and the model started generating tokens the loading state is still shown as loading in the action drawer + the last action verb is shown instead of "Tools Inspection"

I think it's tricky to solve as we never know for sure if a generation is a in-between action generation or a final generation in general.

Goal of the issue is to fix it completely or at least improve the situation

**Comment by Fraggle** [comment]
Not sure ton understand if it's specific to JIT or not (Olympus?).
