### ISSUE TITLE
Fix Favorite button

### ISSUE THREAD

**Issue by spolu** [dust-tt/dust#8933]
When setting a favorite the button does not get disabled and while the operation is done it's unclear to the user if the favorite was set/unset or no.

Fix: disable favorite button while the request is run

**Comment by spolu** [comment]
Also when an assistant is set as favorite, hovering change the visual of the button to unset which is wonky

**Comment by spolu** [comment]
Thank you!!

**Comment by spolu** [comment]
@philipperolet reopening as the UX is still quite off. The disabled state does not live long enough so we see click -> disabled -> enabled (wrong state) -> state change to new state

**Comment by philipperolet** [comment]
Ack. Had tested ofc, and did not have these issues at merge time, but maybe they only occur in laggy circumstances. Will have a look asap

**Comment by spolu** [comment]
tx tx!

**Comment by philipperolet** [comment]
https://dust4ai.slack.com/archives/C050SM8NSPK/p1734675568347479
