### ISSUE TITLE
[KW-search] Align `document_id` with internal IDs (slack)

### ISSUE THREAD

**Issue by aubin-tchoi** [dust-tt/dust#9069]
### Terminology

- Internal IDs: IDs used in the content nodes (connectors).
- parent IDs: IDs used in the column `parents` of core's table `data_source_documents`.
- document_id: ID used in the column `document_id` of core's table `data_source_documents`, notably set when upserting to a data source from connectors.

## Issue

- Related to https://github.com/dust-tt/tasks/issues/1661
- internal IDs have to be aligned with parent IDs otherwise the search won't work.
- we want `parents[0] = document_id`
- we need to align the internal IDs with the `document_id` for KW search since we don't have any kind of `node ID` (it's the document_id).

## Migration Plan

~~To avoid a huge backfill on the `parents` in qdrant, we:~~
~~- change the `document_id` to align it (mostly removing prefixes), we're gonna live with the 2 versions~~
~~- change the upsertion in core to check for both document IDs (if it exists remove the old one and add the new one, otherwise do the right thing)~~
~~- check for other side effect of changing the document_ids (retrieval action, citation).~~

-> We don't do that because the document_id is involved in a hash for GCS and QDrant. Instead we align the parents and internal IDs to the document_ids.

Revised plan:
- in `connectors`: we start upserting parents x2 (both the old and the new format).
- we backfill core (postgres and qdrant) to have parents x2
- in connectors we use the new parents in contentNodes
- in connectors we start upserting only the new parents
- we cleanup core

## Context

- some connectors have a prefix `gdrive-`, `notion-` in the `document_id` but not the `parents`,
- some connectors use prefixes everywhere (Zendesk, Intercom AFAIK), these ones are fiine.
- some connectors use != prefixes between the two (confluence I think).

**Comment by spolu** [comment]
Log created here: https://app.datadoghq.eu/logs?query=service%3Acore%20%22%5BCORE%20REQUEST%20-%20EVENT%5D%20%5BKWSEARCH%5D%20invariant_first_parent_self%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1733836176318&to_ts=1733837076318&live=true

**Comment by spolu** [comment]
Reminder of invariants we're aiming for

- parents = [node_id, parent_node_id, ...] unless parent is null in which case parents = [node_id]

**Comment by spolu** [comment]
I will start handling slack.

Current state:
- we pass parents=[slackChannelId] 
- we don't create folders for slackChannelIds (this is tracked here: https://github.com/dust-tt/dust/issues/9160)

Fix to parents
- pass parents=[document_id, slackChannelId] : this will have no impact on the semantic search or product
- after this has started snapshot the data sources core project and internal id for all slack connectors
- backfill from `core` directly, get all slack documents, update parents in SQL and qdrant

r? @aubin-tchoi

**Comment by aubin-tchoi** [comment]
LGTM

**Comment by spolu** [comment]
`document_id` is now passed as parents as per https://github.com/dust-tt/dust/pull/9252

**Comment by philipperolet** [comment]
should we take the opportunity to add the `slack-` prefix to channels, to uniformize with slack documents and threads?

**Comment by philipperolet** [comment]
(painful IMO but it's now or never)

**Comment by spolu** [comment]
Yeahhhhh I can take it will mark the #9252 as blocked on this one

**Comment by spolu** [comment]
Dump of slack data sources:
[slack_data_sources.json](https://github.com/user-attachments/files/18083604/slack_data_sources.json)
[slack_data_sources.csv](https://github.com/user-attachments/files/18083605/slack_data_sources.csv)

**Comment by spolu** [comment]
Dump of slack data sources to be migrated available here: https://metabase.dust.tt/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7Im5hdGl2ZSI6eyJxdWVyeSI6IlNFTEVDVCBcImR1c3RBUElQcm9qZWN0SWRcIixcImR1c3RBUElEYXRhU291cmNlSWRcIiBGUk9NIGRhdGFfc291cmNlcyBXSEVSRSBcImNvbm5lY3RvclByb3ZpZGVyXCI9J3NsYWNrJyIsInRlbXBsYXRlLXRhZ3MiOnt9fSwidHlwZSI6Im5hdGl2ZSIsImRhdGFiYXNlIjo0fSwiZGlzcGxheSI6InRhYmxlIiwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9LCJ0eXBlIjoicXVlc3Rpb24ifQ==

**Comment by spolu** [comment]
Updated plan of action:

- [x] pass parents=[document_id, slackChannelId, slack-channel-${slackChannelId}]
- [ ] migrate core PSQL and qdrant to have the full parents
- [ ] migrate assistants to rely on the new slack-channel prefixed id
- [ ] remove double write
- [ ] migrate core PSQL and qdrant to have the final version

**Comment by spolu** [comment]
all done
