### ISSUE TITLE
[KW-Search] Update & backfill `folders` for slack

### ISSUE THREAD

**Issue by tdraier** [dust-tt/dust#9160]
See [#8527](https://github.com/dust-tt/dust/issues/8527)

**Comment by spolu** [comment]
Blocked on #9069 (addition of slack prefix in parents tags of slack documents so that the upcoming slack folders are `slack-` prefixed)

**Comment by spolu** [comment]
(unblocked taking)

**Comment by spolu** [comment]
Code complete, migration running
