### ISSUE TITLE
[UX] - Broken citations in thoughts

### ISSUE THREAD

**Issue by JulesBelveze** [dust-tt/dust#9179]
The citations seem broken on the agent thoughts, see screenshot below:

![Image](https://github.com/user-attachments/assets/b9a5594f-3f9c-456b-961f-a00e4f144ecc)

**Comment by spolu** [comment]
@JulesBelveze do you have the conversation URL to test post fix?

**Comment by JulesBelveze** [comment]
https://dust.tt/w/0ec9852c2f/assistant/aFizSLRBk5

**Comment by spolu** [comment]
Gave it a try by adding the directives and plugins to the chain of thought markdown + moving the ContextProvider around the two but something is not happy

**Comment by spolu** [comment]
It's going to be chanlenging to support from 2 sources of text since it relies on "the existence of only one parsing pass". We don't want to temper with the parsing so the best we can do is create a new dummy plugin and directive to simply scrub the citations

**Comment by Fraggle** [comment]
@spolu thanks for taking a shot at this. What's the SITREP here ? Are you owning this ?

**Comment by spolu** [comment]
Not owning it. Based on my exploration I think the best way forward is to have dummy directives and blocks to hide the citations in the chain of thought.

**Comment by Fraggle** [comment]
I must admit it's quite far from my comfort zone (but happy to dig if deemed important).
Is it worth "eng runner" or more like "nice to do" (olympus).

**Comment by spolu** [comment]
I thiiiiiiiiiink we can close it as it's not that bad and not that common. @JulesBelveze let us know if you think otherwise.

**Comment by JulesBelveze** [comment]
Yeah if it's not straightforward let's close it, we'll reopen if it comes back 👍🏼
