### ISSUE TITLE
init/init.sh not running in dust-front Docker image

### ISSUE THREAD

**Issue by andyk** [dust-tt/dust#92]
`front/Dockerfile` currently has 2 `CMD` commands. But Docker only allows one per Dockerfile. So the first one is getting ignored.

https://github.com/dust-tt/dust/blob/eaef34ba33b680ef015cf7a559f9391eef2f9ba9/front/Dockerfile#L9-L12

The first one is the command that sets up the database so this is failing silently and then I got a database error. When I logged into the docker image and ran the init script it fixed things.

**Comment by spolu** [comment]
Hi hi! The Docker has not been maintained. Let me update the README

**Comment by spolu** [comment]
Updated. Let me know if that works for you :+1:

**Comment by Tradunsky** [comment]
Hi @spolu,
I though to contribute docker support for easier setup and found out that it actually existed before this issue:
https://github.com/dust-tt/dust/commit/7743768915b83640110c5b73bfe3a1c9b20c2796

I understand that Docker support would need to be continuously updated with the latest changes to the application, but just wanted to ask what's your opinion to have docker support in general?

**Comment by spolu** [comment]
Last support rotted pretty quick. Happy to revisit if useful to you :+1:

**Comment by Tradunsky** [comment]
Sorry, just noticed your reply. 

I was able to spin it up on ubuntu:
```
# Install Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -y

# FIX: error: linker `cc` not found
sudo apt update
sudo apt install build-essential
# FIX: Could not run `\"pkg-config\"
sudo apt install pkg-config
# FIX:  could not find system library 'openssl'
sudo apt install libssl-dev

# Install dust CLI
git clone https://github.com/dust-tt/dust.git
cd dust/core
cargo build --release --bin dust
alias dust="$(pwd)/target/release/dust"

# Install nodejs
sudo apt install nodejs

# Start rust web app
cargo run --bin dust-api >> dust-api.log &

# Front end app
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
nvm install v19.6.0
nvm use v19.6.0

cat <<EOF >> .env.local
URL=http://localhost:3000

NEXTAUTH_URL=$URL
NEXTAUTH_SECRET=25da29db5485fcd27d2f671c5e28d5df8f325e9470c36cb6bf0a9d19c662255a

FRONT_DATABASE_URI=sqlite:front_store.sqlite
XP1_DATABASE_URI=sqlite:xp1_store.sqlite

GITHUB_ID=47ec837fcbac1c6f1690
GITHUB_SECRET=d59af0da231fc697d7dd8d3002ed1d9765e11c7f

DUST_API=http://localhost:3001

THUM_IO_KEY=0-Foo
GA_TRACKING_ID=Foo
EOF

XP1_DATABASE_URI=sqlite:xp1_store.sqlite FRONT_DATABASE_URI=sqlite:front_store.sqlite ./init/init.sh

npm run dev &
```
