### ISSUE TITLE
[KW-Search] Ensure parents are in correct order for google_drive and do a script to fix it

### ISSUE THREAD

**Issue by tdraier** [dust-tt/dust#9250]
Parents are now inserted in correct order (`[ node_id , parent, grandparent, root ]`), but current data in production is not always valid - we have `[ node_id , root, grandparent, parent ]` ( or `[ table_id, file_id , root, grandparent, parent ]` for tables )

To be checked by file/folder Id seems to start with 1 and drive id by 0, so we can get some invalid entries here :

```
select * from tables where table_id like 'google%' and parents[3] like '0%' order by created desc limit 100;
select * from data_sources_documents where document_id like 'gdrive%' and parents[2] like '0%' order by created desc limit 100;
```

**Comment by tdraier** [comment]
Found another inconsistency : on some csv files, parents are `[ gdrive-nodeId , nodeId , ... ]` because of the code that was removed here https://github.com/dust-tt/dust/pull/9309

**Comment by philipperolet** [comment]
As per IRL, #9250 and #9256 will be handled at the same time, using the common migration script of #9277

**Comment by tdraier** [comment]
Most parents have been fixed. We still have some entries which were not rewritten, as the parentId does not match any entry in google_drive_files - it's not really possible to safely rewrite the full parent list in that case.
Issues was only on tables, because of reverse() in parents at some point, which has now been removed (for documents, we had a second reverse reordering the values).
