### ISSUE TITLE
[KW-search] Google Drive: Standardize parents and internal ID

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#9256]
Goal is to ensure for **Google Drive** that:
-  Parent ids used in the parents[] array in core data_source_nodes and internal ids from connectors should now match node_id in core data_sources_nodes (= document_id for docs, table_id for tables, folder_id for folders);
- the convention that parents[0] = node_id should be enforced.

The connector should be thoroughly inspected. If there is a convention mismatch, fix it; explained in details in https://github.com/dust-tt/dust/issues/9069

As noted here : https://github.com/dust-tt/dust/pull/9261/files#r1879852550 , we should add parent_id parameter in upserts as part of this card once parents are standardized.

**Comment by philipperolet** [comment]
we'll need to migrate folders too here since they're already written on

**Comment by tdraier** [comment]
Found a lot of inconsistencies in existing parents array, may need to be fixed first :  [#9250](https://github.com/dust-tt/dust/issues/9250)

**Comment by philipperolet** [comment]
As per IRL, #9250 and #9256 will be handled at the same time, using the common migration script of #9277

**Comment by tdraier** [comment]
Folders migrated to new parents and inconsistencies fixed with https://github.com/dust-tt/dust/issues/9250 

Added google migration in common migration script : https://github.com/dust-tt/dust/pull/9371
