### ISSUE TITLE
[KW-search] Intercom: Standardize parents and internal ID

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#9257]
Goal is to ensure for **Intercom** that:
-  Parent ids used in the parents[] array in core data_source_nodes and internal ids from connectors should now match node_id in core data_sources_nodes (= document_id for docs, table_id for tables, folder_id for folders);
- the convention that parents[0] = node_id should be enforced.

The connector should be thoroughly inspected. If there is a convention mismatch, fix it; explained in details in https://github.com/dust-tt/dust/issues/9069

**Comment by aubin-tchoi** [comment]
Similarly to Zendesk (I deeply thank you @PopDaph), the convention is already respected for this connector.
The same remarks applies as in [#9259](https://github.com/dust-tt/dust/issues/9259).
