### ISSUE TITLE
[KW-search] Zendesk: Standardize parents and internal ID

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#9259]
Goal is to ensure for **Zendesk** that:
-  Parent ids used in the parents[] array in core data_source_nodes and internal ids from connectors should now match node_id in core data_sources_nodes (= document_id for docs, table_id for tables, folder_id for folders);
- the convention that parents[0] = node_id should be enforced.

The connector should be thoroughly inspected. If there is a convention mismatch, fix it; explained in details in https://github.com/dust-tt/dust/issues/9069

**Comment by philipperolet** [comment]
@aubin-tchoi IIRC you told me all was fine with zendesk? If you're sure about it, this might be the card you work on with the smallest time-to-close ever :)

**Comment by aubin-tchoi** [comment]
Ohh I like this one 👍

**Comment by aubin-tchoi** [comment]
I'll diligently check and close if confirned 👍

**Comment by aubin-tchoi** [comment]
All good :)
Some important details of implementation:
- All conversions between Zendesk ID returned by the API and internal ID are handled in `zendesk/lib/id_conversions.ts`
- The internal IDs are used as document IDs.
- The resources (ZendeskCategoryResource, ZendeskArticleResources, ...) in `resources/zendesk_resources.ts` have `toContentNode` and `getParentInternalIds` methods, which rely on internal IDs and are used in both `getPermissions` and document upsertion.

**Comment by aubin-tchoi** [comment]
One could argue that the other connectors should be a bit more like Zendesk 😇

**Comment by philipperolet** [comment]
I'd point out that Microsoft is also already good then :)

**Comment by aubin-tchoi** [comment]
as some great people would say: \o/
