### ISSUE TITLE
Notion: create folders for `notion-unknown`

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#9457]
Every notion connector should have a notion-unknown folder node, considered as top-level parent for orphans

**Comment by philipperolet** [comment]
Likely we need to have a different nodeId per datasource, e.g. "notion-unknown-[data_source_id]"

**Comment by aubin-tchoi** [comment]
Discussed in https://dust4ai.slack.com/archives/C050SM8NSPK/p1734545151271619
