### ISSUE TITLE
Space Creation: Deleted Space Names Trigger Unique Constraint Error

### ISSUE THREAD

**Issue by cadinette** [dust-tt/dust#9470]
**Description**

When creating a new open space with a unique name, the space is successfully created. However, after deleting the newly created space, attempting to create another space using the same name triggers an error. The error message indicates an internal server issue with a SequelizeUniqueConstraintError: Validation error, suggesting the name is still being treated as non-unique despite the original space being deleted.

**Video**

https://www.loom.com/share/0517839429f14de3a0af6bd0f00933cc?sid=47cf6e1d-e74d-4032-9156-bbd0db89b66e

**Steps to Reproduce**

1. Create a new open space using a unique name
2. Delete the newly created open space
3. Attempt to create a new open space using the same name as the previously deleted space
4. Observe the error message:
```
Error creating space
Error: Unhandled internal server error: SequelizeUniqueConstraintError: Validation error.
```

**Comment by tdraier** [comment]
https://github.com/dust-tt/dust/pull/9476
