### ISSUE TITLE
Assistant Creation: Tab Strip Not Engaging When Clicking On "Next"

### ISSUE THREAD

**Issue by cadinette** [dust-tt/dust#9472]
**Description**

In the assistant creation flow, when navigating between the "Instructions," "Tools & Data Sources," and "Naming" sections using the 'Next' button, the section name at the top does not underline to indicate the active page. However, clicking directly on the section names updates the underline as expected.

**Video**

https://www.loom.com/share/460955e173b94b789c8a37ad96ff16db?sid=a9db5c45-304a-4bee-a0e1-48e5ad347cf3

**Steps to Reproduce**

1. Open the flow to create an assistant
2. Click 'Next' to move from one section to another (e.g., from "Instructions" to "Tools & Data Sources")
3. Observe that the section name at the top is not underlined to indicate the active page
4. Click directly on any section name (e.g., "Naming") and observe that the underline appears correctly

**Comment by tdraier** [comment]
I cannot reproduce, tested on chrome/firefox/arc/safari

**Comment by spolu** [comment]
Looks like it was fixed.
