### ISSUE TITLE
Slack, Notion, Github: on connector delete, also delete folders

### ISSUE THREAD

**Issue by philipperolet** [dust-tt/dust#9511]

**Comment by philipperolet** [comment]
ping @overmode => did you already handle for Github? if not, you can leave it we'll address in this card

**Comment by overmode** [comment]
I didn't, we will tackle it later then

**Comment by aubin-tchoi** [comment]
Let's not forget about the notion-unkown folder

**Comment by philipperolet** [comment]
@aubin-tchoi if you have bandwidth or @overmode once your PRs are merged

**Comment by aubin-tchoi** [comment]
will see who get there first :)

**Comment by aubin-tchoi** [comment]
same as [#9510](https://github.com/dust-tt/dust/issues/9510), this is already handled in core
